// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_Hello
	//	*Envelope_Heartbeat
	//	*Envelope_Request
	//	*Envelope_Response
	//	*Envelope_LogChunk
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Envelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Envelope) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Envelope) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Envelope) GetLogChunk() *LogChunk {
	if x != nil {
		if x, ok := x.Body.(*Envelope_LogChunk); ok {
			return x.LogChunk
		}
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_Hello struct {
	Hello *Hello `protobuf:"bytes,2,opt,name=hello,proto3,oneof"`
}

type Envelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type Envelope_Request struct {
	Request *Request `protobuf:"bytes,4,opt,name=request,proto3,oneof"`
}

type Envelope_Response struct {
	Response *Response `protobuf:"bytes,5,opt,name=response,proto3,oneof"`
}

type Envelope_LogChunk struct {
	LogChunk *LogChunk `protobuf:"bytes,6,opt,name=log_chunk,json=logChunk,proto3,oneof"`
}

func (*Envelope_Hello) isEnvelope_Body() {}

func (*Envelope_Heartbeat) isEnvelope_Body() {}

func (*Envelope_Request) isEnvelope_Body() {}

func (*Envelope_Response) isEnvelope_Body() {}

func (*Envelope_LogChunk) isEnvelope_Body() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion  string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	TproxyVersion string                 `protobuf:"bytes,2,opt,name=tproxy_version,json=tproxyVersion,proto3" json:"tproxy_version,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetTproxyVersion() string {
	if x != nil {
		return x.TproxyVersion
	}
	return ""
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        *HealthReport          `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetHealth() *HealthReport {
	if x != nil {
		return x.Health
	}
	return nil
}

type HealthReport struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	RelayActive              bool                   `protobuf:"varint,1,opt,name=relay_active,json=relayActive,proto3" json:"relay_active,omitempty"`
	MtproxyActive            bool                   `protobuf:"varint,2,opt,name=mtproxy_active,json=mtproxyActive,proto3" json:"mtproxy_active,omitempty"`
	CaddyActive              bool                   `protobuf:"varint,3,opt,name=caddy_active,json=caddyActive,proto3" json:"caddy_active,omitempty"`
	Healthz                  bool                   `protobuf:"varint,4,opt,name=healthz,proto3" json:"healthz,omitempty"`
	Readyz                   bool                   `protobuf:"varint,5,opt,name=readyz,proto3" json:"readyz,omitempty"`
	TproxyVersion            string                 `protobuf:"bytes,6,opt,name=tproxy_version,json=tproxyVersion,proto3" json:"tproxy_version,omitempty"`
	AgentVersion             string                 `protobuf:"bytes,7,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	UptimeSeconds            int64                  `protobuf:"varint,8,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	CpuPercent               float64                `protobuf:"fixed64,9,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemUsedPercent           float64                `protobuf:"fixed64,10,opt,name=mem_used_percent,json=memUsedPercent,proto3" json:"mem_used_percent,omitempty"`
	DiskUsedPercent          float64                `protobuf:"fixed64,11,opt,name=disk_used_percent,json=diskUsedPercent,proto3" json:"disk_used_percent,omitempty"`
	ProfileCount             int32                  `protobuf:"varint,12,opt,name=profile_count,json=profileCount,proto3" json:"profile_count,omitempty"`
	Dcs                      []*DcLatency           `protobuf:"bytes,13,rep,name=dcs,proto3" json:"dcs,omitempty"`
	UpstreamHealthy          bool                   `protobuf:"varint,14,opt,name=upstream_healthy,json=upstreamHealthy,proto3" json:"upstream_healthy,omitempty"`
	UpstreamFails            int32                  `protobuf:"varint,15,opt,name=upstream_fails,json=upstreamFails,proto3" json:"upstream_fails,omitempty"`
	EffectiveLatencyMs       float64                `protobuf:"fixed64,16,opt,name=effective_latency_ms,json=effectiveLatencyMs,proto3" json:"effective_latency_ms,omitempty"`
	ConnectSuccessTotal      int64                  `protobuf:"varint,17,opt,name=connect_success_total,json=connectSuccessTotal,proto3" json:"connect_success_total,omitempty"`
	ConnectFailTotal         int64                  `protobuf:"varint,18,opt,name=connect_fail_total,json=connectFailTotal,proto3" json:"connect_fail_total,omitempty"`
	UpstreamLastCheckAgeSecs int64                  `protobuf:"varint,19,opt,name=upstream_last_check_age_secs,json=upstreamLastCheckAgeSecs,proto3" json:"upstream_last_check_age_secs,omitempty"`
	DcDataAvailable          bool                   `protobuf:"varint,20,opt,name=dc_data_available,json=dcDataAvailable,proto3" json:"dc_data_available,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HealthReport) GetRelayActive() bool {
	if x != nil {
		return x.RelayActive
	}
	return false
}

func (x *HealthReport) GetMtproxyActive() bool {
	if x != nil {
		return x.MtproxyActive
	}
	return false
}

func (x *HealthReport) GetCaddyActive() bool {
	if x != nil {
		return x.CaddyActive
	}
	return false
}

func (x *HealthReport) GetHealthz() bool {
	if x != nil {
		return x.Healthz
	}
	return false
}

func (x *HealthReport) GetReadyz() bool {
	if x != nil {
		return x.Readyz
	}
	return false
}

func (x *HealthReport) GetTproxyVersion() string {
	if x != nil {
		return x.TproxyVersion
	}
	return ""
}

func (x *HealthReport) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HealthReport) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthReport) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *HealthReport) GetMemUsedPercent() float64 {
	if x != nil {
		return x.MemUsedPercent
	}
	return 0
}

func (x *HealthReport) GetDiskUsedPercent() float64 {
	if x != nil {
		return x.DiskUsedPercent
	}
	return 0
}

func (x *HealthReport) GetProfileCount() int32 {
	if x != nil {
		return x.ProfileCount
	}
	return 0
}

func (x *HealthReport) GetDcs() []*DcLatency {
	if x != nil {
		return x.Dcs
	}
	return nil
}

func (x *HealthReport) GetUpstreamHealthy() bool {
	if x != nil {
		return x.UpstreamHealthy
	}
	return false
}

func (x *HealthReport) GetUpstreamFails() int32 {
	if x != nil {
		return x.UpstreamFails
	}
	return 0
}

func (x *HealthReport) GetEffectiveLatencyMs() float64 {
	if x != nil {
		return x.EffectiveLatencyMs
	}
	return 0
}

func (x *HealthReport) GetConnectSuccessTotal() int64 {
	if x != nil {
		return x.ConnectSuccessTotal
	}
	return 0
}

func (x *HealthReport) GetConnectFailTotal() int64 {
	if x != nil {
		return x.ConnectFailTotal
	}
	return 0
}

func (x *HealthReport) GetUpstreamLastCheckAgeSecs() int64 {
	if x != nil {
		return x.UpstreamLastCheckAgeSecs
	}
	return 0
}

func (x *HealthReport) GetDcDataAvailable() bool {
	if x != nil {
		return x.DcDataAvailable
	}
	return false
}

// DcLatency is one Telegram datacenter as telemt's upstream health check sees it.
type DcLatency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dc            int32                  `protobuf:"varint,1,opt,name=dc,proto3" json:"dc,omitempty"`
	LatencyMs     float64                `protobuf:"fixed64,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Known         bool                   `protobuf:"varint,3,opt,name=known,proto3" json:"known,omitempty"`
	IpPreference  string                 `protobuf:"bytes,4,opt,name=ip_preference,json=ipPreference,proto3" json:"ip_preference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DcLatency) Reset() {
	*x = DcLatency{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DcLatency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DcLatency) ProtoMessage() {}

func (x *DcLatency) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DcLatency.ProtoReflect.Descriptor instead.
func (*DcLatency) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *DcLatency) GetDc() int32 {
	if x != nil {
		return x.Dc
	}
	return 0
}

func (x *DcLatency) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *DcLatency) GetKnown() bool {
	if x != nil {
		return x.Known
	}
	return false
}

func (x *DcLatency) GetIpPreference() string {
	if x != nil {
		return x.IpPreference
	}
	return ""
}

type ProfileLimits struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MaxSessions             int32                  `protobuf:"varint,1,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	MaxStreams              int32                  `protobuf:"varint,2,opt,name=max_streams,json=maxStreams,proto3" json:"max_streams,omitempty"`
	MaxBackendDialsInFlight int32                  `protobuf:"varint,3,opt,name=max_backend_dials_in_flight,json=maxBackendDialsInFlight,proto3" json:"max_backend_dials_in_flight,omitempty"`
	NewSessionsPerMinute    int32                  `protobuf:"varint,4,opt,name=new_sessions_per_minute,json=newSessionsPerMinute,proto3" json:"new_sessions_per_minute,omitempty"`
	NewSessionsBurst        int32                  `protobuf:"varint,5,opt,name=new_sessions_burst,json=newSessionsBurst,proto3" json:"new_sessions_burst,omitempty"`
	NewStreamsPerMinute     int32                  `protobuf:"varint,6,opt,name=new_streams_per_minute,json=newStreamsPerMinute,proto3" json:"new_streams_per_minute,omitempty"`
	NewStreamsBurst         int32                  `protobuf:"varint,7,opt,name=new_streams_burst,json=newStreamsBurst,proto3" json:"new_streams_burst,omitempty"`
	MaxStreamsPerSession    int32                  `protobuf:"varint,8,opt,name=max_streams_per_session,json=maxStreamsPerSession,proto3" json:"max_streams_per_session,omitempty"`
	MaxPendingPerSession    int32                  `protobuf:"varint,9,opt,name=max_pending_per_session,json=maxPendingPerSession,proto3" json:"max_pending_per_session,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ProfileLimits) Reset() {
	*x = ProfileLimits{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileLimits) ProtoMessage() {}

func (x *ProfileLimits) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileLimits.ProtoReflect.Descriptor instead.
func (*ProfileLimits) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ProfileLimits) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *ProfileLimits) GetMaxStreams() int32 {
	if x != nil {
		return x.MaxStreams
	}
	return 0
}

func (x *ProfileLimits) GetMaxBackendDialsInFlight() int32 {
	if x != nil {
		return x.MaxBackendDialsInFlight
	}
	return 0
}

func (x *ProfileLimits) GetNewSessionsPerMinute() int32 {
	if x != nil {
		return x.NewSessionsPerMinute
	}
	return 0
}

func (x *ProfileLimits) GetNewSessionsBurst() int32 {
	if x != nil {
		return x.NewSessionsBurst
	}
	return 0
}

func (x *ProfileLimits) GetNewStreamsPerMinute() int32 {
	if x != nil {
		return x.NewStreamsPerMinute
	}
	return 0
}

func (x *ProfileLimits) GetNewStreamsBurst() int32 {
	if x != nil {
		return x.NewStreamsBurst
	}
	return 0
}

func (x *ProfileLimits) GetMaxStreamsPerSession() int32 {
	if x != nil {
		return x.MaxStreamsPerSession
	}
	return 0
}

func (x *ProfileLimits) GetMaxPendingPerSession() int32 {
	if x != nil {
		return x.MaxPendingPerSession
	}
	return 0
}

type Profile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Secret           string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Backend          string                 `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	CarrierMode      string                 `protobuf:"bytes,4,opt,name=carrier_mode,json=carrierMode,proto3" json:"carrier_mode,omitempty"`
	Limits           *ProfileLimits         `protobuf:"bytes,5,opt,name=limits,proto3" json:"limits,omitempty"`
	DataQuotaBytes   uint64                 `protobuf:"varint,10,opt,name=data_quota_bytes,json=dataQuotaBytes,proto3" json:"data_quota_bytes,omitempty"`
	RateLimitUpBps   uint64                 `protobuf:"varint,11,opt,name=rate_limit_up_bps,json=rateLimitUpBps,proto3" json:"rate_limit_up_bps,omitempty"`
	RateLimitDownBps uint64                 `protobuf:"varint,12,opt,name=rate_limit_down_bps,json=rateLimitDownBps,proto3" json:"rate_limit_down_bps,omitempty"`
	MaxUniqueIps     uint32                 `protobuf:"varint,13,opt,name=max_unique_ips,json=maxUniqueIps,proto3" json:"max_unique_ips,omitempty"`
	MaxTcpConns      uint32                 `protobuf:"varint,14,opt,name=max_tcp_conns,json=maxTcpConns,proto3" json:"max_tcp_conns,omitempty"`
	ExpiresAtUnix    int64                  `protobuf:"varint,15,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	Enabled          bool                   `protobuf:"varint,16,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Profile) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *Profile) GetCarrierMode() string {
	if x != nil {
		return x.CarrierMode
	}
	return ""
}

func (x *Profile) GetLimits() *ProfileLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *Profile) GetDataQuotaBytes() uint64 {
	if x != nil {
		return x.DataQuotaBytes
	}
	return 0
}

func (x *Profile) GetRateLimitUpBps() uint64 {
	if x != nil {
		return x.RateLimitUpBps
	}
	return 0
}

func (x *Profile) GetRateLimitDownBps() uint64 {
	if x != nil {
		return x.RateLimitDownBps
	}
	return 0
}

func (x *Profile) GetMaxUniqueIps() uint32 {
	if x != nil {
		return x.MaxUniqueIps
	}
	return 0
}

func (x *Profile) GetMaxTcpConns() uint32 {
	if x != nil {
		return x.MaxTcpConns
	}
	return 0
}

func (x *Profile) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *Profile) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ProfilesFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilesFile) Reset() {
	*x = ProfilesFile{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilesFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilesFile) ProtoMessage() {}

func (x *ProfilesFile) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilesFile.ProtoReflect.Descriptor instead.
func (*ProfilesFile) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ProfilesFile) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

type SiteFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteFile) Reset() {
	*x = SiteFile{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteFile) ProtoMessage() {}

func (x *SiteFile) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteFile.ProtoReflect.Descriptor instead.
func (*SiteFile) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *SiteFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SiteFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type SiteBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*SiteFile            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteBundle) Reset() {
	*x = SiteBundle{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteBundle) ProtoMessage() {}

func (x *SiteBundle) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteBundle.ProtoReflect.Descriptor instead.
func (*SiteBundle) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *SiteBundle) GetFiles() []*SiteFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Request_Health
	//	*Request_GetProfiles
	//	*Request_Apply
	//	*Request_GetSite
	//	*Request_Metrics
	//	*Request_Stats
	//	*Request_TailLogs
	//	*Request_RestartRelay
	Body          isRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *Request) GetBody() isRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Request) GetHealth() *HealthRequest {
	if x != nil {
		if x, ok := x.Body.(*Request_Health); ok {
			return x.Health
		}
	}
	return nil
}

func (x *Request) GetGetProfiles() *GetProfilesRequest {
	if x != nil {
		if x, ok := x.Body.(*Request_GetProfiles); ok {
			return x.GetProfiles
		}
	}
	return nil
}

func (x *Request) GetApply() *ApplyRequest {
	if x != nil {
		if x, ok := x.Body.(*Request_Apply); ok {
			return x.Apply
		}
	}
	return nil
}

func (x *Request) GetGetSite() *GetSiteRequest {
	if x != nil {
		if x, ok := x.Body.(*Request_GetSite); ok {
			return x.GetSite
		}
	}
	return nil
}

func (x *Request) GetMetrics() *MetricsRequest {
	if x != nil {
		if x, ok := x.Body.(*Request_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *Request) GetStats() *StatsRequest {
	if x != nil {
		if x, ok := x.Body.(*Request_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

func (x *Request) GetTailLogs() *TailLogsRequest {
	if x != nil {
		if x, ok := x.Body.(*Request_TailLogs); ok {
			return x.TailLogs
		}
	}
	return nil
}

func (x *Request) GetRestartRelay() *RestartRelayRequest {
	if x != nil {
		if x, ok := x.Body.(*Request_RestartRelay); ok {
			return x.RestartRelay
		}
	}
	return nil
}

type isRequest_Body interface {
	isRequest_Body()
}

type Request_Health struct {
	Health *HealthRequest `protobuf:"bytes,1,opt,name=health,proto3,oneof"`
}

type Request_GetProfiles struct {
	GetProfiles *GetProfilesRequest `protobuf:"bytes,2,opt,name=get_profiles,json=getProfiles,proto3,oneof"`
}

type Request_Apply struct {
	Apply *ApplyRequest `protobuf:"bytes,3,opt,name=apply,proto3,oneof"`
}

type Request_GetSite struct {
	GetSite *GetSiteRequest `protobuf:"bytes,4,opt,name=get_site,json=getSite,proto3,oneof"`
}

type Request_Metrics struct {
	Metrics *MetricsRequest `protobuf:"bytes,5,opt,name=metrics,proto3,oneof"`
}

type Request_Stats struct {
	Stats *StatsRequest `protobuf:"bytes,6,opt,name=stats,proto3,oneof"`
}

type Request_TailLogs struct {
	TailLogs *TailLogsRequest `protobuf:"bytes,7,opt,name=tail_logs,json=tailLogs,proto3,oneof"`
}

type Request_RestartRelay struct {
	RestartRelay *RestartRelayRequest `protobuf:"bytes,8,opt,name=restart_relay,json=restartRelay,proto3,oneof"`
}

func (*Request_Health) isRequest_Body() {}

func (*Request_GetProfiles) isRequest_Body() {}

func (*Request_Apply) isRequest_Body() {}

func (*Request_GetSite) isRequest_Body() {}

func (*Request_Metrics) isRequest_Body() {}

func (*Request_Stats) isRequest_Body() {}

func (*Request_TailLogs) isRequest_Body() {}

func (*Request_RestartRelay) isRequest_Body() {}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

type GetProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfilesRequest) Reset() {
	*x = GetProfilesRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilesRequest) ProtoMessage() {}

func (x *GetProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilesRequest.ProtoReflect.Descriptor instead.
func (*GetProfilesRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

type ApplyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ApplyProfiles  bool                   `protobuf:"varint,1,opt,name=apply_profiles,json=applyProfiles,proto3" json:"apply_profiles,omitempty"`
	Profiles       []*Profile             `protobuf:"bytes,2,rep,name=profiles,proto3" json:"profiles,omitempty"`
	MtproxySecrets []string               `protobuf:"bytes,3,rep,name=mtproxy_secrets,json=mtproxySecrets,proto3" json:"mtproxy_secrets,omitempty"`
	Site           *SiteBundle            `protobuf:"bytes,4,opt,name=site,proto3" json:"site,omitempty"` // nil = leave site untouched
	TlsDomain      string                 `protobuf:"bytes,5,opt,name=tls_domain,json=tlsDomain,proto3" json:"tls_domain,omitempty"`
	ClassicPort    uint32                 `protobuf:"varint,6,opt,name=classic_port,json=classicPort,proto3" json:"classic_port,omitempty"`
	PublicIp       string                 `protobuf:"bytes,7,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	AdTag          string                 `protobuf:"bytes,8,opt,name=ad_tag,json=adTag,proto3" json:"ad_tag,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ApplyRequest) GetApplyProfiles() bool {
	if x != nil {
		return x.ApplyProfiles
	}
	return false
}

func (x *ApplyRequest) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *ApplyRequest) GetMtproxySecrets() []string {
	if x != nil {
		return x.MtproxySecrets
	}
	return nil
}

func (x *ApplyRequest) GetSite() *SiteBundle {
	if x != nil {
		return x.Site
	}
	return nil
}

func (x *ApplyRequest) GetTlsDomain() string {
	if x != nil {
		return x.TlsDomain
	}
	return ""
}

func (x *ApplyRequest) GetClassicPort() uint32 {
	if x != nil {
		return x.ClassicPort
	}
	return 0
}

func (x *ApplyRequest) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *ApplyRequest) GetAdTag() string {
	if x != nil {
		return x.AdTag
	}
	return ""
}

type GetSiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteRequest) Reset() {
	*x = GetSiteRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteRequest) ProtoMessage() {}

func (x *GetSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteRequest.ProtoReflect.Descriptor instead.
func (*GetSiteRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

type TailLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []string               `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Lines         int32                  `protobuf:"varint,2,opt,name=lines,proto3" json:"lines,omitempty"`
	Follow        bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailLogsRequest) Reset() {
	*x = TailLogsRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailLogsRequest) ProtoMessage() {}

func (x *TailLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailLogsRequest.ProtoReflect.Descriptor instead.
func (*TailLogsRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *TailLogsRequest) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *TailLogsRequest) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

func (x *TailLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type RestartRelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartRelayRequest) Reset() {
	*x = RestartRelayRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartRelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRelayRequest) ProtoMessage() {}

func (x *RestartRelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartRelayRequest.ProtoReflect.Descriptor instead.
func (*RestartRelayRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Error string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Response_Health
	//	*Response_Profiles
	//	*Response_Apply
	//	*Response_Site
	//	*Response_Metrics
	//	*Response_Stats
	//	*Response_Empty
	Body          isResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response) GetBody() isResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Response) GetHealth() *HealthReport {
	if x != nil {
		if x, ok := x.Body.(*Response_Health); ok {
			return x.Health
		}
	}
	return nil
}

func (x *Response) GetProfiles() *ProfilesFile {
	if x != nil {
		if x, ok := x.Body.(*Response_Profiles); ok {
			return x.Profiles
		}
	}
	return nil
}

func (x *Response) GetApply() *ApplyResult {
	if x != nil {
		if x, ok := x.Body.(*Response_Apply); ok {
			return x.Apply
		}
	}
	return nil
}

func (x *Response) GetSite() *SiteBundle {
	if x != nil {
		if x, ok := x.Body.(*Response_Site); ok {
			return x.Site
		}
	}
	return nil
}

func (x *Response) GetMetrics() *MetricsText {
	if x != nil {
		if x, ok := x.Body.(*Response_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *Response) GetStats() *StatsMap {
	if x != nil {
		if x, ok := x.Body.(*Response_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

func (x *Response) GetEmpty() *Empty {
	if x != nil {
		if x, ok := x.Body.(*Response_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

type isResponse_Body interface {
	isResponse_Body()
}

type Response_Health struct {
	Health *HealthReport `protobuf:"bytes,2,opt,name=health,proto3,oneof"`
}

type Response_Profiles struct {
	Profiles *ProfilesFile `protobuf:"bytes,3,opt,name=profiles,proto3,oneof"`
}

type Response_Apply struct {
	Apply *ApplyResult `protobuf:"bytes,4,opt,name=apply,proto3,oneof"`
}

type Response_Site struct {
	Site *SiteBundle `protobuf:"bytes,5,opt,name=site,proto3,oneof"`
}

type Response_Metrics struct {
	Metrics *MetricsText `protobuf:"bytes,6,opt,name=metrics,proto3,oneof"`
}

type Response_Stats struct {
	Stats *StatsMap `protobuf:"bytes,7,opt,name=stats,proto3,oneof"`
}

type Response_Empty struct {
	Empty *Empty `protobuf:"bytes,8,opt,name=empty,proto3,oneof"`
}

func (*Response_Health) isResponse_Body() {}

func (*Response_Profiles) isResponse_Body() {}

func (*Response_Apply) isResponse_Body() {}

func (*Response_Site) isResponse_Body() {}

func (*Response_Metrics) isResponse_Body() {}

func (*Response_Stats) isResponse_Body() {}

func (*Response_Empty) isResponse_Body() {}

type ApplyResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ok               bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	RestartedRelay   bool                   `protobuf:"varint,2,opt,name=restarted_relay,json=restartedRelay,proto3" json:"restarted_relay,omitempty"`
	RestartedMtproxy bool                   `protobuf:"varint,3,opt,name=restarted_mtproxy,json=restartedMtproxy,proto3" json:"restarted_mtproxy,omitempty"`
	RolledBack       bool                   `protobuf:"varint,4,opt,name=rolled_back,json=rolledBack,proto3" json:"rolled_back,omitempty"`
	Log              string                 `protobuf:"bytes,5,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApplyResult) Reset() {
	*x = ApplyResult{}
	mi := &file_agent_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResult) ProtoMessage() {}

func (x *ApplyResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResult.ProtoReflect.Descriptor instead.
func (*ApplyResult) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *ApplyResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ApplyResult) GetRestartedRelay() bool {
	if x != nil {
		return x.RestartedRelay
	}
	return false
}

func (x *ApplyResult) GetRestartedMtproxy() bool {
	if x != nil {
		return x.RestartedMtproxy
	}
	return false
}

func (x *ApplyResult) GetRolledBack() bool {
	if x != nil {
		return x.RolledBack
	}
	return false
}

func (x *ApplyResult) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

type MetricsText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsText) Reset() {
	*x = MetricsText{}
	mi := &file_agent_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsText) ProtoMessage() {}

func (x *MetricsText) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsText.ProtoReflect.Descriptor instead.
func (*MetricsText) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *MetricsText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type StatsMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsMap) Reset() {
	*x = StatsMap{}
	mi := &file_agent_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsMap) ProtoMessage() {}

func (x *StatsMap) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsMap.ProtoReflect.Descriptor instead.
func (*StatsMap) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{22}
}

func (x *StatsMap) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_agent_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{23}
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	UnixMs        int64                  `protobuf:"varint,3,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_agent_v1_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{24}
}

func (x *LogLine) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogLine) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []*LogLine             `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_agent_v1_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{25}
}

func (x *LogChunk) GetLines() []*LogLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *LogChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *LogChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\"\xa3\x02\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x05hello\x18\x02 \x01(\v2\x0f.agent.v1.HelloH\x00R\x05hello\x123\n" +
	"\theartbeat\x18\x03 \x01(\v2\x13.agent.v1.HeartbeatH\x00R\theartbeat\x12-\n" +
	"\arequest\x18\x04 \x01(\v2\x11.agent.v1.RequestH\x00R\arequest\x120\n" +
	"\bresponse\x18\x05 \x01(\v2\x12.agent.v1.ResponseH\x00R\bresponse\x121\n" +
	"\tlog_chunk\x18\x06 \x01(\v2\x12.agent.v1.LogChunkH\x00R\blogChunkB\x06\n" +
	"\x04body\"o\n" +
	"\x05Hello\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12%\n" +
	"\x0etproxy_version\x18\x02 \x01(\tR\rtproxyVersion\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\";\n" +
	"\tHeartbeat\x12.\n" +
	"\x06health\x18\x01 \x01(\v2\x16.agent.v1.HealthReportR\x06health\"\xb5\x06\n" +
	"\fHealthReport\x12!\n" +
	"\frelay_active\x18\x01 \x01(\bR\vrelayActive\x12%\n" +
	"\x0emtproxy_active\x18\x02 \x01(\bR\rmtproxyActive\x12!\n" +
	"\fcaddy_active\x18\x03 \x01(\bR\vcaddyActive\x12\x18\n" +
	"\ahealthz\x18\x04 \x01(\bR\ahealthz\x12\x16\n" +
	"\x06readyz\x18\x05 \x01(\bR\x06readyz\x12%\n" +
	"\x0etproxy_version\x18\x06 \x01(\tR\rtproxyVersion\x12#\n" +
	"\ragent_version\x18\a \x01(\tR\fagentVersion\x12%\n" +
	"\x0euptime_seconds\x18\b \x01(\x03R\ruptimeSeconds\x12\x1f\n" +
	"\vcpu_percent\x18\t \x01(\x01R\n" +
	"cpuPercent\x12(\n" +
	"\x10mem_used_percent\x18\n" +
	" \x01(\x01R\x0ememUsedPercent\x12*\n" +
	"\x11disk_used_percent\x18\v \x01(\x01R\x0fdiskUsedPercent\x12#\n" +
	"\rprofile_count\x18\f \x01(\x05R\fprofileCount\x12%\n" +
	"\x03dcs\x18\r \x03(\v2\x13.agent.v1.DcLatencyR\x03dcs\x12)\n" +
	"\x10upstream_healthy\x18\x0e \x01(\bR\x0fupstreamHealthy\x12%\n" +
	"\x0eupstream_fails\x18\x0f \x01(\x05R\rupstreamFails\x120\n" +
	"\x14effective_latency_ms\x18\x10 \x01(\x01R\x12effectiveLatencyMs\x122\n" +
	"\x15connect_success_total\x18\x11 \x01(\x03R\x13connectSuccessTotal\x12,\n" +
	"\x12connect_fail_total\x18\x12 \x01(\x03R\x10connectFailTotal\x12>\n" +
	"\x1cupstream_last_check_age_secs\x18\x13 \x01(\x03R\x18upstreamLastCheckAgeSecs\x12*\n" +
	"\x11dc_data_available\x18\x14 \x01(\bR\x0fdcDataAvailable\"u\n" +
	"\tDcLatency\x12\x0e\n" +
	"\x02dc\x18\x01 \x01(\x05R\x02dc\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x01R\tlatencyMs\x12\x14\n" +
	"\x05known\x18\x03 \x01(\bR\x05known\x12#\n" +
	"\rip_preference\x18\x04 \x01(\tR\fipPreference\"\xc5\x03\n" +
	"\rProfileLimits\x12!\n" +
	"\fmax_sessions\x18\x01 \x01(\x05R\vmaxSessions\x12\x1f\n" +
	"\vmax_streams\x18\x02 \x01(\x05R\n" +
	"maxStreams\x12<\n" +
	"\x1bmax_backend_dials_in_flight\x18\x03 \x01(\x05R\x17maxBackendDialsInFlight\x125\n" +
	"\x17new_sessions_per_minute\x18\x04 \x01(\x05R\x14newSessionsPerMinute\x12,\n" +
	"\x12new_sessions_burst\x18\x05 \x01(\x05R\x10newSessionsBurst\x123\n" +
	"\x16new_streams_per_minute\x18\x06 \x01(\x05R\x13newStreamsPerMinute\x12*\n" +
	"\x11new_streams_burst\x18\a \x01(\x05R\x0fnewStreamsBurst\x125\n" +
	"\x17max_streams_per_session\x18\b \x01(\x05R\x14maxStreamsPerSession\x125\n" +
	"\x17max_pending_per_session\x18\t \x01(\x05R\x14maxPendingPerSession\"\xb3\x03\n" +
	"\aProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend\x12!\n" +
	"\fcarrier_mode\x18\x04 \x01(\tR\vcarrierMode\x12/\n" +
	"\x06limits\x18\x05 \x01(\v2\x17.agent.v1.ProfileLimitsR\x06limits\x12(\n" +
	"\x10data_quota_bytes\x18\n" +
	" \x01(\x04R\x0edataQuotaBytes\x12)\n" +
	"\x11rate_limit_up_bps\x18\v \x01(\x04R\x0erateLimitUpBps\x12-\n" +
	"\x13rate_limit_down_bps\x18\f \x01(\x04R\x10rateLimitDownBps\x12$\n" +
	"\x0emax_unique_ips\x18\r \x01(\rR\fmaxUniqueIps\x12\"\n" +
	"\rmax_tcp_conns\x18\x0e \x01(\rR\vmaxTcpConns\x12&\n" +
	"\x0fexpires_at_unix\x18\x0f \x01(\x03R\rexpiresAtUnix\x12\x18\n" +
	"\aenabled\x18\x10 \x01(\bR\aenabled\"=\n" +
	"\fProfilesFile\x12-\n" +
	"\bprofiles\x18\x01 \x03(\v2\x11.agent.v1.ProfileR\bprofiles\"8\n" +
	"\bSiteFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"6\n" +
	"\n" +
	"SiteBundle\x12(\n" +
	"\x05files\x18\x01 \x03(\v2\x12.agent.v1.SiteFileR\x05files\"\xd4\x03\n" +
	"\aRequest\x121\n" +
	"\x06health\x18\x01 \x01(\v2\x17.agent.v1.HealthRequestH\x00R\x06health\x12A\n" +
	"\fget_profiles\x18\x02 \x01(\v2\x1c.agent.v1.GetProfilesRequestH\x00R\vgetProfiles\x12.\n" +
	"\x05apply\x18\x03 \x01(\v2\x16.agent.v1.ApplyRequestH\x00R\x05apply\x125\n" +
	"\bget_site\x18\x04 \x01(\v2\x18.agent.v1.GetSiteRequestH\x00R\agetSite\x124\n" +
	"\ametrics\x18\x05 \x01(\v2\x18.agent.v1.MetricsRequestH\x00R\ametrics\x12.\n" +
	"\x05stats\x18\x06 \x01(\v2\x16.agent.v1.StatsRequestH\x00R\x05stats\x128\n" +
	"\ttail_logs\x18\a \x01(\v2\x19.agent.v1.TailLogsRequestH\x00R\btailLogs\x12D\n" +
	"\rrestart_relay\x18\b \x01(\v2\x1d.agent.v1.RestartRelayRequestH\x00R\frestartRelayB\x06\n" +
	"\x04body\"\x0f\n" +
	"\rHealthRequest\"\x14\n" +
	"\x12GetProfilesRequest\"\xad\x02\n" +
	"\fApplyRequest\x12%\n" +
	"\x0eapply_profiles\x18\x01 \x01(\bR\rapplyProfiles\x12-\n" +
	"\bprofiles\x18\x02 \x03(\v2\x11.agent.v1.ProfileR\bprofiles\x12'\n" +
	"\x0fmtproxy_secrets\x18\x03 \x03(\tR\x0emtproxySecrets\x12(\n" +
	"\x04site\x18\x04 \x01(\v2\x14.agent.v1.SiteBundleR\x04site\x12\x1d\n" +
	"\n" +
	"tls_domain\x18\x05 \x01(\tR\ttlsDomain\x12!\n" +
	"\fclassic_port\x18\x06 \x01(\rR\vclassicPort\x12\x1b\n" +
	"\tpublic_ip\x18\a \x01(\tR\bpublicIp\x12\x15\n" +
	"\x06ad_tag\x18\b \x01(\tR\x05adTag\"\x10\n" +
	"\x0eGetSiteRequest\"\x10\n" +
	"\x0eMetricsRequest\"\x0e\n" +
	"\fStatsRequest\"[\n" +
	"\x0fTailLogsRequest\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices\x12\x14\n" +
	"\x05lines\x18\x02 \x01(\x05R\x05lines\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\"\x15\n" +
	"\x13RestartRelayRequest\"\xf3\x02\n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x120\n" +
	"\x06health\x18\x02 \x01(\v2\x16.agent.v1.HealthReportH\x00R\x06health\x124\n" +
	"\bprofiles\x18\x03 \x01(\v2\x16.agent.v1.ProfilesFileH\x00R\bprofiles\x12-\n" +
	"\x05apply\x18\x04 \x01(\v2\x15.agent.v1.ApplyResultH\x00R\x05apply\x12*\n" +
	"\x04site\x18\x05 \x01(\v2\x14.agent.v1.SiteBundleH\x00R\x04site\x121\n" +
	"\ametrics\x18\x06 \x01(\v2\x15.agent.v1.MetricsTextH\x00R\ametrics\x12*\n" +
	"\x05stats\x18\a \x01(\v2\x12.agent.v1.StatsMapH\x00R\x05stats\x12'\n" +
	"\x05empty\x18\b \x01(\v2\x0f.agent.v1.EmptyH\x00R\x05emptyB\x06\n" +
	"\x04body\"\xa6\x01\n" +
	"\vApplyResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12'\n" +
	"\x0frestarted_relay\x18\x02 \x01(\bR\x0erestartedRelay\x12+\n" +
	"\x11restarted_mtproxy\x18\x03 \x01(\bR\x10restartedMtproxy\x12\x1f\n" +
	"\vrolled_back\x18\x04 \x01(\bR\n" +
	"rolledBack\x12\x10\n" +
	"\x03log\x18\x05 \x01(\tR\x03log\"!\n" +
	"\vMetricsText\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"}\n" +
	"\bStatsMap\x126\n" +
	"\x06values\x18\x01 \x03(\v2\x1e.agent.v1.StatsMap.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\a\n" +
	"\x05Empty\"P\n" +
	"\aLogLine\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x12\x17\n" +
	"\aunix_ms\x18\x03 \x01(\x03R\x06unixMs\"]\n" +
	"\bLogChunk\x12'\n" +
	"\x05lines\x18\x01 \x03(\v2\x11.agent.v1.LogLineR\x05lines\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2E\n" +
	"\fAgentGateway\x125\n" +
	"\aSession\x12\x12.agent.v1.Envelope\x1a\x12.agent.v1.Envelope(\x010\x01B#Z!tgwebproxy/proto/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_agent_v1_agent_proto_goTypes = []any{
	(*Envelope)(nil),            // 0: agent.v1.Envelope
	(*Hello)(nil),               // 1: agent.v1.Hello
	(*Heartbeat)(nil),           // 2: agent.v1.Heartbeat
	(*HealthReport)(nil),        // 3: agent.v1.HealthReport
	(*DcLatency)(nil),           // 4: agent.v1.DcLatency
	(*ProfileLimits)(nil),       // 5: agent.v1.ProfileLimits
	(*Profile)(nil),             // 6: agent.v1.Profile
	(*ProfilesFile)(nil),        // 7: agent.v1.ProfilesFile
	(*SiteFile)(nil),            // 8: agent.v1.SiteFile
	(*SiteBundle)(nil),          // 9: agent.v1.SiteBundle
	(*Request)(nil),             // 10: agent.v1.Request
	(*HealthRequest)(nil),       // 11: agent.v1.HealthRequest
	(*GetProfilesRequest)(nil),  // 12: agent.v1.GetProfilesRequest
	(*ApplyRequest)(nil),        // 13: agent.v1.ApplyRequest
	(*GetSiteRequest)(nil),      // 14: agent.v1.GetSiteRequest
	(*MetricsRequest)(nil),      // 15: agent.v1.MetricsRequest
	(*StatsRequest)(nil),        // 16: agent.v1.StatsRequest
	(*TailLogsRequest)(nil),     // 17: agent.v1.TailLogsRequest
	(*RestartRelayRequest)(nil), // 18: agent.v1.RestartRelayRequest
	(*Response)(nil),            // 19: agent.v1.Response
	(*ApplyResult)(nil),         // 20: agent.v1.ApplyResult
	(*MetricsText)(nil),         // 21: agent.v1.MetricsText
	(*StatsMap)(nil),            // 22: agent.v1.StatsMap
	(*Empty)(nil),               // 23: agent.v1.Empty
	(*LogLine)(nil),             // 24: agent.v1.LogLine
	(*LogChunk)(nil),            // 25: agent.v1.LogChunk
	nil,                         // 26: agent.v1.StatsMap.ValuesEntry
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	1,  // 0: agent.v1.Envelope.hello:type_name -> agent.v1.Hello
	2,  // 1: agent.v1.Envelope.heartbeat:type_name -> agent.v1.Heartbeat
	10, // 2: agent.v1.Envelope.request:type_name -> agent.v1.Request
	19, // 3: agent.v1.Envelope.response:type_name -> agent.v1.Response
	25, // 4: agent.v1.Envelope.log_chunk:type_name -> agent.v1.LogChunk
	3,  // 5: agent.v1.Heartbeat.health:type_name -> agent.v1.HealthReport
	4,  // 6: agent.v1.HealthReport.dcs:type_name -> agent.v1.DcLatency
	5,  // 7: agent.v1.Profile.limits:type_name -> agent.v1.ProfileLimits
	6,  // 8: agent.v1.ProfilesFile.profiles:type_name -> agent.v1.Profile
	8,  // 9: agent.v1.SiteBundle.files:type_name -> agent.v1.SiteFile
	11, // 10: agent.v1.Request.health:type_name -> agent.v1.HealthRequest
	12, // 11: agent.v1.Request.get_profiles:type_name -> agent.v1.GetProfilesRequest
	13, // 12: agent.v1.Request.apply:type_name -> agent.v1.ApplyRequest
	14, // 13: agent.v1.Request.get_site:type_name -> agent.v1.GetSiteRequest
	15, // 14: agent.v1.Request.metrics:type_name -> agent.v1.MetricsRequest
	16, // 15: agent.v1.Request.stats:type_name -> agent.v1.StatsRequest
	17, // 16: agent.v1.Request.tail_logs:type_name -> agent.v1.TailLogsRequest
	18, // 17: agent.v1.Request.restart_relay:type_name -> agent.v1.RestartRelayRequest
	6,  // 18: agent.v1.ApplyRequest.profiles:type_name -> agent.v1.Profile
	9,  // 19: agent.v1.ApplyRequest.site:type_name -> agent.v1.SiteBundle
	3,  // 20: agent.v1.Response.health:type_name -> agent.v1.HealthReport
	7,  // 21: agent.v1.Response.profiles:type_name -> agent.v1.ProfilesFile
	20, // 22: agent.v1.Response.apply:type_name -> agent.v1.ApplyResult
	9,  // 23: agent.v1.Response.site:type_name -> agent.v1.SiteBundle
	21, // 24: agent.v1.Response.metrics:type_name -> agent.v1.MetricsText
	22, // 25: agent.v1.Response.stats:type_name -> agent.v1.StatsMap
	23, // 26: agent.v1.Response.empty:type_name -> agent.v1.Empty
	26, // 27: agent.v1.StatsMap.values:type_name -> agent.v1.StatsMap.ValuesEntry
	24, // 28: agent.v1.LogChunk.lines:type_name -> agent.v1.LogLine
	0,  // 29: agent.v1.AgentGateway.Session:input_type -> agent.v1.Envelope
	0,  // 30: agent.v1.AgentGateway.Session:output_type -> agent.v1.Envelope
	30, // [30:31] is the sub-list for method output_type
	29, // [29:30] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Hello)(nil),
		(*Envelope_Heartbeat)(nil),
		(*Envelope_Request)(nil),
		(*Envelope_Response)(nil),
		(*Envelope_LogChunk)(nil),
	}
	file_agent_v1_agent_proto_msgTypes[10].OneofWrappers = []any{
		(*Request_Health)(nil),
		(*Request_GetProfiles)(nil),
		(*Request_Apply)(nil),
		(*Request_GetSite)(nil),
		(*Request_Metrics)(nil),
		(*Request_Stats)(nil),
		(*Request_TailLogs)(nil),
		(*Request_RestartRelay)(nil),
	}
	file_agent_v1_agent_proto_msgTypes[19].OneofWrappers = []any{
		(*Response_Health)(nil),
		(*Response_Profiles)(nil),
		(*Response_Apply)(nil),
		(*Response_Site)(nil),
		(*Response_Metrics)(nil),
		(*Response_Stats)(nil),
		(*Response_Empty)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
