// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: agent/v1/agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Envelope struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Envelope_Hello
	//	*Envelope_Heartbeat
	//	*Envelope_Request
	//	*Envelope_Response
	//	*Envelope_LogChunk
	Body          isEnvelope_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Envelope) GetBody() isEnvelope_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Envelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Envelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *Envelope) GetRequest() *Request {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *Envelope) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Body.(*Envelope_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Envelope) GetLogChunk() *LogChunk {
	if x != nil {
		if x, ok := x.Body.(*Envelope_LogChunk); ok {
			return x.LogChunk
		}
	}
	return nil
}

type isEnvelope_Body interface {
	isEnvelope_Body()
}

type Envelope_Hello struct {
	Hello *Hello `protobuf:"bytes,2,opt,name=hello,proto3,oneof"`
}

type Envelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,3,opt,name=heartbeat,proto3,oneof"`
}

type Envelope_Request struct {
	Request *Request `protobuf:"bytes,4,opt,name=request,proto3,oneof"`
}

type Envelope_Response struct {
	Response *Response `protobuf:"bytes,5,opt,name=response,proto3,oneof"`
}

type Envelope_LogChunk struct {
	LogChunk *LogChunk `protobuf:"bytes,6,opt,name=log_chunk,json=logChunk,proto3,oneof"`
}

func (*Envelope_Hello) isEnvelope_Body() {}

func (*Envelope_Heartbeat) isEnvelope_Body() {}

func (*Envelope_Request) isEnvelope_Body() {}

func (*Envelope_Response) isEnvelope_Body() {}

func (*Envelope_LogChunk) isEnvelope_Body() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion  string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	TproxyVersion string                 `protobuf:"bytes,2,opt,name=tproxy_version,json=tproxyVersion,proto3" json:"tproxy_version,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetTproxyVersion() string {
	if x != nil {
		return x.TproxyVersion
	}
	return ""
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Health        *HealthReport          `protobuf:"bytes,1,opt,name=health,proto3" json:"health,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetHealth() *HealthReport {
	if x != nil {
		return x.Health
	}
	return nil
}

type HealthReport struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	RelayActive              bool                   `protobuf:"varint,1,opt,name=relay_active,json=relayActive,proto3" json:"relay_active,omitempty"`
	MtproxyActive            bool                   `protobuf:"varint,2,opt,name=mtproxy_active,json=mtproxyActive,proto3" json:"mtproxy_active,omitempty"`
	CaddyActive              bool                   `protobuf:"varint,3,opt,name=caddy_active,json=caddyActive,proto3" json:"caddy_active,omitempty"`
	Healthz                  bool                   `protobuf:"varint,4,opt,name=healthz,proto3" json:"healthz,omitempty"`
	Readyz                   bool                   `protobuf:"varint,5,opt,name=readyz,proto3" json:"readyz,omitempty"`
	TproxyVersion            string                 `protobuf:"bytes,6,opt,name=tproxy_version,json=tproxyVersion,proto3" json:"tproxy_version,omitempty"`
	AgentVersion             string                 `protobuf:"bytes,7,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	UptimeSeconds            int64                  `protobuf:"varint,8,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	CpuPercent               float64                `protobuf:"fixed64,9,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemUsedPercent           float64                `protobuf:"fixed64,10,opt,name=mem_used_percent,json=memUsedPercent,proto3" json:"mem_used_percent,omitempty"`
	DiskUsedPercent          float64                `protobuf:"fixed64,11,opt,name=disk_used_percent,json=diskUsedPercent,proto3" json:"disk_used_percent,omitempty"`
	ProfileCount             int32                  `protobuf:"varint,12,opt,name=profile_count,json=profileCount,proto3" json:"profile_count,omitempty"`
	Dcs                      []*DcLatency           `protobuf:"bytes,13,rep,name=dcs,proto3" json:"dcs,omitempty"`
	UpstreamHealthy          bool                   `protobuf:"varint,14,opt,name=upstream_healthy,json=upstreamHealthy,proto3" json:"upstream_healthy,omitempty"`
	UpstreamFails            int32                  `protobuf:"varint,15,opt,name=upstream_fails,json=upstreamFails,proto3" json:"upstream_fails,omitempty"`
	EffectiveLatencyMs       float64                `protobuf:"fixed64,16,opt,name=effective_latency_ms,json=effectiveLatencyMs,proto3" json:"effective_latency_ms,omitempty"`
	ConnectSuccessTotal      int64                  `protobuf:"varint,17,opt,name=connect_success_total,json=connectSuccessTotal,proto3" json:"connect_success_total,omitempty"`
	ConnectFailTotal         int64                  `protobuf:"varint,18,opt,name=connect_fail_total,json=connectFailTotal,proto3" json:"connect_fail_total,omitempty"`
	UpstreamLastCheckAgeSecs int64                  `protobuf:"varint,19,opt,name=upstream_last_check_age_secs,json=upstreamLastCheckAgeSecs,proto3" json:"upstream_last_check_age_secs,omitempty"`
	DcDataAvailable          bool                   `protobuf:"varint,20,opt,name=dc_data_available,json=dcDataAvailable,proto3" json:"dc_data_available,omitempty"`
	// web is the WEB transport telemetry; absent when the agent could not read it. An agent
	// that never sets it and a panel that never reads it both keep working.
	Web *WebTelemetry `protobuf:"bytes,21,opt,name=web,proto3" json:"web,omitempty"`
	// capabilities is what the agent worked out the node's telemt can do; absent when the
	// probe did not run or could not reach telemt.
	Capabilities  *TelemtCapabilities `protobuf:"bytes,22,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthReport) Reset() {
	*x = HealthReport{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReport) ProtoMessage() {}

func (x *HealthReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReport.ProtoReflect.Descriptor instead.
func (*HealthReport) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HealthReport) GetRelayActive() bool {
	if x != nil {
		return x.RelayActive
	}
	return false
}

func (x *HealthReport) GetMtproxyActive() bool {
	if x != nil {
		return x.MtproxyActive
	}
	return false
}

func (x *HealthReport) GetCaddyActive() bool {
	if x != nil {
		return x.CaddyActive
	}
	return false
}

func (x *HealthReport) GetHealthz() bool {
	if x != nil {
		return x.Healthz
	}
	return false
}

func (x *HealthReport) GetReadyz() bool {
	if x != nil {
		return x.Readyz
	}
	return false
}

func (x *HealthReport) GetTproxyVersion() string {
	if x != nil {
		return x.TproxyVersion
	}
	return ""
}

func (x *HealthReport) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HealthReport) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthReport) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *HealthReport) GetMemUsedPercent() float64 {
	if x != nil {
		return x.MemUsedPercent
	}
	return 0
}

func (x *HealthReport) GetDiskUsedPercent() float64 {
	if x != nil {
		return x.DiskUsedPercent
	}
	return 0
}

func (x *HealthReport) GetProfileCount() int32 {
	if x != nil {
		return x.ProfileCount
	}
	return 0
}

func (x *HealthReport) GetDcs() []*DcLatency {
	if x != nil {
		return x.Dcs
	}
	return nil
}

func (x *HealthReport) GetUpstreamHealthy() bool {
	if x != nil {
		return x.UpstreamHealthy
	}
	return false
}

func (x *HealthReport) GetUpstreamFails() int32 {
	if x != nil {
		return x.UpstreamFails
	}
	return 0
}

func (x *HealthReport) GetEffectiveLatencyMs() float64 {
	if x != nil {
		return x.EffectiveLatencyMs
	}
	return 0
}

func (x *HealthReport) GetConnectSuccessTotal() int64 {
	if x != nil {
		return x.ConnectSuccessTotal
	}
	return 0
}

func (x *HealthReport) GetConnectFailTotal() int64 {
	if x != nil {
		return x.ConnectFailTotal
	}
	return 0
}

func (x *HealthReport) GetUpstreamLastCheckAgeSecs() int64 {
	if x != nil {
		return x.UpstreamLastCheckAgeSecs
	}
	return 0
}

func (x *HealthReport) GetDcDataAvailable() bool {
	if x != nil {
		return x.DcDataAvailable
	}
	return false
}

func (x *HealthReport) GetWeb() *WebTelemetry {
	if x != nil {
		return x.Web
	}
	return nil
}

func (x *HealthReport) GetCapabilities() *TelemtCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// WebCounterSample is one Prometheus sample of a telemt_web_* family. carrier, label and phase
// are the family's own labels and are empty for a family that does not carry them.
type WebCounterSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Carrier       string                 `protobuf:"bytes,1,opt,name=carrier,proto3" json:"carrier,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Phase         string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebCounterSample) Reset() {
	*x = WebCounterSample{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebCounterSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebCounterSample) ProtoMessage() {}

func (x *WebCounterSample) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebCounterSample.ProtoReflect.Descriptor instead.
func (*WebCounterSample) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *WebCounterSample) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *WebCounterSample) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *WebCounterSample) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *WebCounterSample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// WebCounterFamily is one metric family. The message itself is the presence flag: a family the
// node did not expose is a nil WebCounterFamily, never an empty one, so "not reported" can
// never be read as zero. A present family with no samples is a family telemt declared but has
// not yet incremented.
type WebCounterFamily struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Samples       []*WebCounterSample    `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebCounterFamily) Reset() {
	*x = WebCounterFamily{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebCounterFamily) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebCounterFamily) ProtoMessage() {}

func (x *WebCounterFamily) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebCounterFamily.ProtoReflect.Descriptor instead.
func (*WebCounterFamily) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *WebCounterFamily) GetSamples() []*WebCounterSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type WebLearningState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Enabled          bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	PolicyGeneration uint64                 `protobuf:"varint,2,opt,name=policy_generation,json=policyGeneration,proto3" json:"policy_generation,omitempty"`
	Epoch            uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Entries          int32                  `protobuf:"varint,4,opt,name=entries,proto3" json:"entries,omitempty"`
	Capacity         int32                  `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	LifetimeSecs     int64                  `protobuf:"varint,6,opt,name=lifetime_secs,json=lifetimeSecs,proto3" json:"lifetime_secs,omitempty"`
	HealthSecs       int64                  `protobuf:"varint,7,opt,name=health_secs,json=healthSecs,proto3" json:"health_secs,omitempty"`
	AgeMs            int64                  `protobuf:"varint,8,opt,name=age_ms,json=ageMs,proto3" json:"age_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WebLearningState) Reset() {
	*x = WebLearningState{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebLearningState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebLearningState) ProtoMessage() {}

func (x *WebLearningState) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebLearningState.ProtoReflect.Descriptor instead.
func (*WebLearningState) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *WebLearningState) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *WebLearningState) GetPolicyGeneration() uint64 {
	if x != nil {
		return x.PolicyGeneration
	}
	return 0
}

func (x *WebLearningState) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *WebLearningState) GetEntries() int32 {
	if x != nil {
		return x.Entries
	}
	return 0
}

func (x *WebLearningState) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *WebLearningState) GetLifetimeSecs() int64 {
	if x != nil {
		return x.LifetimeSecs
	}
	return 0
}

func (x *WebLearningState) GetHealthSecs() int64 {
	if x != nil {
		return x.HealthSecs
	}
	return 0
}

func (x *WebLearningState) GetAgeMs() int64 {
	if x != nil {
		return x.AgeMs
	}
	return 0
}

type WebDrainState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OperationId         string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	State               string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Outcome             string                 `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"`
	TimeoutSecs         int32                  `protobuf:"varint,4,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	StartedEpochMillis  int64                  `protobuf:"varint,5,opt,name=started_epoch_millis,json=startedEpochMillis,proto3" json:"started_epoch_millis,omitempty"`
	DeadlineEpochMillis int64                  `protobuf:"varint,6,opt,name=deadline_epoch_millis,json=deadlineEpochMillis,proto3" json:"deadline_epoch_millis,omitempty"`
	RemainingSessions   uint64                 `protobuf:"varint,7,opt,name=remaining_sessions,json=remainingSessions,proto3" json:"remaining_sessions,omitempty"`
	RemainingStreams    uint64                 `protobuf:"varint,8,opt,name=remaining_streams,json=remainingStreams,proto3" json:"remaining_streams,omitempty"`
	RemainingWebsockets uint64                 `protobuf:"varint,9,opt,name=remaining_websockets,json=remainingWebsockets,proto3" json:"remaining_websockets,omitempty"`
	ForceCloseSignalled bool                   `protobuf:"varint,10,opt,name=force_close_signalled,json=forceCloseSignalled,proto3" json:"force_close_signalled,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *WebDrainState) Reset() {
	*x = WebDrainState{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebDrainState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebDrainState) ProtoMessage() {}

func (x *WebDrainState) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebDrainState.ProtoReflect.Descriptor instead.
func (*WebDrainState) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *WebDrainState) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *WebDrainState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *WebDrainState) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *WebDrainState) GetTimeoutSecs() int32 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

func (x *WebDrainState) GetStartedEpochMillis() int64 {
	if x != nil {
		return x.StartedEpochMillis
	}
	return 0
}

func (x *WebDrainState) GetDeadlineEpochMillis() int64 {
	if x != nil {
		return x.DeadlineEpochMillis
	}
	return 0
}

func (x *WebDrainState) GetRemainingSessions() uint64 {
	if x != nil {
		return x.RemainingSessions
	}
	return 0
}

func (x *WebDrainState) GetRemainingStreams() uint64 {
	if x != nil {
		return x.RemainingStreams
	}
	return 0
}

func (x *WebDrainState) GetRemainingWebsockets() uint64 {
	if x != nil {
		return x.RemainingWebsockets
	}
	return 0
}

func (x *WebDrainState) GetForceCloseSignalled() bool {
	if x != nil {
		return x.ForceCloseSignalled
	}
	return false
}

type WebLifecycleState struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	State                     string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Epoch                     uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	AgeMs                     int64                  `protobuf:"varint,3,opt,name=age_ms,json=ageMs,proto3" json:"age_ms,omitempty"`
	AdmissionOpen             bool                   `protobuf:"varint,4,opt,name=admission_open,json=admissionOpen,proto3" json:"admission_open,omitempty"`
	EffectiveNewWorkAdmission bool                   `protobuf:"varint,5,opt,name=effective_new_work_admission,json=effectiveNewWorkAdmission,proto3" json:"effective_new_work_admission,omitempty"`
	Drain                     *WebDrainState         `protobuf:"bytes,6,opt,name=drain,proto3" json:"drain,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *WebLifecycleState) Reset() {
	*x = WebLifecycleState{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebLifecycleState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebLifecycleState) ProtoMessage() {}

func (x *WebLifecycleState) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebLifecycleState.ProtoReflect.Descriptor instead.
func (*WebLifecycleState) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *WebLifecycleState) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *WebLifecycleState) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *WebLifecycleState) GetAgeMs() int64 {
	if x != nil {
		return x.AgeMs
	}
	return 0
}

func (x *WebLifecycleState) GetAdmissionOpen() bool {
	if x != nil {
		return x.AdmissionOpen
	}
	return false
}

func (x *WebLifecycleState) GetEffectiveNewWorkAdmission() bool {
	if x != nil {
		return x.EffectiveNewWorkAdmission
	}
	return false
}

func (x *WebLifecycleState) GetDrain() *WebDrainState {
	if x != nil {
		return x.Drain
	}
	return nil
}

// WebRuntimeState is GET /v1/runtime/web/status as the agent read it. learning and lifecycle
// are nil when telemt's payload carried no such section.
type WebRuntimeState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RuntimeInstance    string                 `protobuf:"bytes,1,opt,name=runtime_instance,json=runtimeInstance,proto3" json:"runtime_instance,omitempty"`
	CarrierNegotiation bool                   `protobuf:"varint,2,opt,name=carrier_negotiation,json=carrierNegotiation,proto3" json:"carrier_negotiation,omitempty"`
	Learning           *WebLearningState      `protobuf:"bytes,3,opt,name=learning,proto3" json:"learning,omitempty"`
	Lifecycle          *WebLifecycleState     `protobuf:"bytes,4,opt,name=lifecycle,proto3" json:"lifecycle,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WebRuntimeState) Reset() {
	*x = WebRuntimeState{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebRuntimeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebRuntimeState) ProtoMessage() {}

func (x *WebRuntimeState) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebRuntimeState.ProtoReflect.Descriptor instead.
func (*WebRuntimeState) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *WebRuntimeState) GetRuntimeInstance() string {
	if x != nil {
		return x.RuntimeInstance
	}
	return ""
}

func (x *WebRuntimeState) GetCarrierNegotiation() bool {
	if x != nil {
		return x.CarrierNegotiation
	}
	return false
}

func (x *WebRuntimeState) GetLearning() *WebLearningState {
	if x != nil {
		return x.Learning
	}
	return nil
}

func (x *WebRuntimeState) GetLifecycle() *WebLifecycleState {
	if x != nil {
		return x.Lifecycle
	}
	return nil
}

// WebTelemetry carries the telemt_web_* families and the WEB runtime state of one node.
// Every family is a nullable message: nil means the node did not report it.
type WebTelemetry struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CarrierSelections *WebCounterFamily      `protobuf:"bytes,1,opt,name=carrier_selections,json=carrierSelections,proto3" json:"carrier_selections,omitempty"`
	CarrierFailures   *WebCounterFamily      `protobuf:"bytes,2,opt,name=carrier_failures,json=carrierFailures,proto3" json:"carrier_failures,omitempty"`
	LearningOutcomes  *WebCounterFamily      `protobuf:"bytes,3,opt,name=learning_outcomes,json=learningOutcomes,proto3" json:"learning_outcomes,omitempty"`
	LearningEntries   *WebCounterFamily      `protobuf:"bytes,4,opt,name=learning_entries,json=learningEntries,proto3" json:"learning_entries,omitempty"`
	Rejections        *WebCounterFamily      `protobuf:"bytes,5,opt,name=rejections,proto3" json:"rejections,omitempty"`
	SessionClosures   *WebCounterFamily      `protobuf:"bytes,6,opt,name=session_closures,json=sessionClosures,proto3" json:"session_closures,omitempty"`
	BridgeRecovery    *WebCounterFamily      `protobuf:"bytes,7,opt,name=bridge_recovery,json=bridgeRecovery,proto3" json:"bridge_recovery,omitempty"`
	Runtime           *WebRuntimeState       `protobuf:"bytes,8,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WebTelemetry) Reset() {
	*x = WebTelemetry{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebTelemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebTelemetry) ProtoMessage() {}

func (x *WebTelemetry) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebTelemetry.ProtoReflect.Descriptor instead.
func (*WebTelemetry) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *WebTelemetry) GetCarrierSelections() *WebCounterFamily {
	if x != nil {
		return x.CarrierSelections
	}
	return nil
}

func (x *WebTelemetry) GetCarrierFailures() *WebCounterFamily {
	if x != nil {
		return x.CarrierFailures
	}
	return nil
}

func (x *WebTelemetry) GetLearningOutcomes() *WebCounterFamily {
	if x != nil {
		return x.LearningOutcomes
	}
	return nil
}

func (x *WebTelemetry) GetLearningEntries() *WebCounterFamily {
	if x != nil {
		return x.LearningEntries
	}
	return nil
}

func (x *WebTelemetry) GetRejections() *WebCounterFamily {
	if x != nil {
		return x.Rejections
	}
	return nil
}

func (x *WebTelemetry) GetSessionClosures() *WebCounterFamily {
	if x != nil {
		return x.SessionClosures
	}
	return nil
}

func (x *WebTelemetry) GetBridgeRecovery() *WebCounterFamily {
	if x != nil {
		return x.BridgeRecovery
	}
	return nil
}

func (x *WebTelemetry) GetRuntime() *WebRuntimeState {
	if x != nil {
		return x.Runtime
	}
	return nil
}

// TelemtCapabilities is the capability set the agent computed. supported holds only the
// capabilities it settled; undetermined names the ones it could not, which the panel must keep
// distinguishable from a capability the node answered "no" to.
type TelemtCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Supported     map[string]bool        `protobuf:"bytes,1,rep,name=supported,proto3" json:"supported,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Undetermined  []string               `protobuf:"bytes,2,rep,name=undetermined,proto3" json:"undetermined,omitempty"`
	Build         string                 `protobuf:"bytes,3,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemtCapabilities) Reset() {
	*x = TelemtCapabilities{}
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemtCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemtCapabilities) ProtoMessage() {}

func (x *TelemtCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemtCapabilities.ProtoReflect.Descriptor instead.
func (*TelemtCapabilities) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *TelemtCapabilities) GetSupported() map[string]bool {
	if x != nil {
		return x.Supported
	}
	return nil
}

func (x *TelemtCapabilities) GetUndetermined() []string {
	if x != nil {
		return x.Undetermined
	}
	return nil
}

func (x *TelemtCapabilities) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

// DcLatency is one Telegram datacenter as telemt's upstream health check sees it.
type DcLatency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dc            int32                  `protobuf:"varint,1,opt,name=dc,proto3" json:"dc,omitempty"`
	LatencyMs     float64                `protobuf:"fixed64,2,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Known         bool                   `protobuf:"varint,3,opt,name=known,proto3" json:"known,omitempty"`
	IpPreference  string                 `protobuf:"bytes,4,opt,name=ip_preference,json=ipPreference,proto3" json:"ip_preference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DcLatency) Reset() {
	*x = DcLatency{}
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DcLatency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DcLatency) ProtoMessage() {}

func (x *DcLatency) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DcLatency.ProtoReflect.Descriptor instead.
func (*DcLatency) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *DcLatency) GetDc() int32 {
	if x != nil {
		return x.Dc
	}
	return 0
}

func (x *DcLatency) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *DcLatency) GetKnown() bool {
	if x != nil {
		return x.Known
	}
	return false
}

func (x *DcLatency) GetIpPreference() string {
	if x != nil {
		return x.IpPreference
	}
	return ""
}

type ProfileLimits struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	MaxSessions             int32                  `protobuf:"varint,1,opt,name=max_sessions,json=maxSessions,proto3" json:"max_sessions,omitempty"`
	MaxStreams              int32                  `protobuf:"varint,2,opt,name=max_streams,json=maxStreams,proto3" json:"max_streams,omitempty"`
	MaxBackendDialsInFlight int32                  `protobuf:"varint,3,opt,name=max_backend_dials_in_flight,json=maxBackendDialsInFlight,proto3" json:"max_backend_dials_in_flight,omitempty"`
	NewSessionsPerMinute    int32                  `protobuf:"varint,4,opt,name=new_sessions_per_minute,json=newSessionsPerMinute,proto3" json:"new_sessions_per_minute,omitempty"`
	NewSessionsBurst        int32                  `protobuf:"varint,5,opt,name=new_sessions_burst,json=newSessionsBurst,proto3" json:"new_sessions_burst,omitempty"`
	NewStreamsPerMinute     int32                  `protobuf:"varint,6,opt,name=new_streams_per_minute,json=newStreamsPerMinute,proto3" json:"new_streams_per_minute,omitempty"`
	NewStreamsBurst         int32                  `protobuf:"varint,7,opt,name=new_streams_burst,json=newStreamsBurst,proto3" json:"new_streams_burst,omitempty"`
	MaxStreamsPerSession    int32                  `protobuf:"varint,8,opt,name=max_streams_per_session,json=maxStreamsPerSession,proto3" json:"max_streams_per_session,omitempty"`
	MaxPendingPerSession    int32                  `protobuf:"varint,9,opt,name=max_pending_per_session,json=maxPendingPerSession,proto3" json:"max_pending_per_session,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ProfileLimits) Reset() {
	*x = ProfileLimits{}
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfileLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileLimits) ProtoMessage() {}

func (x *ProfileLimits) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileLimits.ProtoReflect.Descriptor instead.
func (*ProfileLimits) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ProfileLimits) GetMaxSessions() int32 {
	if x != nil {
		return x.MaxSessions
	}
	return 0
}

func (x *ProfileLimits) GetMaxStreams() int32 {
	if x != nil {
		return x.MaxStreams
	}
	return 0
}

func (x *ProfileLimits) GetMaxBackendDialsInFlight() int32 {
	if x != nil {
		return x.MaxBackendDialsInFlight
	}
	return 0
}

func (x *ProfileLimits) GetNewSessionsPerMinute() int32 {
	if x != nil {
		return x.NewSessionsPerMinute
	}
	return 0
}

func (x *ProfileLimits) GetNewSessionsBurst() int32 {
	if x != nil {
		return x.NewSessionsBurst
	}
	return 0
}

func (x *ProfileLimits) GetNewStreamsPerMinute() int32 {
	if x != nil {
		return x.NewStreamsPerMinute
	}
	return 0
}

func (x *ProfileLimits) GetNewStreamsBurst() int32 {
	if x != nil {
		return x.NewStreamsBurst
	}
	return 0
}

func (x *ProfileLimits) GetMaxStreamsPerSession() int32 {
	if x != nil {
		return x.MaxStreamsPerSession
	}
	return 0
}

func (x *ProfileLimits) GetMaxPendingPerSession() int32 {
	if x != nil {
		return x.MaxPendingPerSession
	}
	return 0
}

type Profile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Secret           string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Backend          string                 `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	CarrierMode      string                 `protobuf:"bytes,4,opt,name=carrier_mode,json=carrierMode,proto3" json:"carrier_mode,omitempty"`
	Limits           *ProfileLimits         `protobuf:"bytes,5,opt,name=limits,proto3" json:"limits,omitempty"`
	DataQuotaBytes   uint64                 `protobuf:"varint,10,opt,name=data_quota_bytes,json=dataQuotaBytes,proto3" json:"data_quota_bytes,omitempty"`
	RateLimitUpBps   uint64                 `protobuf:"varint,11,opt,name=rate_limit_up_bps,json=rateLimitUpBps,proto3" json:"rate_limit_up_bps,omitempty"`
	RateLimitDownBps uint64                 `protobuf:"varint,12,opt,name=rate_limit_down_bps,json=rateLimitDownBps,proto3" json:"rate_limit_down_bps,omitempty"`
	MaxUniqueIps     uint32                 `protobuf:"varint,13,opt,name=max_unique_ips,json=maxUniqueIps,proto3" json:"max_unique_ips,omitempty"`
	MaxTcpConns      uint32                 `protobuf:"varint,14,opt,name=max_tcp_conns,json=maxTcpConns,proto3" json:"max_tcp_conns,omitempty"`
	ExpiresAtUnix    int64                  `protobuf:"varint,15,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	Enabled          bool                   `protobuf:"varint,16,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *Profile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Profile) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *Profile) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *Profile) GetCarrierMode() string {
	if x != nil {
		return x.CarrierMode
	}
	return ""
}

func (x *Profile) GetLimits() *ProfileLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *Profile) GetDataQuotaBytes() uint64 {
	if x != nil {
		return x.DataQuotaBytes
	}
	return 0
}

func (x *Profile) GetRateLimitUpBps() uint64 {
	if x != nil {
		return x.RateLimitUpBps
	}
	return 0
}

func (x *Profile) GetRateLimitDownBps() uint64 {
	if x != nil {
		return x.RateLimitDownBps
	}
	return 0
}

func (x *Profile) GetMaxUniqueIps() uint32 {
	if x != nil {
		return x.MaxUniqueIps
	}
	return 0
}

func (x *Profile) GetMaxTcpConns() uint32 {
	if x != nil {
		return x.MaxTcpConns
	}
	return 0
}

func (x *Profile) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *Profile) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type ProfilesFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profiles      []*Profile             `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProfilesFile) Reset() {
	*x = ProfilesFile{}
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilesFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilesFile) ProtoMessage() {}

func (x *ProfilesFile) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfilesFile.ProtoReflect.Descriptor instead.
func (*ProfilesFile) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ProfilesFile) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

// WebTimeouts mirrors telemt's [web.timeouts]. Every value is required: the message only
// travels inside a WebPolicy, and a WebPolicy present at all means the panel has an opinion
// on every one of these.
type WebTimeouts struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	NegotiationDeadlinesSecs []int32                `protobuf:"varint,1,rep,packed,name=negotiation_deadlines_secs,json=negotiationDeadlinesSecs,proto3" json:"negotiation_deadlines_secs,omitempty"`
	CarrierHealthSecs        int32                  `protobuf:"varint,2,opt,name=carrier_health_secs,json=carrierHealthSecs,proto3" json:"carrier_health_secs,omitempty"`
	CarrierLearningSecs      int32                  `protobuf:"varint,3,opt,name=carrier_learning_secs,json=carrierLearningSecs,proto3" json:"carrier_learning_secs,omitempty"`
	BridgeRequestSecs        int32                  `protobuf:"varint,4,opt,name=bridge_request_secs,json=bridgeRequestSecs,proto3" json:"bridge_request_secs,omitempty"`
	BridgeRetrySecs          int32                  `protobuf:"varint,5,opt,name=bridge_retry_secs,json=bridgeRetrySecs,proto3" json:"bridge_retry_secs,omitempty"`
	ProbeCoalesceMs          int32                  `protobuf:"varint,6,opt,name=probe_coalesce_ms,json=probeCoalesceMs,proto3" json:"probe_coalesce_ms,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *WebTimeouts) Reset() {
	*x = WebTimeouts{}
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebTimeouts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebTimeouts) ProtoMessage() {}

func (x *WebTimeouts) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebTimeouts.ProtoReflect.Descriptor instead.
func (*WebTimeouts) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *WebTimeouts) GetNegotiationDeadlinesSecs() []int32 {
	if x != nil {
		return x.NegotiationDeadlinesSecs
	}
	return nil
}

func (x *WebTimeouts) GetCarrierHealthSecs() int32 {
	if x != nil {
		return x.CarrierHealthSecs
	}
	return 0
}

func (x *WebTimeouts) GetCarrierLearningSecs() int32 {
	if x != nil {
		return x.CarrierLearningSecs
	}
	return 0
}

func (x *WebTimeouts) GetBridgeRequestSecs() int32 {
	if x != nil {
		return x.BridgeRequestSecs
	}
	return 0
}

func (x *WebTimeouts) GetBridgeRetrySecs() int32 {
	if x != nil {
		return x.BridgeRetrySecs
	}
	return 0
}

func (x *WebTimeouts) GetProbeCoalesceMs() int32 {
	if x != nil {
		return x.ProbeCoalesceMs
	}
	return 0
}

// WebPolicy is telemt's carrier negotiation and learning policy as the panel owns it.
type WebPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Carrier         string                 `protobuf:"bytes,1,opt,name=carrier,proto3" json:"carrier,omitempty"`
	Carriers        []string               `protobuf:"bytes,2,rep,name=carriers,proto3" json:"carriers,omitempty"`
	CarrierLearning bool                   `protobuf:"varint,3,opt,name=carrier_learning,json=carrierLearning,proto3" json:"carrier_learning,omitempty"`
	Aggressiveness  string                 `protobuf:"bytes,4,opt,name=aggressiveness,proto3" json:"aggressiveness,omitempty"`
	Timeouts        *WebTimeouts           `protobuf:"bytes,5,opt,name=timeouts,proto3" json:"timeouts,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WebPolicy) Reset() {
	*x = WebPolicy{}
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebPolicy) ProtoMessage() {}

func (x *WebPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebPolicy.ProtoReflect.Descriptor instead.
func (*WebPolicy) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *WebPolicy) GetCarrier() string {
	if x != nil {
		return x.Carrier
	}
	return ""
}

func (x *WebPolicy) GetCarriers() []string {
	if x != nil {
		return x.Carriers
	}
	return nil
}

func (x *WebPolicy) GetCarrierLearning() bool {
	if x != nil {
		return x.CarrierLearning
	}
	return false
}

func (x *WebPolicy) GetAggressiveness() string {
	if x != nil {
		return x.Aggressiveness
	}
	return ""
}

func (x *WebPolicy) GetTimeouts() *WebTimeouts {
	if x != nil {
		return x.Timeouts
	}
	return nil
}

type SiteFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteFile) Reset() {
	*x = SiteFile{}
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteFile) ProtoMessage() {}

func (x *SiteFile) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteFile.ProtoReflect.Descriptor instead.
func (*SiteFile) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *SiteFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SiteFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type SiteBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*SiteFile            `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SiteBundle) Reset() {
	*x = SiteBundle{}
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SiteBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SiteBundle) ProtoMessage() {}

func (x *SiteBundle) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SiteBundle.ProtoReflect.Descriptor instead.
func (*SiteBundle) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *SiteBundle) GetFiles() []*SiteFile {
	if x != nil {
		return x.Files
	}
	return nil
}

type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Request_Health
	//	*Request_GetProfiles
	//	*Request_Apply
	//	*Request_GetSite
	//	*Request_Metrics
	//	*Request_Stats
	//	*Request_TailLogs
	//	*Request_RestartRelay
	Body          isRequest_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_agent_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *Request) GetBody() isRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Request) GetHealth() *HealthRequest {
	if x != nil {
		if x, ok := x.Body.(*Request_Health); ok {
			return x.Health
		}
	}
	return nil
}

func (x *Request) GetGetProfiles() *GetProfilesRequest {
	if x != nil {
		if x, ok := x.Body.(*Request_GetProfiles); ok {
			return x.GetProfiles
		}
	}
	return nil
}

func (x *Request) GetApply() *ApplyRequest {
	if x != nil {
		if x, ok := x.Body.(*Request_Apply); ok {
			return x.Apply
		}
	}
	return nil
}

func (x *Request) GetGetSite() *GetSiteRequest {
	if x != nil {
		if x, ok := x.Body.(*Request_GetSite); ok {
			return x.GetSite
		}
	}
	return nil
}

func (x *Request) GetMetrics() *MetricsRequest {
	if x != nil {
		if x, ok := x.Body.(*Request_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *Request) GetStats() *StatsRequest {
	if x != nil {
		if x, ok := x.Body.(*Request_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

func (x *Request) GetTailLogs() *TailLogsRequest {
	if x != nil {
		if x, ok := x.Body.(*Request_TailLogs); ok {
			return x.TailLogs
		}
	}
	return nil
}

func (x *Request) GetRestartRelay() *RestartRelayRequest {
	if x != nil {
		if x, ok := x.Body.(*Request_RestartRelay); ok {
			return x.RestartRelay
		}
	}
	return nil
}

type isRequest_Body interface {
	isRequest_Body()
}

type Request_Health struct {
	Health *HealthRequest `protobuf:"bytes,1,opt,name=health,proto3,oneof"`
}

type Request_GetProfiles struct {
	GetProfiles *GetProfilesRequest `protobuf:"bytes,2,opt,name=get_profiles,json=getProfiles,proto3,oneof"`
}

type Request_Apply struct {
	Apply *ApplyRequest `protobuf:"bytes,3,opt,name=apply,proto3,oneof"`
}

type Request_GetSite struct {
	GetSite *GetSiteRequest `protobuf:"bytes,4,opt,name=get_site,json=getSite,proto3,oneof"`
}

type Request_Metrics struct {
	Metrics *MetricsRequest `protobuf:"bytes,5,opt,name=metrics,proto3,oneof"`
}

type Request_Stats struct {
	Stats *StatsRequest `protobuf:"bytes,6,opt,name=stats,proto3,oneof"`
}

type Request_TailLogs struct {
	TailLogs *TailLogsRequest `protobuf:"bytes,7,opt,name=tail_logs,json=tailLogs,proto3,oneof"`
}

type Request_RestartRelay struct {
	RestartRelay *RestartRelayRequest `protobuf:"bytes,8,opt,name=restart_relay,json=restartRelay,proto3,oneof"`
}

func (*Request_Health) isRequest_Body() {}

func (*Request_GetProfiles) isRequest_Body() {}

func (*Request_Apply) isRequest_Body() {}

func (*Request_GetSite) isRequest_Body() {}

func (*Request_Metrics) isRequest_Body() {}

func (*Request_Stats) isRequest_Body() {}

func (*Request_TailLogs) isRequest_Body() {}

func (*Request_RestartRelay) isRequest_Body() {}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{21}
}

type GetProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfilesRequest) Reset() {
	*x = GetProfilesRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilesRequest) ProtoMessage() {}

func (x *GetProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilesRequest.ProtoReflect.Descriptor instead.
func (*GetProfilesRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{22}
}

type ApplyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ApplyProfiles  bool                   `protobuf:"varint,1,opt,name=apply_profiles,json=applyProfiles,proto3" json:"apply_profiles,omitempty"`
	Profiles       []*Profile             `protobuf:"bytes,2,rep,name=profiles,proto3" json:"profiles,omitempty"`
	MtproxySecrets []string               `protobuf:"bytes,3,rep,name=mtproxy_secrets,json=mtproxySecrets,proto3" json:"mtproxy_secrets,omitempty"`
	Site           *SiteBundle            `protobuf:"bytes,4,opt,name=site,proto3" json:"site,omitempty"` // nil = leave site untouched
	TlsDomain      string                 `protobuf:"bytes,5,opt,name=tls_domain,json=tlsDomain,proto3" json:"tls_domain,omitempty"`
	ClassicPort    uint32                 `protobuf:"varint,6,opt,name=classic_port,json=classicPort,proto3" json:"classic_port,omitempty"`
	PublicIp       string                 `protobuf:"bytes,7,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`
	AdTag          string                 `protobuf:"bytes,8,opt,name=ad_tag,json=adTag,proto3" json:"ad_tag,omitempty"`
	WebPolicy      *WebPolicy             `protobuf:"bytes,9,opt,name=web_policy,json=webPolicy,proto3" json:"web_policy,omitempty"` // nil = leave the node's WEB policy untouched
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{23}
}

func (x *ApplyRequest) GetApplyProfiles() bool {
	if x != nil {
		return x.ApplyProfiles
	}
	return false
}

func (x *ApplyRequest) GetProfiles() []*Profile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *ApplyRequest) GetMtproxySecrets() []string {
	if x != nil {
		return x.MtproxySecrets
	}
	return nil
}

func (x *ApplyRequest) GetSite() *SiteBundle {
	if x != nil {
		return x.Site
	}
	return nil
}

func (x *ApplyRequest) GetTlsDomain() string {
	if x != nil {
		return x.TlsDomain
	}
	return ""
}

func (x *ApplyRequest) GetClassicPort() uint32 {
	if x != nil {
		return x.ClassicPort
	}
	return 0
}

func (x *ApplyRequest) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *ApplyRequest) GetAdTag() string {
	if x != nil {
		return x.AdTag
	}
	return ""
}

func (x *ApplyRequest) GetWebPolicy() *WebPolicy {
	if x != nil {
		return x.WebPolicy
	}
	return nil
}

type GetSiteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSiteRequest) Reset() {
	*x = GetSiteRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSiteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSiteRequest) ProtoMessage() {}

func (x *GetSiteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSiteRequest.ProtoReflect.Descriptor instead.
func (*GetSiteRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{24}
}

type MetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{25}
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{26}
}

type TailLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []string               `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	Lines         int32                  `protobuf:"varint,2,opt,name=lines,proto3" json:"lines,omitempty"`
	Follow        bool                   `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TailLogsRequest) Reset() {
	*x = TailLogsRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TailLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TailLogsRequest) ProtoMessage() {}

func (x *TailLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TailLogsRequest.ProtoReflect.Descriptor instead.
func (*TailLogsRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{27}
}

func (x *TailLogsRequest) GetServices() []string {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *TailLogsRequest) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

func (x *TailLogsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

type RestartRelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartRelayRequest) Reset() {
	*x = RestartRelayRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartRelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartRelayRequest) ProtoMessage() {}

func (x *RestartRelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartRelayRequest.ProtoReflect.Descriptor instead.
func (*RestartRelayRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{28}
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Error string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	// Types that are valid to be assigned to Body:
	//
	//	*Response_Health
	//	*Response_Profiles
	//	*Response_Apply
	//	*Response_Site
	//	*Response_Metrics
	//	*Response_Stats
	//	*Response_Empty
	Body          isResponse_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_agent_v1_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{29}
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Response) GetBody() isResponse_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Response) GetHealth() *HealthReport {
	if x != nil {
		if x, ok := x.Body.(*Response_Health); ok {
			return x.Health
		}
	}
	return nil
}

func (x *Response) GetProfiles() *ProfilesFile {
	if x != nil {
		if x, ok := x.Body.(*Response_Profiles); ok {
			return x.Profiles
		}
	}
	return nil
}

func (x *Response) GetApply() *ApplyResult {
	if x != nil {
		if x, ok := x.Body.(*Response_Apply); ok {
			return x.Apply
		}
	}
	return nil
}

func (x *Response) GetSite() *SiteBundle {
	if x != nil {
		if x, ok := x.Body.(*Response_Site); ok {
			return x.Site
		}
	}
	return nil
}

func (x *Response) GetMetrics() *MetricsText {
	if x != nil {
		if x, ok := x.Body.(*Response_Metrics); ok {
			return x.Metrics
		}
	}
	return nil
}

func (x *Response) GetStats() *StatsMap {
	if x != nil {
		if x, ok := x.Body.(*Response_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

func (x *Response) GetEmpty() *Empty {
	if x != nil {
		if x, ok := x.Body.(*Response_Empty); ok {
			return x.Empty
		}
	}
	return nil
}

type isResponse_Body interface {
	isResponse_Body()
}

type Response_Health struct {
	Health *HealthReport `protobuf:"bytes,2,opt,name=health,proto3,oneof"`
}

type Response_Profiles struct {
	Profiles *ProfilesFile `protobuf:"bytes,3,opt,name=profiles,proto3,oneof"`
}

type Response_Apply struct {
	Apply *ApplyResult `protobuf:"bytes,4,opt,name=apply,proto3,oneof"`
}

type Response_Site struct {
	Site *SiteBundle `protobuf:"bytes,5,opt,name=site,proto3,oneof"`
}

type Response_Metrics struct {
	Metrics *MetricsText `protobuf:"bytes,6,opt,name=metrics,proto3,oneof"`
}

type Response_Stats struct {
	Stats *StatsMap `protobuf:"bytes,7,opt,name=stats,proto3,oneof"`
}

type Response_Empty struct {
	Empty *Empty `protobuf:"bytes,8,opt,name=empty,proto3,oneof"`
}

func (*Response_Health) isResponse_Body() {}

func (*Response_Profiles) isResponse_Body() {}

func (*Response_Apply) isResponse_Body() {}

func (*Response_Site) isResponse_Body() {}

func (*Response_Metrics) isResponse_Body() {}

func (*Response_Stats) isResponse_Body() {}

func (*Response_Empty) isResponse_Body() {}

type ApplyResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ok               bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	RestartedRelay   bool                   `protobuf:"varint,2,opt,name=restarted_relay,json=restartedRelay,proto3" json:"restarted_relay,omitempty"`
	RestartedMtproxy bool                   `protobuf:"varint,3,opt,name=restarted_mtproxy,json=restartedMtproxy,proto3" json:"restarted_mtproxy,omitempty"`
	RolledBack       bool                   `protobuf:"varint,4,opt,name=rolled_back,json=rolledBack,proto3" json:"rolled_back,omitempty"`
	Log              string                 `protobuf:"bytes,5,opt,name=log,proto3" json:"log,omitempty"`
	// deferred_fields are config keys telemt persisted but did not activate; restart_required
	// says telemt wants a process restart before they take effect. Both are reported rather
	// than acted on: a proxy node is not restarted behind the operator's back.
	DeferredFields  []string `protobuf:"bytes,6,rep,name=deferred_fields,json=deferredFields,proto3" json:"deferred_fields,omitempty"`
	RestartRequired bool     `protobuf:"varint,7,opt,name=restart_required,json=restartRequired,proto3" json:"restart_required,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApplyResult) Reset() {
	*x = ApplyResult{}
	mi := &file_agent_v1_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResult) ProtoMessage() {}

func (x *ApplyResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResult.ProtoReflect.Descriptor instead.
func (*ApplyResult) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{30}
}

func (x *ApplyResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ApplyResult) GetRestartedRelay() bool {
	if x != nil {
		return x.RestartedRelay
	}
	return false
}

func (x *ApplyResult) GetRestartedMtproxy() bool {
	if x != nil {
		return x.RestartedMtproxy
	}
	return false
}

func (x *ApplyResult) GetRolledBack() bool {
	if x != nil {
		return x.RolledBack
	}
	return false
}

func (x *ApplyResult) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *ApplyResult) GetDeferredFields() []string {
	if x != nil {
		return x.DeferredFields
	}
	return nil
}

func (x *ApplyResult) GetRestartRequired() bool {
	if x != nil {
		return x.RestartRequired
	}
	return false
}

type MetricsText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsText) Reset() {
	*x = MetricsText{}
	mi := &file_agent_v1_agent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsText) ProtoMessage() {}

func (x *MetricsText) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsText.ProtoReflect.Descriptor instead.
func (*MetricsText) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{31}
}

func (x *MetricsText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type StatsMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsMap) Reset() {
	*x = StatsMap{}
	mi := &file_agent_v1_agent_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsMap) ProtoMessage() {}

func (x *StatsMap) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsMap.ProtoReflect.Descriptor instead.
func (*StatsMap) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{32}
}

func (x *StatsMap) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_agent_v1_agent_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{33}
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Line          string                 `protobuf:"bytes,2,opt,name=line,proto3" json:"line,omitempty"`
	UnixMs        int64                  `protobuf:"varint,3,opt,name=unix_ms,json=unixMs,proto3" json:"unix_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_agent_v1_agent_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{34}
}

func (x *LogLine) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogLine) GetLine() string {
	if x != nil {
		return x.Line
	}
	return ""
}

func (x *LogLine) GetUnixMs() int64 {
	if x != nil {
		return x.UnixMs
	}
	return 0
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lines         []*LogLine             `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_agent_v1_agent_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{35}
}

func (x *LogChunk) GetLines() []*LogLine {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *LogChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *LogChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\bagent.v1\"\xa3\x02\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x05hello\x18\x02 \x01(\v2\x0f.agent.v1.HelloH\x00R\x05hello\x123\n" +
	"\theartbeat\x18\x03 \x01(\v2\x13.agent.v1.HeartbeatH\x00R\theartbeat\x12-\n" +
	"\arequest\x18\x04 \x01(\v2\x11.agent.v1.RequestH\x00R\arequest\x120\n" +
	"\bresponse\x18\x05 \x01(\v2\x12.agent.v1.ResponseH\x00R\bresponse\x121\n" +
	"\tlog_chunk\x18\x06 \x01(\v2\x12.agent.v1.LogChunkH\x00R\blogChunkB\x06\n" +
	"\x04body\"o\n" +
	"\x05Hello\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12%\n" +
	"\x0etproxy_version\x18\x02 \x01(\tR\rtproxyVersion\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\";\n" +
	"\tHeartbeat\x12.\n" +
	"\x06health\x18\x01 \x01(\v2\x16.agent.v1.HealthReportR\x06health\"\xa1\a\n" +
	"\fHealthReport\x12!\n" +
	"\frelay_active\x18\x01 \x01(\bR\vrelayActive\x12%\n" +
	"\x0emtproxy_active\x18\x02 \x01(\bR\rmtproxyActive\x12!\n" +
	"\fcaddy_active\x18\x03 \x01(\bR\vcaddyActive\x12\x18\n" +
	"\ahealthz\x18\x04 \x01(\bR\ahealthz\x12\x16\n" +
	"\x06readyz\x18\x05 \x01(\bR\x06readyz\x12%\n" +
	"\x0etproxy_version\x18\x06 \x01(\tR\rtproxyVersion\x12#\n" +
	"\ragent_version\x18\a \x01(\tR\fagentVersion\x12%\n" +
	"\x0euptime_seconds\x18\b \x01(\x03R\ruptimeSeconds\x12\x1f\n" +
	"\vcpu_percent\x18\t \x01(\x01R\n" +
	"cpuPercent\x12(\n" +
	"\x10mem_used_percent\x18\n" +
	" \x01(\x01R\x0ememUsedPercent\x12*\n" +
	"\x11disk_used_percent\x18\v \x01(\x01R\x0fdiskUsedPercent\x12#\n" +
	"\rprofile_count\x18\f \x01(\x05R\fprofileCount\x12%\n" +
	"\x03dcs\x18\r \x03(\v2\x13.agent.v1.DcLatencyR\x03dcs\x12)\n" +
	"\x10upstream_healthy\x18\x0e \x01(\bR\x0fupstreamHealthy\x12%\n" +
	"\x0eupstream_fails\x18\x0f \x01(\x05R\rupstreamFails\x120\n" +
	"\x14effective_latency_ms\x18\x10 \x01(\x01R\x12effectiveLatencyMs\x122\n" +
	"\x15connect_success_total\x18\x11 \x01(\x03R\x13connectSuccessTotal\x12,\n" +
	"\x12connect_fail_total\x18\x12 \x01(\x03R\x10connectFailTotal\x12>\n" +
	"\x1cupstream_last_check_age_secs\x18\x13 \x01(\x03R\x18upstreamLastCheckAgeSecs\x12*\n" +
	"\x11dc_data_available\x18\x14 \x01(\bR\x0fdcDataAvailable\x12(\n" +
	"\x03web\x18\x15 \x01(\v2\x16.agent.v1.WebTelemetryR\x03web\x12@\n" +
	"\fcapabilities\x18\x16 \x01(\v2\x1c.agent.v1.TelemtCapabilitiesR\fcapabilities\"n\n" +
	"\x10WebCounterSample\x12\x18\n" +
	"\acarrier\x18\x01 \x01(\tR\acarrier\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\"H\n" +
	"\x10WebCounterFamily\x124\n" +
	"\asamples\x18\x01 \x03(\v2\x1a.agent.v1.WebCounterSampleR\asamples\"\x82\x02\n" +
	"\x10WebLearningState\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12+\n" +
	"\x11policy_generation\x18\x02 \x01(\x04R\x10policyGeneration\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\x12\x18\n" +
	"\aentries\x18\x04 \x01(\x05R\aentries\x12\x1a\n" +
	"\bcapacity\x18\x05 \x01(\x05R\bcapacity\x12#\n" +
	"\rlifetime_secs\x18\x06 \x01(\x03R\flifetimeSecs\x12\x1f\n" +
	"\vhealth_secs\x18\a \x01(\x03R\n" +
	"healthSecs\x12\x15\n" +
	"\x06age_ms\x18\b \x01(\x03R\x05ageMs\"\xae\x03\n" +
	"\rWebDrainState\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\tR\aoutcome\x12!\n" +
	"\ftimeout_secs\x18\x04 \x01(\x05R\vtimeoutSecs\x120\n" +
	"\x14started_epoch_millis\x18\x05 \x01(\x03R\x12startedEpochMillis\x122\n" +
	"\x15deadline_epoch_millis\x18\x06 \x01(\x03R\x13deadlineEpochMillis\x12-\n" +
	"\x12remaining_sessions\x18\a \x01(\x04R\x11remainingSessions\x12+\n" +
	"\x11remaining_streams\x18\b \x01(\x04R\x10remainingStreams\x121\n" +
	"\x14remaining_websockets\x18\t \x01(\x04R\x13remainingWebsockets\x122\n" +
	"\x15force_close_signalled\x18\n" +
	" \x01(\bR\x13forceCloseSignalled\"\xed\x01\n" +
	"\x11WebLifecycleState\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x15\n" +
	"\x06age_ms\x18\x03 \x01(\x03R\x05ageMs\x12%\n" +
	"\x0eadmission_open\x18\x04 \x01(\bR\radmissionOpen\x12?\n" +
	"\x1ceffective_new_work_admission\x18\x05 \x01(\bR\x19effectiveNewWorkAdmission\x12-\n" +
	"\x05drain\x18\x06 \x01(\v2\x17.agent.v1.WebDrainStateR\x05drain\"\xe0\x01\n" +
	"\x0fWebRuntimeState\x12)\n" +
	"\x10runtime_instance\x18\x01 \x01(\tR\x0fruntimeInstance\x12/\n" +
	"\x13carrier_negotiation\x18\x02 \x01(\bR\x12carrierNegotiation\x126\n" +
	"\blearning\x18\x03 \x01(\v2\x1a.agent.v1.WebLearningStateR\blearning\x129\n" +
	"\tlifecycle\x18\x04 \x01(\v2\x1b.agent.v1.WebLifecycleStateR\tlifecycle\"\xad\x04\n" +
	"\fWebTelemetry\x12I\n" +
	"\x12carrier_selections\x18\x01 \x01(\v2\x1a.agent.v1.WebCounterFamilyR\x11carrierSelections\x12E\n" +
	"\x10carrier_failures\x18\x02 \x01(\v2\x1a.agent.v1.WebCounterFamilyR\x0fcarrierFailures\x12G\n" +
	"\x11learning_outcomes\x18\x03 \x01(\v2\x1a.agent.v1.WebCounterFamilyR\x10learningOutcomes\x12E\n" +
	"\x10learning_entries\x18\x04 \x01(\v2\x1a.agent.v1.WebCounterFamilyR\x0flearningEntries\x12:\n" +
	"\n" +
	"rejections\x18\x05 \x01(\v2\x1a.agent.v1.WebCounterFamilyR\n" +
	"rejections\x12E\n" +
	"\x10session_closures\x18\x06 \x01(\v2\x1a.agent.v1.WebCounterFamilyR\x0fsessionClosures\x12C\n" +
	"\x0fbridge_recovery\x18\a \x01(\v2\x1a.agent.v1.WebCounterFamilyR\x0ebridgeRecovery\x123\n" +
	"\aruntime\x18\b \x01(\v2\x19.agent.v1.WebRuntimeStateR\aruntime\"\xd7\x01\n" +
	"\x12TelemtCapabilities\x12I\n" +
	"\tsupported\x18\x01 \x03(\v2+.agent.v1.TelemtCapabilities.SupportedEntryR\tsupported\x12\"\n" +
	"\fundetermined\x18\x02 \x03(\tR\fundetermined\x12\x14\n" +
	"\x05build\x18\x03 \x01(\tR\x05build\x1a<\n" +
	"\x0eSupportedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"u\n" +
	"\tDcLatency\x12\x0e\n" +
	"\x02dc\x18\x01 \x01(\x05R\x02dc\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x02 \x01(\x01R\tlatencyMs\x12\x14\n" +
	"\x05known\x18\x03 \x01(\bR\x05known\x12#\n" +
	"\rip_preference\x18\x04 \x01(\tR\fipPreference\"\xc5\x03\n" +
	"\rProfileLimits\x12!\n" +
	"\fmax_sessions\x18\x01 \x01(\x05R\vmaxSessions\x12\x1f\n" +
	"\vmax_streams\x18\x02 \x01(\x05R\n" +
	"maxStreams\x12<\n" +
	"\x1bmax_backend_dials_in_flight\x18\x03 \x01(\x05R\x17maxBackendDialsInFlight\x125\n" +
	"\x17new_sessions_per_minute\x18\x04 \x01(\x05R\x14newSessionsPerMinute\x12,\n" +
	"\x12new_sessions_burst\x18\x05 \x01(\x05R\x10newSessionsBurst\x123\n" +
	"\x16new_streams_per_minute\x18\x06 \x01(\x05R\x13newStreamsPerMinute\x12*\n" +
	"\x11new_streams_burst\x18\a \x01(\x05R\x0fnewStreamsBurst\x125\n" +
	"\x17max_streams_per_session\x18\b \x01(\x05R\x14maxStreamsPerSession\x125\n" +
	"\x17max_pending_per_session\x18\t \x01(\x05R\x14maxPendingPerSession\"\xb3\x03\n" +
	"\aProfile\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x18\n" +
	"\abackend\x18\x03 \x01(\tR\abackend\x12!\n" +
	"\fcarrier_mode\x18\x04 \x01(\tR\vcarrierMode\x12/\n" +
	"\x06limits\x18\x05 \x01(\v2\x17.agent.v1.ProfileLimitsR\x06limits\x12(\n" +
	"\x10data_quota_bytes\x18\n" +
	" \x01(\x04R\x0edataQuotaBytes\x12)\n" +
	"\x11rate_limit_up_bps\x18\v \x01(\x04R\x0erateLimitUpBps\x12-\n" +
	"\x13rate_limit_down_bps\x18\f \x01(\x04R\x10rateLimitDownBps\x12$\n" +
	"\x0emax_unique_ips\x18\r \x01(\rR\fmaxUniqueIps\x12\"\n" +
	"\rmax_tcp_conns\x18\x0e \x01(\rR\vmaxTcpConns\x12&\n" +
	"\x0fexpires_at_unix\x18\x0f \x01(\x03R\rexpiresAtUnix\x12\x18\n" +
	"\aenabled\x18\x10 \x01(\bR\aenabled\"=\n" +
	"\fProfilesFile\x12-\n" +
	"\bprofiles\x18\x01 \x03(\v2\x11.agent.v1.ProfileR\bprofiles\"\xb7\x02\n" +
	"\vWebTimeouts\x12<\n" +
	"\x1anegotiation_deadlines_secs\x18\x01 \x03(\x05R\x18negotiationDeadlinesSecs\x12.\n" +
	"\x13carrier_health_secs\x18\x02 \x01(\x05R\x11carrierHealthSecs\x122\n" +
	"\x15carrier_learning_secs\x18\x03 \x01(\x05R\x13carrierLearningSecs\x12.\n" +
	"\x13bridge_request_secs\x18\x04 \x01(\x05R\x11bridgeRequestSecs\x12*\n" +
	"\x11bridge_retry_secs\x18\x05 \x01(\x05R\x0fbridgeRetrySecs\x12*\n" +
	"\x11probe_coalesce_ms\x18\x06 \x01(\x05R\x0fprobeCoalesceMs\"\xc7\x01\n" +
	"\tWebPolicy\x12\x18\n" +
	"\acarrier\x18\x01 \x01(\tR\acarrier\x12\x1a\n" +
	"\bcarriers\x18\x02 \x03(\tR\bcarriers\x12)\n" +
	"\x10carrier_learning\x18\x03 \x01(\bR\x0fcarrierLearning\x12&\n" +
	"\x0eaggressiveness\x18\x04 \x01(\tR\x0eaggressiveness\x121\n" +
	"\btimeouts\x18\x05 \x01(\v2\x15.agent.v1.WebTimeoutsR\btimeouts\"8\n" +
	"\bSiteFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"6\n" +
	"\n" +
	"SiteBundle\x12(\n" +
	"\x05files\x18\x01 \x03(\v2\x12.agent.v1.SiteFileR\x05files\"\xd4\x03\n" +
	"\aRequest\x121\n" +
	"\x06health\x18\x01 \x01(\v2\x17.agent.v1.HealthRequestH\x00R\x06health\x12A\n" +
	"\fget_profiles\x18\x02 \x01(\v2\x1c.agent.v1.GetProfilesRequestH\x00R\vgetProfiles\x12.\n" +
	"\x05apply\x18\x03 \x01(\v2\x16.agent.v1.ApplyRequestH\x00R\x05apply\x125\n" +
	"\bget_site\x18\x04 \x01(\v2\x18.agent.v1.GetSiteRequestH\x00R\agetSite\x124\n" +
	"\ametrics\x18\x05 \x01(\v2\x18.agent.v1.MetricsRequestH\x00R\ametrics\x12.\n" +
	"\x05stats\x18\x06 \x01(\v2\x16.agent.v1.StatsRequestH\x00R\x05stats\x128\n" +
	"\ttail_logs\x18\a \x01(\v2\x19.agent.v1.TailLogsRequestH\x00R\btailLogs\x12D\n" +
	"\rrestart_relay\x18\b \x01(\v2\x1d.agent.v1.RestartRelayRequestH\x00R\frestartRelayB\x06\n" +
	"\x04body\"\x0f\n" +
	"\rHealthRequest\"\x14\n" +
	"\x12GetProfilesRequest\"\xe1\x02\n" +
	"\fApplyRequest\x12%\n" +
	"\x0eapply_profiles\x18\x01 \x01(\bR\rapplyProfiles\x12-\n" +
	"\bprofiles\x18\x02 \x03(\v2\x11.agent.v1.ProfileR\bprofiles\x12'\n" +
	"\x0fmtproxy_secrets\x18\x03 \x03(\tR\x0emtproxySecrets\x12(\n" +
	"\x04site\x18\x04 \x01(\v2\x14.agent.v1.SiteBundleR\x04site\x12\x1d\n" +
	"\n" +
	"tls_domain\x18\x05 \x01(\tR\ttlsDomain\x12!\n" +
	"\fclassic_port\x18\x06 \x01(\rR\vclassicPort\x12\x1b\n" +
	"\tpublic_ip\x18\a \x01(\tR\bpublicIp\x12\x15\n" +
	"\x06ad_tag\x18\b \x01(\tR\x05adTag\x122\n" +
	"\n" +
	"web_policy\x18\t \x01(\v2\x13.agent.v1.WebPolicyR\twebPolicy\"\x10\n" +
	"\x0eGetSiteRequest\"\x10\n" +
	"\x0eMetricsRequest\"\x0e\n" +
	"\fStatsRequest\"[\n" +
	"\x0fTailLogsRequest\x12\x1a\n" +
	"\bservices\x18\x01 \x03(\tR\bservices\x12\x14\n" +
	"\x05lines\x18\x02 \x01(\x05R\x05lines\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\"\x15\n" +
	"\x13RestartRelayRequest\"\xf3\x02\n" +
	"\bResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x120\n" +
	"\x06health\x18\x02 \x01(\v2\x16.agent.v1.HealthReportH\x00R\x06health\x124\n" +
	"\bprofiles\x18\x03 \x01(\v2\x16.agent.v1.ProfilesFileH\x00R\bprofiles\x12-\n" +
	"\x05apply\x18\x04 \x01(\v2\x15.agent.v1.ApplyResultH\x00R\x05apply\x12*\n" +
	"\x04site\x18\x05 \x01(\v2\x14.agent.v1.SiteBundleH\x00R\x04site\x121\n" +
	"\ametrics\x18\x06 \x01(\v2\x15.agent.v1.MetricsTextH\x00R\ametrics\x12*\n" +
	"\x05stats\x18\a \x01(\v2\x12.agent.v1.StatsMapH\x00R\x05stats\x12'\n" +
	"\x05empty\x18\b \x01(\v2\x0f.agent.v1.EmptyH\x00R\x05emptyB\x06\n" +
	"\x04body\"\xfa\x01\n" +
	"\vApplyResult\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12'\n" +
	"\x0frestarted_relay\x18\x02 \x01(\bR\x0erestartedRelay\x12+\n" +
	"\x11restarted_mtproxy\x18\x03 \x01(\bR\x10restartedMtproxy\x12\x1f\n" +
	"\vrolled_back\x18\x04 \x01(\bR\n" +
	"rolledBack\x12\x10\n" +
	"\x03log\x18\x05 \x01(\tR\x03log\x12'\n" +
	"\x0fdeferred_fields\x18\x06 \x03(\tR\x0edeferredFields\x12)\n" +
	"\x10restart_required\x18\a \x01(\bR\x0frestartRequired\"!\n" +
	"\vMetricsText\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"}\n" +
	"\bStatsMap\x126\n" +
	"\x06values\x18\x01 \x03(\v2\x1e.agent.v1.StatsMap.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\a\n" +
	"\x05Empty\"P\n" +
	"\aLogLine\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x12\n" +
	"\x04line\x18\x02 \x01(\tR\x04line\x12\x17\n" +
	"\aunix_ms\x18\x03 \x01(\x03R\x06unixMs\"]\n" +
	"\bLogChunk\x12'\n" +
	"\x05lines\x18\x01 \x03(\v2\x11.agent.v1.LogLineR\x05lines\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2E\n" +
	"\fAgentGateway\x125\n" +
	"\aSession\x12\x12.agent.v1.Envelope\x1a\x12.agent.v1.Envelope(\x010\x01B#Z!tgwebproxy/proto/agent/v1;agentv1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_agent_v1_agent_proto_goTypes = []any{
	(*Envelope)(nil),            // 0: agent.v1.Envelope
	(*Hello)(nil),               // 1: agent.v1.Hello
	(*Heartbeat)(nil),           // 2: agent.v1.Heartbeat
	(*HealthReport)(nil),        // 3: agent.v1.HealthReport
	(*WebCounterSample)(nil),    // 4: agent.v1.WebCounterSample
	(*WebCounterFamily)(nil),    // 5: agent.v1.WebCounterFamily
	(*WebLearningState)(nil),    // 6: agent.v1.WebLearningState
	(*WebDrainState)(nil),       // 7: agent.v1.WebDrainState
	(*WebLifecycleState)(nil),   // 8: agent.v1.WebLifecycleState
	(*WebRuntimeState)(nil),     // 9: agent.v1.WebRuntimeState
	(*WebTelemetry)(nil),        // 10: agent.v1.WebTelemetry
	(*TelemtCapabilities)(nil),  // 11: agent.v1.TelemtCapabilities
	(*DcLatency)(nil),           // 12: agent.v1.DcLatency
	(*ProfileLimits)(nil),       // 13: agent.v1.ProfileLimits
	(*Profile)(nil),             // 14: agent.v1.Profile
	(*ProfilesFile)(nil),        // 15: agent.v1.ProfilesFile
	(*WebTimeouts)(nil),         // 16: agent.v1.WebTimeouts
	(*WebPolicy)(nil),           // 17: agent.v1.WebPolicy
	(*SiteFile)(nil),            // 18: agent.v1.SiteFile
	(*SiteBundle)(nil),          // 19: agent.v1.SiteBundle
	(*Request)(nil),             // 20: agent.v1.Request
	(*HealthRequest)(nil),       // 21: agent.v1.HealthRequest
	(*GetProfilesRequest)(nil),  // 22: agent.v1.GetProfilesRequest
	(*ApplyRequest)(nil),        // 23: agent.v1.ApplyRequest
	(*GetSiteRequest)(nil),      // 24: agent.v1.GetSiteRequest
	(*MetricsRequest)(nil),      // 25: agent.v1.MetricsRequest
	(*StatsRequest)(nil),        // 26: agent.v1.StatsRequest
	(*TailLogsRequest)(nil),     // 27: agent.v1.TailLogsRequest
	(*RestartRelayRequest)(nil), // 28: agent.v1.RestartRelayRequest
	(*Response)(nil),            // 29: agent.v1.Response
	(*ApplyResult)(nil),         // 30: agent.v1.ApplyResult
	(*MetricsText)(nil),         // 31: agent.v1.MetricsText
	(*StatsMap)(nil),            // 32: agent.v1.StatsMap
	(*Empty)(nil),               // 33: agent.v1.Empty
	(*LogLine)(nil),             // 34: agent.v1.LogLine
	(*LogChunk)(nil),            // 35: agent.v1.LogChunk
	nil,                         // 36: agent.v1.TelemtCapabilities.SupportedEntry
	nil,                         // 37: agent.v1.StatsMap.ValuesEntry
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	1,  // 0: agent.v1.Envelope.hello:type_name -> agent.v1.Hello
	2,  // 1: agent.v1.Envelope.heartbeat:type_name -> agent.v1.Heartbeat
	20, // 2: agent.v1.Envelope.request:type_name -> agent.v1.Request
	29, // 3: agent.v1.Envelope.response:type_name -> agent.v1.Response
	35, // 4: agent.v1.Envelope.log_chunk:type_name -> agent.v1.LogChunk
	3,  // 5: agent.v1.Heartbeat.health:type_name -> agent.v1.HealthReport
	12, // 6: agent.v1.HealthReport.dcs:type_name -> agent.v1.DcLatency
	10, // 7: agent.v1.HealthReport.web:type_name -> agent.v1.WebTelemetry
	11, // 8: agent.v1.HealthReport.capabilities:type_name -> agent.v1.TelemtCapabilities
	4,  // 9: agent.v1.WebCounterFamily.samples:type_name -> agent.v1.WebCounterSample
	7,  // 10: agent.v1.WebLifecycleState.drain:type_name -> agent.v1.WebDrainState
	6,  // 11: agent.v1.WebRuntimeState.learning:type_name -> agent.v1.WebLearningState
	8,  // 12: agent.v1.WebRuntimeState.lifecycle:type_name -> agent.v1.WebLifecycleState
	5,  // 13: agent.v1.WebTelemetry.carrier_selections:type_name -> agent.v1.WebCounterFamily
	5,  // 14: agent.v1.WebTelemetry.carrier_failures:type_name -> agent.v1.WebCounterFamily
	5,  // 15: agent.v1.WebTelemetry.learning_outcomes:type_name -> agent.v1.WebCounterFamily
	5,  // 16: agent.v1.WebTelemetry.learning_entries:type_name -> agent.v1.WebCounterFamily
	5,  // 17: agent.v1.WebTelemetry.rejections:type_name -> agent.v1.WebCounterFamily
	5,  // 18: agent.v1.WebTelemetry.session_closures:type_name -> agent.v1.WebCounterFamily
	5,  // 19: agent.v1.WebTelemetry.bridge_recovery:type_name -> agent.v1.WebCounterFamily
	9,  // 20: agent.v1.WebTelemetry.runtime:type_name -> agent.v1.WebRuntimeState
	36, // 21: agent.v1.TelemtCapabilities.supported:type_name -> agent.v1.TelemtCapabilities.SupportedEntry
	13, // 22: agent.v1.Profile.limits:type_name -> agent.v1.ProfileLimits
	14, // 23: agent.v1.ProfilesFile.profiles:type_name -> agent.v1.Profile
	16, // 24: agent.v1.WebPolicy.timeouts:type_name -> agent.v1.WebTimeouts
	18, // 25: agent.v1.SiteBundle.files:type_name -> agent.v1.SiteFile
	21, // 26: agent.v1.Request.health:type_name -> agent.v1.HealthRequest
	22, // 27: agent.v1.Request.get_profiles:type_name -> agent.v1.GetProfilesRequest
	23, // 28: agent.v1.Request.apply:type_name -> agent.v1.ApplyRequest
	24, // 29: agent.v1.Request.get_site:type_name -> agent.v1.GetSiteRequest
	25, // 30: agent.v1.Request.metrics:type_name -> agent.v1.MetricsRequest
	26, // 31: agent.v1.Request.stats:type_name -> agent.v1.StatsRequest
	27, // 32: agent.v1.Request.tail_logs:type_name -> agent.v1.TailLogsRequest
	28, // 33: agent.v1.Request.restart_relay:type_name -> agent.v1.RestartRelayRequest
	14, // 34: agent.v1.ApplyRequest.profiles:type_name -> agent.v1.Profile
	19, // 35: agent.v1.ApplyRequest.site:type_name -> agent.v1.SiteBundle
	17, // 36: agent.v1.ApplyRequest.web_policy:type_name -> agent.v1.WebPolicy
	3,  // 37: agent.v1.Response.health:type_name -> agent.v1.HealthReport
	15, // 38: agent.v1.Response.profiles:type_name -> agent.v1.ProfilesFile
	30, // 39: agent.v1.Response.apply:type_name -> agent.v1.ApplyResult
	19, // 40: agent.v1.Response.site:type_name -> agent.v1.SiteBundle
	31, // 41: agent.v1.Response.metrics:type_name -> agent.v1.MetricsText
	32, // 42: agent.v1.Response.stats:type_name -> agent.v1.StatsMap
	33, // 43: agent.v1.Response.empty:type_name -> agent.v1.Empty
	37, // 44: agent.v1.StatsMap.values:type_name -> agent.v1.StatsMap.ValuesEntry
	34, // 45: agent.v1.LogChunk.lines:type_name -> agent.v1.LogLine
	0,  // 46: agent.v1.AgentGateway.Session:input_type -> agent.v1.Envelope
	0,  // 47: agent.v1.AgentGateway.Session:output_type -> agent.v1.Envelope
	47, // [47:48] is the sub-list for method output_type
	46, // [46:47] is the sub-list for method input_type
	46, // [46:46] is the sub-list for extension type_name
	46, // [46:46] is the sub-list for extension extendee
	0,  // [0:46] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Hello)(nil),
		(*Envelope_Heartbeat)(nil),
		(*Envelope_Request)(nil),
		(*Envelope_Response)(nil),
		(*Envelope_LogChunk)(nil),
	}
	file_agent_v1_agent_proto_msgTypes[20].OneofWrappers = []any{
		(*Request_Health)(nil),
		(*Request_GetProfiles)(nil),
		(*Request_Apply)(nil),
		(*Request_GetSite)(nil),
		(*Request_Metrics)(nil),
		(*Request_Stats)(nil),
		(*Request_TailLogs)(nil),
		(*Request_RestartRelay)(nil),
	}
	file_agent_v1_agent_proto_msgTypes[29].OneofWrappers = []any{
		(*Response_Health)(nil),
		(*Response_Profiles)(nil),
		(*Response_Apply)(nil),
		(*Response_Site)(nil),
		(*Response_Metrics)(nil),
		(*Response_Stats)(nil),
		(*Response_Empty)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
