// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admins.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM admin_users
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOwnersForUpdate = `-- name: CountOwnersForUpdate :one
SELECT count(*) FROM (SELECT 1 FROM admin_users WHERE role = 'owner' FOR UPDATE) t
`

// CountOwnersForUpdate locks every owner row for the duration of the transaction, so two
// concurrent "delete an owner" requests serialise instead of both seeing two owners and
// both succeeding.
func (q *Queries) CountOwnersForUpdate(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnersForUpdate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admin_users (username, password_hash, role) VALUES ($1, $2, $3) RETURNING id, username, password_hash, role, totp_secret_enc, totp_enabled, failed_logins, locked_until, created_at, totp_pending_enc
`

type CreateAdminParams struct {
	Username     string    `json:"username"`
	PasswordHash string    `json:"password_hash"`
	Role         AdminRole `json:"role"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.Username, arg.PasswordHash, arg.Role)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.TotpPendingEnc,
	)
	return i, err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM admin_users WHERE id = $1
`

func (q *Queries) DeleteAdmin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdmin, id)
	return err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM recovery_codes WHERE admin_user_id = $1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, adminUserID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, adminUserID)
	return err
}

const getAdmin = `-- name: GetAdmin :one
SELECT id, username, password_hash, role, totp_secret_enc, totp_enabled, failed_logins, locked_until, created_at, totp_pending_enc FROM admin_users WHERE id = $1
`

func (q *Queries) GetAdmin(ctx context.Context, id uuid.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdmin, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.TotpPendingEnc,
	)
	return i, err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one
SELECT id, username, password_hash, role, totp_secret_enc, totp_enabled, failed_logins, locked_until, created_at, totp_pending_enc FROM admin_users WHERE username = $1
`

func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByUsername, username)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.FailedLogins,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.TotpPendingEnc,
	)
	return i, err
}

const getAdminTOTP = `-- name: GetAdminTOTP :one
SELECT totp_secret_enc, totp_pending_enc, totp_enabled FROM admin_users WHERE id = $1
`

type GetAdminTOTPRow struct {
	TotpSecretEnc  []byte `json:"totp_secret_enc"`
	TotpPendingEnc []byte `json:"totp_pending_enc"`
	TotpEnabled    bool   `json:"totp_enabled"`
}

func (q *Queries) GetAdminTOTP(ctx context.Context, id uuid.UUID) (GetAdminTOTPRow, error) {
	row := q.db.QueryRow(ctx, getAdminTOTP, id)
	var i GetAdminTOTPRow
	err := row.Scan(&i.TotpSecretEnc, &i.TotpPendingEnc, &i.TotpEnabled)
	return i, err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec
INSERT INTO recovery_codes (admin_user_id, code_hash) VALUES ($1, $2)
`

type InsertRecoveryCodeParams struct {
	AdminUserID uuid.UUID `json:"admin_user_id"`
	CodeHash    string    `json:"code_hash"`
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCode, arg.AdminUserID, arg.CodeHash)
	return err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, username, password_hash, role, totp_secret_enc, totp_enabled, failed_logins, locked_until, created_at, totp_pending_enc FROM admin_users ORDER BY created_at
`

func (q *Queries) ListAdmins(ctx context.Context) ([]AdminUser, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminUser{}
	for rows.Next() {
		var i AdminUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.PasswordHash,
			&i.Role,
			&i.TotpSecretEnc,
			&i.TotpEnabled,
			&i.FailedLogins,
			&i.LockedUntil,
			&i.CreatedAt,
			&i.TotpPendingEnc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecoveryCodes = `-- name: ListRecoveryCodes :many
SELECT id, admin_user_id, code_hash, used_at FROM recovery_codes WHERE admin_user_id = $1 ORDER BY id
`

func (q *Queries) ListRecoveryCodes(ctx context.Context, adminUserID uuid.UUID) ([]RecoveryCode, error) {
	rows, err := q.db.Query(ctx, listRecoveryCodes, adminUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryCode{}
	for rows.Next() {
		var i RecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.AdminUserID,
			&i.CodeHash,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordFailedLogin = `-- name: RecordFailedLogin :exec
UPDATE admin_users SET failed_logins = failed_logins + 1,
  locked_until = CASE WHEN failed_logins + 1 >= 20 THEN now() + interval '15 minutes' ELSE locked_until END
WHERE id = $1
`

func (q *Queries) RecordFailedLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, recordFailedLogin, id)
	return err
}

const resetFailedLogins = `-- name: ResetFailedLogins :exec
UPDATE admin_users SET failed_logins = 0, locked_until = NULL WHERE id = $1
`

func (q *Queries) ResetFailedLogins(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetFailedLogins, id)
	return err
}

const setAdminTOTP = `-- name: SetAdminTOTP :exec
UPDATE admin_users SET totp_secret_enc = $2, totp_enabled = $3, totp_pending_enc = NULL WHERE id = $1
`

type SetAdminTOTPParams struct {
	ID            uuid.UUID `json:"id"`
	TotpSecretEnc []byte    `json:"totp_secret_enc"`
	TotpEnabled   bool      `json:"totp_enabled"`
}

// SetAdminTOTP writes the live second factor. It always clears the pending secret:
// on confirm the pending secret has just been promoted, and on disable nothing about
// the old enrolment may survive.
func (q *Queries) SetAdminTOTP(ctx context.Context, arg SetAdminTOTPParams) error {
	_, err := q.db.Exec(ctx, setAdminTOTP, arg.ID, arg.TotpSecretEnc, arg.TotpEnabled)
	return err
}

const setAdminTOTPPending = `-- name: SetAdminTOTPPending :exec
UPDATE admin_users SET totp_pending_enc = $2 WHERE id = $1
`

type SetAdminTOTPPendingParams struct {
	ID             uuid.UUID `json:"id"`
	TotpPendingEnc []byte    `json:"totp_pending_enc"`
}

func (q *Queries) SetAdminTOTPPending(ctx context.Context, arg SetAdminTOTPPendingParams) error {
	_, err := q.db.Exec(ctx, setAdminTOTPPending, arg.ID, arg.TotpPendingEnc)
	return err
}

const updateAdminPassword = `-- name: UpdateAdminPassword :exec
UPDATE admin_users SET password_hash = $2 WHERE id = $1
`

type UpdateAdminPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateAdminPassword(ctx context.Context, arg UpdateAdminPasswordParams) error {
	_, err := q.db.Exec(ctx, updateAdminPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateAdminRole = `-- name: UpdateAdminRole :exec
UPDATE admin_users SET role = $2 WHERE id = $1
`

type UpdateAdminRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role AdminRole `json:"role"`
}

func (q *Queries) UpdateAdminRole(ctx context.Context, arg UpdateAdminRoleParams) error {
	_, err := q.db.Exec(ctx, updateAdminRole, arg.ID, arg.Role)
	return err
}

const useRecoveryCode = `-- name: UseRecoveryCode :execrows
UPDATE recovery_codes SET used_at = now()
WHERE admin_user_id = $1 AND code_hash = $2 AND used_at IS NULL
`

type UseRecoveryCodeParams struct {
	AdminUserID uuid.UUID `json:"admin_user_id"`
	CodeHash    string    `json:"code_hash"`
}

// UseRecoveryCode burns a code and reports how many rows it changed (:execrows). The
// `used_at IS NULL` predicate is what makes the burn atomic: two concurrent logins
// presenting the same code produce one row updated and one row not, so exactly one of
// them is let in.
func (q *Queries) UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, useRecoveryCode, arg.AdminUserID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
