// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveAPITokens = `-- name: CountActiveAPITokens :one
SELECT count(*) FROM api_tokens WHERE admin_user_id = $1 AND revoked_at IS NULL AND expires_at > now()
`

func (q *Queries) CountActiveAPITokens(ctx context.Context, adminUserID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAPITokens, adminUserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (admin_user_id, name, prefix, token_hash, scopes, expires_at)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, admin_user_id, name, prefix, token_hash, scopes, created_at, expires_at, last_used_at, revoked_at
`

type CreateAPITokenParams struct {
	AdminUserID uuid.UUID `json:"admin_user_id"`
	Name        string    `json:"name"`
	Prefix      string    `json:"prefix"`
	TokenHash   []byte    `json:"token_hash"`
	Scopes      []string  `json:"scopes"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.AdminUserID,
		arg.Name,
		arg.Prefix,
		arg.TokenHash,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.Name,
		&i.Prefix,
		&i.TokenHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveAPIToken = `-- name: GetActiveAPIToken :one
SELECT t.id, t.admin_user_id, t.scopes, a.username, a.role FROM api_tokens t
JOIN admin_users a ON a.id = t.admin_user_id
WHERE t.token_hash = $1 AND t.revoked_at IS NULL AND t.expires_at > now()
`

type GetActiveAPITokenRow struct {
	ID          uuid.UUID `json:"id"`
	AdminUserID uuid.UUID `json:"admin_user_id"`
	Scopes      []string  `json:"scopes"`
	Username    string    `json:"username"`
	Role        AdminRole `json:"role"`
}

func (q *Queries) GetActiveAPIToken(ctx context.Context, tokenHash []byte) (GetActiveAPITokenRow, error) {
	row := q.db.QueryRow(ctx, getActiveAPIToken, tokenHash)
	var i GetActiveAPITokenRow
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.Scopes,
		&i.Username,
		&i.Role,
	)
	return i, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, name, prefix, scopes, created_at, expires_at, last_used_at, revoked_at
FROM api_tokens WHERE admin_user_id = $1 ORDER BY created_at DESC, id DESC
`

type ListAPITokensRow struct {
	ID         uuid.UUID  `json:"id"`
	Name       string     `json:"name"`
	Prefix     string     `json:"prefix"`
	Scopes     []string   `json:"scopes"`
	CreatedAt  time.Time  `json:"created_at"`
	ExpiresAt  time.Time  `json:"expires_at"`
	LastUsedAt *time.Time `json:"last_used_at"`
	RevokedAt  *time.Time `json:"revoked_at"`
}

func (q *Queries) ListAPITokens(ctx context.Context, adminUserID uuid.UUID) ([]ListAPITokensRow, error) {
	rows, err := q.db.Query(ctx, listAPITokens, adminUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPITokensRow{}
	for rows.Next() {
		var i ListAPITokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Prefix,
			&i.Scopes,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAPITokenOwner = `-- name: LockAPITokenOwner :one
SELECT id FROM admin_users WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockAPITokenOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockAPITokenOwner, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_tokens SET revoked_at = COALESCE(revoked_at, now()) WHERE id = $1 AND admin_user_id = $2
`

type RevokeAPITokenParams struct {
	ID          uuid.UUID `json:"id"`
	AdminUserID uuid.UUID `json:"admin_user_id"`
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.AdminUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAdminAPITokens = `-- name: RevokeAdminAPITokens :exec
UPDATE api_tokens SET revoked_at = COALESCE(revoked_at, now()) WHERE admin_user_id = $1
`

func (q *Queries) RevokeAdminAPITokens(ctx context.Context, adminUserID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAdminAPITokens, adminUserID)
	return err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
AND (last_used_at IS NULL OR last_used_at < now() - interval '1 minute')
`

func (q *Queries) TouchAPIToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}
