// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: apply.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createApplyJob = `-- name: CreateApplyJob :one
INSERT INTO apply_jobs (node_id, kind, status, started_at) VALUES ($1, $2, 'running', now()) RETURNING id, node_id, status, kind, started_at, finished_at, error, log, created_at
`

type CreateApplyJobParams struct {
	NodeID uuid.UUID `json:"node_id"`
	Kind   ApplyKind `json:"kind"`
}

func (q *Queries) CreateApplyJob(ctx context.Context, arg CreateApplyJobParams) (ApplyJob, error) {
	row := q.db.QueryRow(ctx, createApplyJob, arg.NodeID, arg.Kind)
	var i ApplyJob
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Status,
		&i.Kind,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Error,
		&i.Log,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldApplyJobs = `-- name: DeleteOldApplyJobs :execrows
DELETE FROM apply_jobs WHERE finished_at IS NOT NULL AND finished_at < $1
`

func (q *Queries) DeleteOldApplyJobs(ctx context.Context, finishedAt *time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldApplyJobs, finishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishApplyJob = `-- name: FinishApplyJob :exec
UPDATE apply_jobs SET status = $2, finished_at = now(), error = $3, log = $4 WHERE id = $1
`

type FinishApplyJobParams struct {
	ID     uuid.UUID   `json:"id"`
	Status ApplyStatus `json:"status"`
	Error  string      `json:"error"`
	Log    string      `json:"log"`
}

func (q *Queries) FinishApplyJob(ctx context.Context, arg FinishApplyJobParams) error {
	_, err := q.db.Exec(ctx, finishApplyJob,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.Log,
	)
	return err
}

const getNodeSite = `-- name: GetNodeSite :one
SELECT node_id, template_id, bundle, bundle_hash, deployed_hash, updated_at FROM node_sites WHERE node_id = $1
`

func (q *Queries) GetNodeSite(ctx context.Context, nodeID uuid.UUID) (NodeSite, error) {
	row := q.db.QueryRow(ctx, getNodeSite, nodeID)
	var i NodeSite
	err := row.Scan(
		&i.NodeID,
		&i.TemplateID,
		&i.Bundle,
		&i.BundleHash,
		&i.DeployedHash,
		&i.UpdatedAt,
	)
	return i, err
}

const listNodeApplyJobs = `-- name: ListNodeApplyJobs :many
SELECT id, node_id, status, kind, started_at, finished_at, error, log, created_at FROM apply_jobs WHERE node_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListNodeApplyJobsParams struct {
	NodeID uuid.UUID `json:"node_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListNodeApplyJobs(ctx context.Context, arg ListNodeApplyJobsParams) ([]ApplyJob, error) {
	rows, err := q.db.Query(ctx, listNodeApplyJobs, arg.NodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApplyJob{}
	for rows.Next() {
		var i ApplyJob
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Status,
			&i.Kind,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
			&i.Log,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentApplyJobs = `-- name: ListRecentApplyJobs :many
SELECT j.id, j.node_id, j.status, j.kind, j.started_at, j.finished_at, j.error, j.log, j.created_at, n.name AS node_name FROM apply_jobs j JOIN nodes n ON n.id = j.node_id ORDER BY j.created_at DESC LIMIT $1
`

type ListRecentApplyJobsRow struct {
	ID         uuid.UUID   `json:"id"`
	NodeID     uuid.UUID   `json:"node_id"`
	Status     ApplyStatus `json:"status"`
	Kind       ApplyKind   `json:"kind"`
	StartedAt  *time.Time  `json:"started_at"`
	FinishedAt *time.Time  `json:"finished_at"`
	Error      string      `json:"error"`
	Log        string      `json:"log"`
	CreatedAt  time.Time   `json:"created_at"`
	NodeName   string      `json:"node_name"`
}

func (q *Queries) ListRecentApplyJobs(ctx context.Context, limit int32) ([]ListRecentApplyJobsRow, error) {
	rows, err := q.db.Query(ctx, listRecentApplyJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRecentApplyJobsRow{}
	for rows.Next() {
		var i ListRecentApplyJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Status,
			&i.Kind,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Error,
			&i.Log,
			&i.CreatedAt,
			&i.NodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNodeSiteDeployed = `-- name: SetNodeSiteDeployed :exec
UPDATE node_sites SET deployed_hash = $1 WHERE node_id = $2 AND bundle_hash = $1
`

type SetNodeSiteDeployedParams struct {
	Hash   *string   `json:"hash"`
	NodeID uuid.UUID `json:"node_id"`
}

// SetNodeSiteDeployed records the hash of the bundle an apply actually pushed.
// The bundle_hash = @hash guard is what makes it safe against a re-assign that
// lands mid-apply: if node_sites now holds a different bundle, the update
// matches no row, deployed_hash keeps its old value and the next sweep pushes
// the new bundle for real. Writing unconditionally would mark a bundle deployed
// that was never sent, with no recovery path through the UI.
func (q *Queries) SetNodeSiteDeployed(ctx context.Context, arg SetNodeSiteDeployedParams) error {
	_, err := q.db.Exec(ctx, setNodeSiteDeployed, arg.Hash, arg.NodeID)
	return err
}
