// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAudit = `-- name: CountAudit :one
SELECT count(*) FROM audit_log
`

func (q *Queries) CountAudit(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAudit)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditFiltered = `-- name: CountAuditFiltered :one
SELECT count(*) FROM audit_log a LEFT JOIN admin_users u ON u.id = a.admin_user_id
WHERE ($1::text IS NULL OR a.action LIKE $1 || '%' ESCAPE '\')
  AND ($2::text IS NULL OR u.username = $2)
  AND ($3::timestamptz IS NULL OR a.created_at >= $3)
  AND ($4::timestamptz IS NULL OR a.created_at <= $4)
`

type CountAuditFilteredParams struct {
	Action   *string    `json:"action"`
	Username *string    `json:"username"`
	FromAt   *time.Time `json:"from_at"`
	ToAt     *time.Time `json:"to_at"`
}

func (q *Queries) CountAuditFiltered(ctx context.Context, arg CountAuditFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditFiltered,
		arg.Action,
		arg.Username,
		arg.FromAt,
		arg.ToAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_log (admin_user_id, action, target_type, target_id, meta, ip) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditParams struct {
	AdminUserID uuid.NullUUID `json:"admin_user_id"`
	Action      string        `json:"action"`
	TargetType  string        `json:"target_type"`
	TargetID    string        `json:"target_id"`
	Meta        []byte        `json:"meta"`
	Ip          string        `json:"ip"`
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.AdminUserID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Meta,
		arg.Ip,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT a.id, a.admin_user_id, a.action, a.target_type, a.target_id, a.meta, a.ip, a.created_at, u.username FROM audit_log a LEFT JOIN admin_users u ON u.id = a.admin_user_id
ORDER BY a.created_at DESC, a.id DESC LIMIT $1 OFFSET $2
`

type ListAuditParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAuditRow struct {
	ID          int64         `json:"id"`
	AdminUserID uuid.NullUUID `json:"admin_user_id"`
	Action      string        `json:"action"`
	TargetType  string        `json:"target_type"`
	TargetID    string        `json:"target_id"`
	Meta        []byte        `json:"meta"`
	Ip          string        `json:"ip"`
	CreatedAt   time.Time     `json:"created_at"`
	Username    *string       `json:"username"`
}

// The id tiebreaker is load-bearing, not cosmetic: audit_log.id is a bigserial and entries
// written inside one transaction share a created_at to the microsecond, so an unordered tie
// lets Postgres return them in a different order per page and a row can appear on two pages
// or on none.
func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]ListAuditRow, error) {
	rows, err := q.db.Query(ctx, listAudit, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditRow{}
	for rows.Next() {
		var i ListAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminUserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Meta,
			&i.Ip,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditFiltered = `-- name: ListAuditFiltered :many
SELECT a.id, a.admin_user_id, a.action, a.target_type, a.target_id, a.meta, a.ip, a.created_at, u.username FROM audit_log a LEFT JOIN admin_users u ON u.id = a.admin_user_id
WHERE ($3::text IS NULL OR a.action LIKE $3 || '%' ESCAPE '\')
  AND ($4::text IS NULL OR u.username = $4)
  AND ($5::timestamptz IS NULL OR a.created_at >= $5)
  AND ($6::timestamptz IS NULL OR a.created_at <= $6)
ORDER BY a.created_at DESC, a.id DESC LIMIT $1 OFFSET $2
`

type ListAuditFilteredParams struct {
	Limit    int32      `json:"limit"`
	Offset   int32      `json:"offset"`
	Action   *string    `json:"action"`
	Username *string    `json:"username"`
	FromAt   *time.Time `json:"from_at"`
	ToAt     *time.Time `json:"to_at"`
}

type ListAuditFilteredRow struct {
	ID          int64         `json:"id"`
	AdminUserID uuid.NullUUID `json:"admin_user_id"`
	Action      string        `json:"action"`
	TargetType  string        `json:"target_type"`
	TargetID    string        `json:"target_id"`
	Meta        []byte        `json:"meta"`
	Ip          string        `json:"ip"`
	CreatedAt   time.Time     `json:"created_at"`
	Username    *string       `json:"username"`
}

func (q *Queries) ListAuditFiltered(ctx context.Context, arg ListAuditFilteredParams) ([]ListAuditFilteredRow, error) {
	rows, err := q.db.Query(ctx, listAuditFiltered,
		arg.Limit,
		arg.Offset,
		arg.Action,
		arg.Username,
		arg.FromAt,
		arg.ToAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditFilteredRow{}
	for rows.Next() {
		var i ListAuditFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.AdminUserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Meta,
			&i.Ip,
			&i.CreatedAt,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
