// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backups.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countBackupsSince = `-- name: CountBackupsSince :one
SELECT count(*) FROM backups WHERE kind = $1 AND created_at >= $2
`

type CountBackupsSinceParams struct {
	Kind      BackupKind `json:"kind"`
	CreatedAt time.Time  `json:"created_at"`
}

// CountBackupsSince answers "has the nightly dump already run today?" without
// pulling the whole list into the worker.
func (q *Queries) CountBackupsSince(ctx context.Context, arg CountBackupsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBackupsSince, arg.Kind, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBackup = `-- name: DeleteBackup :execrows
DELETE FROM backups WHERE id = $1
`

func (q *Queries) DeleteBackup(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBackup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBackup = `-- name: GetBackup :one
SELECT id, path, size, kind, created_at FROM backups WHERE id = $1
`

func (q *Queries) GetBackup(ctx context.Context, id uuid.UUID) (Backup, error) {
	row := q.db.QueryRow(ctx, getBackup, id)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Size,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const insertBackup = `-- name: InsertBackup :one
INSERT INTO backups (path, size, kind) VALUES ($1, $2, $3) RETURNING id, path, size, kind, created_at
`

type InsertBackupParams struct {
	Path string     `json:"path"`
	Size int64      `json:"size"`
	Kind BackupKind `json:"kind"`
}

func (q *Queries) InsertBackup(ctx context.Context, arg InsertBackupParams) (Backup, error) {
	row := q.db.QueryRow(ctx, insertBackup, arg.Path, arg.Size, arg.Kind)
	var i Backup
	err := row.Scan(
		&i.ID,
		&i.Path,
		&i.Size,
		&i.Kind,
		&i.CreatedAt,
	)
	return i, err
}

const listBackups = `-- name: ListBackups :many
SELECT id, path, size, kind, created_at FROM backups ORDER BY created_at DESC
`

func (q *Queries) ListBackups(ctx context.Context) ([]Backup, error) {
	rows, err := q.db.Query(ctx, listBackups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Backup{}
	for rows.Next() {
		var i Backup
		if err := rows.Scan(
			&i.ID,
			&i.Path,
			&i.Size,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
