// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blocklists.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getNodeBlocklist = `-- name: GetNodeBlocklist :one
SELECT node_id, entries, revision, updated_at FROM node_blocklists WHERE node_id = $1
`

func (q *Queries) GetNodeBlocklist(ctx context.Context, nodeID uuid.UUID) (NodeBlocklist, error) {
	row := q.db.QueryRow(ctx, getNodeBlocklist, nodeID)
	var i NodeBlocklist
	err := row.Scan(
		&i.NodeID,
		&i.Entries,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const listBlocklistsToSync = `-- name: ListBlocklistsToSync :many
SELECT n.id AS node_id,
       COALESCE(b.entries, '[]'::jsonb)::jsonb AS entries,
       COALESCE(b.revision, 0)::bigint AS revision,
       n.last_health
FROM nodes n
LEFT JOIN node_blocklists b ON b.node_id = n.id
WHERE n.status IN ('online', 'degraded')
`

type ListBlocklistsToSyncRow struct {
	NodeID     uuid.UUID `json:"node_id"`
	Entries    []byte    `json:"entries"`
	Revision   int64     `json:"revision"`
	LastHealth []byte    `json:"last_health"`
}

func (q *Queries) ListBlocklistsToSync(ctx context.Context) ([]ListBlocklistsToSyncRow, error) {
	rows, err := q.db.Query(ctx, listBlocklistsToSync)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlocklistsToSyncRow{}
	for rows.Next() {
		var i ListBlocklistsToSyncRow
		if err := rows.Scan(
			&i.NodeID,
			&i.Entries,
			&i.Revision,
			&i.LastHealth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveNodeBlocklist = `-- name: SaveNodeBlocklist :one
INSERT INTO node_blocklists (node_id, entries, revision, updated_at)
VALUES ($1, $2, 1, now())
ON CONFLICT (node_id) DO UPDATE
  SET entries = EXCLUDED.entries, revision = node_blocklists.revision + 1, updated_at = now()
  WHERE $3::bigint IS NULL OR node_blocklists.revision = $3::bigint
RETURNING node_id, entries, revision, updated_at
`

type SaveNodeBlocklistParams struct {
	NodeID           uuid.UUID   `json:"node_id"`
	Entries          []byte      `json:"entries"`
	ExpectedRevision pgtype.Int8 `json:"expected_revision"`
}

func (q *Queries) SaveNodeBlocklist(ctx context.Context, arg SaveNodeBlocklistParams) (NodeBlocklist, error) {
	row := q.db.QueryRow(ctx, saveNodeBlocklist, arg.NodeID, arg.Entries, arg.ExpectedRevision)
	var i NodeBlocklist
	err := row.Scan(
		&i.NodeID,
		&i.Entries,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}
