// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branding.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const activateBrandingOne = `-- name: ActivateBrandingOne :exec
UPDATE branding_profiles SET is_active = true WHERE id = $1
`

func (q *Queries) ActivateBrandingOne(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, activateBrandingOne, id)
	return err
}

const createBranding = `-- name: CreateBranding :one
INSERT INTO branding_profiles (name, panel_name, logo_path, favicon_path, primary_color, accent_color, theme_default, login_bg_path, login_text, support_link, footer_text, custom_css)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12) RETURNING id, name, is_active, panel_name, logo_path, favicon_path, primary_color, accent_color, theme_default, login_bg_path, login_text, support_link, footer_text, custom_css, updated_at
`

type CreateBrandingParams struct {
	Name         string `json:"name"`
	PanelName    string `json:"panel_name"`
	LogoPath     string `json:"logo_path"`
	FaviconPath  string `json:"favicon_path"`
	PrimaryColor string `json:"primary_color"`
	AccentColor  string `json:"accent_color"`
	ThemeDefault string `json:"theme_default"`
	LoginBgPath  string `json:"login_bg_path"`
	LoginText    string `json:"login_text"`
	SupportLink  string `json:"support_link"`
	FooterText   string `json:"footer_text"`
	CustomCss    string `json:"custom_css"`
}

func (q *Queries) CreateBranding(ctx context.Context, arg CreateBrandingParams) (BrandingProfile, error) {
	row := q.db.QueryRow(ctx, createBranding,
		arg.Name,
		arg.PanelName,
		arg.LogoPath,
		arg.FaviconPath,
		arg.PrimaryColor,
		arg.AccentColor,
		arg.ThemeDefault,
		arg.LoginBgPath,
		arg.LoginText,
		arg.SupportLink,
		arg.FooterText,
		arg.CustomCss,
	)
	var i BrandingProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.PanelName,
		&i.LogoPath,
		&i.FaviconPath,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.ThemeDefault,
		&i.LoginBgPath,
		&i.LoginText,
		&i.SupportLink,
		&i.FooterText,
		&i.CustomCss,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateBranding = `-- name: DeactivateBranding :exec
UPDATE branding_profiles SET is_active = false WHERE is_active
`

func (q *Queries) DeactivateBranding(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateBranding)
	return err
}

const deleteBranding = `-- name: DeleteBranding :execrows
DELETE FROM branding_profiles WHERE id = $1 AND is_active = false
`

// DeleteBranding returns the affected row count so the handler can tell a real
// delete from a no-op: the profile was activated between the pre-check and this
// statement, and the AND is_active = false predicate silently matched nothing.
func (q *Queries) DeleteBranding(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBranding, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveBranding = `-- name: GetActiveBranding :one
SELECT id, name, is_active, panel_name, logo_path, favicon_path, primary_color, accent_color, theme_default, login_bg_path, login_text, support_link, footer_text, custom_css, updated_at FROM branding_profiles WHERE is_active = true LIMIT 1
`

func (q *Queries) GetActiveBranding(ctx context.Context) (BrandingProfile, error) {
	row := q.db.QueryRow(ctx, getActiveBranding)
	var i BrandingProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.PanelName,
		&i.LogoPath,
		&i.FaviconPath,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.ThemeDefault,
		&i.LoginBgPath,
		&i.LoginText,
		&i.SupportLink,
		&i.FooterText,
		&i.CustomCss,
		&i.UpdatedAt,
	)
	return i, err
}

const getBranding = `-- name: GetBranding :one
SELECT id, name, is_active, panel_name, logo_path, favicon_path, primary_color, accent_color, theme_default, login_bg_path, login_text, support_link, footer_text, custom_css, updated_at FROM branding_profiles WHERE id = $1
`

func (q *Queries) GetBranding(ctx context.Context, id uuid.UUID) (BrandingProfile, error) {
	row := q.db.QueryRow(ctx, getBranding, id)
	var i BrandingProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.PanelName,
		&i.LogoPath,
		&i.FaviconPath,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.ThemeDefault,
		&i.LoginBgPath,
		&i.LoginText,
		&i.SupportLink,
		&i.FooterText,
		&i.CustomCss,
		&i.UpdatedAt,
	)
	return i, err
}

const listBranding = `-- name: ListBranding :many
SELECT id, name, is_active, panel_name, logo_path, favicon_path, primary_color, accent_color, theme_default, login_bg_path, login_text, support_link, footer_text, custom_css, updated_at FROM branding_profiles ORDER BY is_active DESC, name
`

func (q *Queries) ListBranding(ctx context.Context) ([]BrandingProfile, error) {
	rows, err := q.db.Query(ctx, listBranding)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BrandingProfile{}
	for rows.Next() {
		var i BrandingProfile
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.PanelName,
			&i.LogoPath,
			&i.FaviconPath,
			&i.PrimaryColor,
			&i.AccentColor,
			&i.ThemeDefault,
			&i.LoginBgPath,
			&i.LoginText,
			&i.SupportLink,
			&i.FooterText,
			&i.CustomCss,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBrandingAsset = `-- name: SetBrandingAsset :exec
UPDATE branding_profiles SET
  logo_path = CASE WHEN $2::text = 'logo' THEN $3 ELSE logo_path END,
  favicon_path = CASE WHEN $2::text = 'favicon' THEN $3 ELSE favicon_path END,
  login_bg_path = CASE WHEN $2::text = 'login_bg' THEN $3 ELSE login_bg_path END,
  updated_at = now() WHERE id = $1
`

type SetBrandingAssetParams struct {
	ID       uuid.UUID `json:"id"`
	Column2  string    `json:"column_2"`
	LogoPath string    `json:"logo_path"`
}

func (q *Queries) SetBrandingAsset(ctx context.Context, arg SetBrandingAssetParams) error {
	_, err := q.db.Exec(ctx, setBrandingAsset, arg.ID, arg.Column2, arg.LogoPath)
	return err
}

const updateBranding = `-- name: UpdateBranding :one
UPDATE branding_profiles SET name = $2, panel_name = $3, primary_color = $4, accent_color = $5, theme_default = $6, login_text = $7, support_link = $8, footer_text = $9, custom_css = $10, updated_at = now()
WHERE id = $1 RETURNING id, name, is_active, panel_name, logo_path, favicon_path, primary_color, accent_color, theme_default, login_bg_path, login_text, support_link, footer_text, custom_css, updated_at
`

type UpdateBrandingParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	PanelName    string    `json:"panel_name"`
	PrimaryColor string    `json:"primary_color"`
	AccentColor  string    `json:"accent_color"`
	ThemeDefault string    `json:"theme_default"`
	LoginText    string    `json:"login_text"`
	SupportLink  string    `json:"support_link"`
	FooterText   string    `json:"footer_text"`
	CustomCss    string    `json:"custom_css"`
}

func (q *Queries) UpdateBranding(ctx context.Context, arg UpdateBrandingParams) (BrandingProfile, error) {
	row := q.db.QueryRow(ctx, updateBranding,
		arg.ID,
		arg.Name,
		arg.PanelName,
		arg.PrimaryColor,
		arg.AccentColor,
		arg.ThemeDefault,
		arg.LoginText,
		arg.SupportLink,
		arg.FooterText,
		arg.CustomCss,
	)
	var i BrandingProfile
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.PanelName,
		&i.LogoPath,
		&i.FaviconPath,
		&i.PrimaryColor,
		&i.AccentColor,
		&i.ThemeDefault,
		&i.LoginBgPath,
		&i.LoginText,
		&i.SupportLink,
		&i.FooterText,
		&i.CustomCss,
		&i.UpdatedAt,
	)
	return i, err
}
