// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diagnostics.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertNodeDiagnostics = `-- name: InsertNodeDiagnostics :one
INSERT INTO node_diagnostics (node_id, started_at, finished_at, overall_status, trigger, checks)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, node_id, started_at, finished_at, overall_status, trigger, checks
`

type InsertNodeDiagnosticsParams struct {
	NodeID        uuid.UUID  `json:"node_id"`
	StartedAt     time.Time  `json:"started_at"`
	FinishedAt    *time.Time `json:"finished_at"`
	OverallStatus string     `json:"overall_status"`
	Trigger       string     `json:"trigger"`
	Checks        []byte     `json:"checks"`
}

func (q *Queries) InsertNodeDiagnostics(ctx context.Context, arg InsertNodeDiagnosticsParams) (NodeDiagnostic, error) {
	row := q.db.QueryRow(ctx, insertNodeDiagnostics,
		arg.NodeID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.OverallStatus,
		arg.Trigger,
		arg.Checks,
	)
	var i NodeDiagnostic
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.OverallStatus,
		&i.Trigger,
		&i.Checks,
	)
	return i, err
}

const latestCertChecks = `-- name: LatestCertChecks :many
SELECT n.id AS node_id, d.started_at, d.cert::jsonb AS cert
FROM nodes n
JOIN LATERAL (
  SELECT started_at, jsonb_path_query_first(checks, '$[*].checks[*] ? (@.key == "certificate_expiry" && @.value != null)') AS cert
  FROM node_diagnostics
  WHERE node_id = n.id
    AND jsonb_path_exists(checks, '$[*].checks[*] ? (@.key == "certificate_expiry" && @.value != null)')
  ORDER BY started_at DESC LIMIT 1
) d ON true
`

type LatestCertChecksRow struct {
	NodeID    uuid.UUID `json:"node_id"`
	StartedAt time.Time `json:"started_at"`
	Cert      []byte    `json:"cert"`
}

// LatestCertChecks is, per node, the certificate_expiry check of its newest diagnostics pass that
// measured one.
func (q *Queries) LatestCertChecks(ctx context.Context) ([]LatestCertChecksRow, error) {
	rows, err := q.db.Query(ctx, latestCertChecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LatestCertChecksRow{}
	for rows.Next() {
		var i LatestCertChecksRow
		if err := rows.Scan(&i.NodeID, &i.StartedAt, &i.Cert); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeDiagnostics = `-- name: ListNodeDiagnostics :many
SELECT id, node_id, started_at, finished_at, overall_status, trigger, checks FROM node_diagnostics WHERE node_id = $1 ORDER BY started_at DESC LIMIT $2
`

type ListNodeDiagnosticsParams struct {
	NodeID uuid.UUID `json:"node_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListNodeDiagnostics(ctx context.Context, arg ListNodeDiagnosticsParams) ([]NodeDiagnostic, error) {
	rows, err := q.db.Query(ctx, listNodeDiagnostics, arg.NodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeDiagnostic{}
	for rows.Next() {
		var i NodeDiagnostic
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.OverallStatus,
			&i.Trigger,
			&i.Checks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
