// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diagnostics.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertNodeDiagnostics = `-- name: InsertNodeDiagnostics :one
INSERT INTO node_diagnostics (node_id, started_at, finished_at, overall_status, trigger, checks)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, node_id, started_at, finished_at, overall_status, trigger, checks
`

type InsertNodeDiagnosticsParams struct {
	NodeID        uuid.UUID  `json:"node_id"`
	StartedAt     time.Time  `json:"started_at"`
	FinishedAt    *time.Time `json:"finished_at"`
	OverallStatus string     `json:"overall_status"`
	Trigger       string     `json:"trigger"`
	Checks        []byte     `json:"checks"`
}

func (q *Queries) InsertNodeDiagnostics(ctx context.Context, arg InsertNodeDiagnosticsParams) (NodeDiagnostic, error) {
	row := q.db.QueryRow(ctx, insertNodeDiagnostics,
		arg.NodeID,
		arg.StartedAt,
		arg.FinishedAt,
		arg.OverallStatus,
		arg.Trigger,
		arg.Checks,
	)
	var i NodeDiagnostic
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.OverallStatus,
		&i.Trigger,
		&i.Checks,
	)
	return i, err
}

const listNodeDiagnostics = `-- name: ListNodeDiagnostics :many
SELECT id, node_id, started_at, finished_at, overall_status, trigger, checks FROM node_diagnostics WHERE node_id = $1 ORDER BY started_at DESC LIMIT $2
`

type ListNodeDiagnosticsParams struct {
	NodeID uuid.UUID `json:"node_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListNodeDiagnostics(ctx context.Context, arg ListNodeDiagnosticsParams) ([]NodeDiagnostic, error) {
	rows, err := q.db.Query(ctx, listNodeDiagnostics, arg.NodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeDiagnostic{}
	for rows.Next() {
		var i NodeDiagnostic
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.OverallStatus,
			&i.Trigger,
			&i.Checks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
