// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: keys.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activatePendingKeysForNode = `-- name: ActivatePendingKeysForNode :exec
UPDATE access_keys k SET status = 'active' WHERE k.status = 'pending'
  AND EXISTS (SELECT 1 FROM profiles p WHERE p.access_key_id = k.id)
  AND NOT EXISTS (SELECT 1 FROM profiles p WHERE p.access_key_id = k.id AND p.sync_state <> 'synced')
`

func (q *Queries) ActivatePendingKeysForNode(ctx context.Context) error {
	_, err := q.db.Exec(ctx, activatePendingKeysForNode)
	return err
}

const countKeys = `-- name: CountKeys :one
SELECT count(*) FROM access_keys k
WHERE ($1::key_type IS NULL OR k.type = $1)
  AND ($2::key_status IS NULL OR k.status = $2)
  AND ($3::uuid IS NULL OR EXISTS (SELECT 1 FROM key_bindings b WHERE b.access_key_id = k.id AND b.node_id = $3))
  AND ($4::text IS NULL OR k.label ILIKE '%' || $4 || '%' OR k.owner_label ILIKE '%' || $4 || '%')
`

type CountKeysParams struct {
	Type   NullKeyType   `json:"type"`
	Status NullKeyStatus `json:"status"`
	NodeID uuid.NullUUID `json:"node_id"`
	Q      *string       `json:"q"`
}

func (q *Queries) CountKeys(ctx context.Context, arg CountKeysParams) (int64, error) {
	row := q.db.QueryRow(ctx, countKeys,
		arg.Type,
		arg.Status,
		arg.NodeID,
		arg.Q,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countKeysByStatus = `-- name: CountKeysByStatus :many
SELECT status, count(*) AS n FROM access_keys GROUP BY status
`

type CountKeysByStatusRow struct {
	Status KeyStatus `json:"status"`
	N      int64     `json:"n"`
}

func (q *Queries) CountKeysByStatus(ctx context.Context) ([]CountKeysByStatusRow, error) {
	rows, err := q.db.Query(ctx, countKeysByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountKeysByStatusRow{}
	for rows.Next() {
		var i CountKeysByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBinding = `-- name: CreateBinding :exec
INSERT INTO key_bindings (access_key_id, node_id, profile_id) VALUES ($1, $2, $3)
`

type CreateBindingParams struct {
	AccessKeyID uuid.UUID `json:"access_key_id"`
	NodeID      uuid.UUID `json:"node_id"`
	ProfileID   uuid.UUID `json:"profile_id"`
}

func (q *Queries) CreateBinding(ctx context.Context, arg CreateBindingParams) error {
	_, err := q.db.Exec(ctx, createBinding, arg.AccessKeyID, arg.NodeID, arg.ProfileID)
	return err
}

const createKey = `-- name: CreateKey :one
INSERT INTO access_keys (label, type, owner_label, secret_enc, carrier_mode, limits, expires_at, note, created_by, telemt_limits)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, COALESCE($10::jsonb, '{}'::jsonb)) RETURNING id, label, type, owner_label, secret_enc, status, carrier_mode, limits, expires_at, revoked_at, note, created_by, created_at, telemt_limits
`

type CreateKeyParams struct {
	Label        string        `json:"label"`
	Type         KeyType       `json:"type"`
	OwnerLabel   string        `json:"owner_label"`
	SecretEnc    []byte        `json:"secret_enc"`
	CarrierMode  string        `json:"carrier_mode"`
	Limits       []byte        `json:"limits"`
	ExpiresAt    *time.Time    `json:"expires_at"`
	Note         string        `json:"note"`
	CreatedBy    uuid.NullUUID `json:"created_by"`
	TelemtLimits []byte        `json:"telemt_limits"`
}

func (q *Queries) CreateKey(ctx context.Context, arg CreateKeyParams) (AccessKey, error) {
	row := q.db.QueryRow(ctx, createKey,
		arg.Label,
		arg.Type,
		arg.OwnerLabel,
		arg.SecretEnc,
		arg.CarrierMode,
		arg.Limits,
		arg.ExpiresAt,
		arg.Note,
		arg.CreatedBy,
		arg.TelemtLimits,
	)
	var i AccessKey
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Type,
		&i.OwnerLabel,
		&i.SecretEnc,
		&i.Status,
		&i.CarrierMode,
		&i.Limits,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.TelemtLimits,
	)
	return i, err
}

const createSubscriptionToken = `-- name: CreateSubscriptionToken :one
INSERT INTO subscription_tokens (token_hash, access_key_id) VALUES ($1, $2) RETURNING token_hash, access_key_id, created_at, revoked_at
`

type CreateSubscriptionTokenParams struct {
	TokenHash   string    `json:"token_hash"`
	AccessKeyID uuid.UUID `json:"access_key_id"`
}

func (q *Queries) CreateSubscriptionToken(ctx context.Context, arg CreateSubscriptionTokenParams) (SubscriptionToken, error) {
	row := q.db.QueryRow(ctx, createSubscriptionToken, arg.TokenHash, arg.AccessKeyID)
	var i SubscriptionToken
	err := row.Scan(
		&i.TokenHash,
		&i.AccessKeyID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteBinding = `-- name: DeleteBinding :exec
DELETE FROM key_bindings WHERE access_key_id = $1 AND node_id = $2
`

type DeleteBindingParams struct {
	AccessKeyID uuid.UUID `json:"access_key_id"`
	NodeID      uuid.UUID `json:"node_id"`
}

func (q *Queries) DeleteBinding(ctx context.Context, arg DeleteBindingParams) error {
	_, err := q.db.Exec(ctx, deleteBinding, arg.AccessKeyID, arg.NodeID)
	return err
}

const deleteKey = `-- name: DeleteKey :exec
DELETE FROM access_keys WHERE id = $1
`

func (q *Queries) DeleteKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteKey, id)
	return err
}

const getKey = `-- name: GetKey :one
SELECT id, label, type, owner_label, secret_enc, status, carrier_mode, limits, expires_at, revoked_at, note, created_by, created_at, telemt_limits FROM access_keys WHERE id = $1
`

func (q *Queries) GetKey(ctx context.Context, id uuid.UUID) (AccessKey, error) {
	row := q.db.QueryRow(ctx, getKey, id)
	var i AccessKey
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Type,
		&i.OwnerLabel,
		&i.SecretEnc,
		&i.Status,
		&i.CarrierMode,
		&i.Limits,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.TelemtLimits,
	)
	return i, err
}

const getKeySubscription = `-- name: GetKeySubscription :one
SELECT token_hash, access_key_id, created_at, revoked_at FROM subscription_tokens WHERE access_key_id = $1 AND revoked_at IS NULL ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetKeySubscription(ctx context.Context, accessKeyID uuid.UUID) (SubscriptionToken, error) {
	row := q.db.QueryRow(ctx, getKeySubscription, accessKeyID)
	var i SubscriptionToken
	err := row.Scan(
		&i.TokenHash,
		&i.AccessKeyID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getSubscriptionByHash = `-- name: GetSubscriptionByHash :one
SELECT token_hash, access_key_id, created_at, revoked_at FROM subscription_tokens WHERE token_hash = $1
`

func (q *Queries) GetSubscriptionByHash(ctx context.Context, tokenHash string) (SubscriptionToken, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByHash, tokenHash)
	var i SubscriptionToken
	err := row.Scan(
		&i.TokenHash,
		&i.AccessKeyID,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveSubscriptionAccessKeyIDs = `-- name: ListActiveSubscriptionAccessKeyIDs :many
SELECT DISTINCT access_key_id FROM subscription_tokens
WHERE access_key_id = ANY($1::uuid[]) AND revoked_at IS NULL
`

// ListActiveSubscriptionAccessKeyIDs is GetKeySubscription for a whole page of keys at
// once, so the list endpoint can flag subscription_active without one query per row.
func (q *Queries) ListActiveSubscriptionAccessKeyIDs(ctx context.Context, keyIds []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveSubscriptionAccessKeyIDs, keyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var access_key_id uuid.UUID
		if err := rows.Scan(&access_key_id); err != nil {
			return nil, err
		}
		items = append(items, access_key_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBindingsForKeys = `-- name: ListBindingsForKeys :many
SELECT b.access_key_id, b.node_id, b.profile_id, n.name AS node_name, n.hostname, n.engine, n.tls_domain, n.classic_port, p.sync_state FROM key_bindings b
JOIN nodes n ON n.id = b.node_id JOIN profiles p ON p.id = b.profile_id
WHERE b.access_key_id = ANY($1::uuid[]) ORDER BY b.access_key_id, n.name
`

type ListBindingsForKeysRow struct {
	AccessKeyID uuid.UUID  `json:"access_key_id"`
	NodeID      uuid.UUID  `json:"node_id"`
	ProfileID   uuid.UUID  `json:"profile_id"`
	NodeName    string     `json:"node_name"`
	Hostname    string     `json:"hostname"`
	Engine      NodeEngine `json:"engine"`
	TlsDomain   string     `json:"tls_domain"`
	ClassicPort int32      `json:"classic_port"`
	SyncState   SyncState  `json:"sync_state"`
}

// ListBindingsForKeys is ListKeyBindings for a whole page of keys at once, so
// the list endpoint no longer issues one binding query per key.
func (q *Queries) ListBindingsForKeys(ctx context.Context, keyIds []uuid.UUID) ([]ListBindingsForKeysRow, error) {
	rows, err := q.db.Query(ctx, listBindingsForKeys, keyIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBindingsForKeysRow{}
	for rows.Next() {
		var i ListBindingsForKeysRow
		if err := rows.Scan(
			&i.AccessKeyID,
			&i.NodeID,
			&i.ProfileID,
			&i.NodeName,
			&i.Hostname,
			&i.Engine,
			&i.TlsDomain,
			&i.ClassicPort,
			&i.SyncState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredActiveKeys = `-- name: ListExpiredActiveKeys :many
SELECT id, label, type, owner_label, secret_enc, status, carrier_mode, limits, expires_at, revoked_at, note, created_by, created_at, telemt_limits FROM access_keys WHERE status IN ('pending','active') AND expires_at IS NOT NULL AND expires_at <= now()
`

func (q *Queries) ListExpiredActiveKeys(ctx context.Context) ([]AccessKey, error) {
	rows, err := q.db.Query(ctx, listExpiredActiveKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessKey{}
	for rows.Next() {
		var i AccessKey
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Type,
			&i.OwnerLabel,
			&i.SecretEnc,
			&i.Status,
			&i.CarrierMode,
			&i.Limits,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.TelemtLimits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeyBindings = `-- name: ListKeyBindings :many
SELECT b.access_key_id, b.node_id, b.profile_id, n.name AS node_name, n.hostname, n.engine, n.tls_domain, n.classic_port, p.sync_state FROM key_bindings b
JOIN nodes n ON n.id = b.node_id JOIN profiles p ON p.id = b.profile_id
WHERE b.access_key_id = $1 ORDER BY n.name
`

type ListKeyBindingsRow struct {
	AccessKeyID uuid.UUID  `json:"access_key_id"`
	NodeID      uuid.UUID  `json:"node_id"`
	ProfileID   uuid.UUID  `json:"profile_id"`
	NodeName    string     `json:"node_name"`
	Hostname    string     `json:"hostname"`
	Engine      NodeEngine `json:"engine"`
	TlsDomain   string     `json:"tls_domain"`
	ClassicPort int32      `json:"classic_port"`
	SyncState   SyncState  `json:"sync_state"`
}

func (q *Queries) ListKeyBindings(ctx context.Context, accessKeyID uuid.UUID) ([]ListKeyBindingsRow, error) {
	rows, err := q.db.Query(ctx, listKeyBindings, accessKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKeyBindingsRow{}
	for rows.Next() {
		var i ListKeyBindingsRow
		if err := rows.Scan(
			&i.AccessKeyID,
			&i.NodeID,
			&i.ProfileID,
			&i.NodeName,
			&i.Hostname,
			&i.Engine,
			&i.TlsDomain,
			&i.ClassicPort,
			&i.SyncState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeys = `-- name: ListKeys :many
SELECT k.id, k.label, k.type, k.owner_label, k.secret_enc, k.status, k.carrier_mode, k.limits, k.expires_at, k.revoked_at, k.note, k.created_by, k.created_at, k.telemt_limits FROM access_keys k
WHERE ($3::key_type IS NULL OR k.type = $3)
  AND ($4::key_status IS NULL OR k.status = $4)
  AND ($5::uuid IS NULL OR EXISTS (SELECT 1 FROM key_bindings b WHERE b.access_key_id = k.id AND b.node_id = $5))
  AND ($6::text IS NULL OR k.label ILIKE '%' || $6 || '%' OR k.owner_label ILIKE '%' || $6 || '%')
ORDER BY k.created_at DESC LIMIT $1 OFFSET $2
`

type ListKeysParams struct {
	Limit  int32         `json:"limit"`
	Offset int32         `json:"offset"`
	Type   NullKeyType   `json:"type"`
	Status NullKeyStatus `json:"status"`
	NodeID uuid.NullUUID `json:"node_id"`
	Q      *string       `json:"q"`
}

func (q *Queries) ListKeys(ctx context.Context, arg ListKeysParams) ([]AccessKey, error) {
	rows, err := q.db.Query(ctx, listKeys,
		arg.Limit,
		arg.Offset,
		arg.Type,
		arg.Status,
		arg.NodeID,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccessKey{}
	for rows.Next() {
		var i AccessKey
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Type,
			&i.OwnerLabel,
			&i.SecretEnc,
			&i.Status,
			&i.CarrierMode,
			&i.Limits,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.Note,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.TelemtLimits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeKeyBindings = `-- name: ListNodeKeyBindings :many
SELECT b.access_key_id, b.node_id, b.profile_id, k.status AS key_status FROM key_bindings b JOIN access_keys k ON k.id = b.access_key_id WHERE b.node_id = $1
`

type ListNodeKeyBindingsRow struct {
	AccessKeyID uuid.UUID `json:"access_key_id"`
	NodeID      uuid.UUID `json:"node_id"`
	ProfileID   uuid.UUID `json:"profile_id"`
	KeyStatus   KeyStatus `json:"key_status"`
}

func (q *Queries) ListNodeKeyBindings(ctx context.Context, nodeID uuid.UUID) ([]ListNodeKeyBindingsRow, error) {
	rows, err := q.db.Query(ctx, listNodeKeyBindings, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodeKeyBindingsRow{}
	for rows.Next() {
		var i ListNodeKeyBindingsRow
		if err := rows.Scan(
			&i.AccessKeyID,
			&i.NodeID,
			&i.ProfileID,
			&i.KeyStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSubscriptionTokensForKey = `-- name: RevokeSubscriptionTokensForKey :exec
UPDATE subscription_tokens SET revoked_at = now() WHERE access_key_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSubscriptionTokensForKey(ctx context.Context, accessKeyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSubscriptionTokensForKey, accessKeyID)
	return err
}

const setKeyExpiry = `-- name: SetKeyExpiry :exec
UPDATE access_keys SET expires_at = $2 WHERE id = $1
`

type SetKeyExpiryParams struct {
	ID        uuid.UUID  `json:"id"`
	ExpiresAt *time.Time `json:"expires_at"`
}

func (q *Queries) SetKeyExpiry(ctx context.Context, arg SetKeyExpiryParams) error {
	_, err := q.db.Exec(ctx, setKeyExpiry, arg.ID, arg.ExpiresAt)
	return err
}

const setKeySecret = `-- name: SetKeySecret :exec
UPDATE access_keys SET secret_enc = $2, status = 'pending', revoked_at = NULL WHERE id = $1
`

type SetKeySecretParams struct {
	ID        uuid.UUID `json:"id"`
	SecretEnc []byte    `json:"secret_enc"`
}

func (q *Queries) SetKeySecret(ctx context.Context, arg SetKeySecretParams) error {
	_, err := q.db.Exec(ctx, setKeySecret, arg.ID, arg.SecretEnc)
	return err
}

const setKeyStatus = `-- name: SetKeyStatus :exec
UPDATE access_keys SET status = $2::key_status, revoked_at = CASE WHEN $2::key_status = 'revoked' THEN now() ELSE revoked_at END WHERE id = $1
`

type SetKeyStatusParams struct {
	ID      uuid.UUID `json:"id"`
	Column2 KeyStatus `json:"column_2"`
}

func (q *Queries) SetKeyStatus(ctx context.Context, arg SetKeyStatusParams) error {
	_, err := q.db.Exec(ctx, setKeyStatus, arg.ID, arg.Column2)
	return err
}

const updateKey = `-- name: UpdateKey :one
UPDATE access_keys SET label = $2, owner_label = $3, note = $4, expires_at = $5, carrier_mode = $6, limits = $7,
  telemt_limits = COALESCE($8::jsonb, telemt_limits)
WHERE id = $1 RETURNING id, label, type, owner_label, secret_enc, status, carrier_mode, limits, expires_at, revoked_at, note, created_by, created_at, telemt_limits
`

type UpdateKeyParams struct {
	ID           uuid.UUID  `json:"id"`
	Label        string     `json:"label"`
	OwnerLabel   string     `json:"owner_label"`
	Note         string     `json:"note"`
	ExpiresAt    *time.Time `json:"expires_at"`
	CarrierMode  string     `json:"carrier_mode"`
	Limits       []byte     `json:"limits"`
	TelemtLimits []byte     `json:"telemt_limits"`
}

func (q *Queries) UpdateKey(ctx context.Context, arg UpdateKeyParams) (AccessKey, error) {
	row := q.db.QueryRow(ctx, updateKey,
		arg.ID,
		arg.Label,
		arg.OwnerLabel,
		arg.Note,
		arg.ExpiresAt,
		arg.CarrierMode,
		arg.Limits,
		arg.TelemtLimits,
	)
	var i AccessKey
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Type,
		&i.OwnerLabel,
		&i.SecretEnc,
		&i.Status,
		&i.CarrierMode,
		&i.Limits,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Note,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.TelemtLimits,
	)
	return i, err
}
