// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AdminRole string

const (
	AdminRoleOwner  AdminRole = "owner"
	AdminRoleAdmin  AdminRole = "admin"
	AdminRoleViewer AdminRole = "viewer"
)

func (e *AdminRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AdminRole(s)
	case string:
		*e = AdminRole(s)
	default:
		return fmt.Errorf("unsupported scan type for AdminRole: %T", src)
	}
	return nil
}

type NullAdminRole struct {
	AdminRole AdminRole `json:"admin_role"`
	Valid     bool      `json:"valid"` // Valid is true if AdminRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAdminRole) Scan(value interface{}) error {
	if value == nil {
		ns.AdminRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AdminRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAdminRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AdminRole), nil
}

type ApplyKind string

const (
	ApplyKindProfiles ApplyKind = "profiles"
	ApplyKindSite     ApplyKind = "site"
	ApplyKindBoth     ApplyKind = "both"
)

func (e *ApplyKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApplyKind(s)
	case string:
		*e = ApplyKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ApplyKind: %T", src)
	}
	return nil
}

type NullApplyKind struct {
	ApplyKind ApplyKind `json:"apply_kind"`
	Valid     bool      `json:"valid"` // Valid is true if ApplyKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApplyKind) Scan(value interface{}) error {
	if value == nil {
		ns.ApplyKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApplyKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApplyKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApplyKind), nil
}

type ApplyStatus string

const (
	ApplyStatusQueued     ApplyStatus = "queued"
	ApplyStatusRunning    ApplyStatus = "running"
	ApplyStatusOk         ApplyStatus = "ok"
	ApplyStatusFailed     ApplyStatus = "failed"
	ApplyStatusRolledBack ApplyStatus = "rolled_back"
)

func (e *ApplyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ApplyStatus(s)
	case string:
		*e = ApplyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ApplyStatus: %T", src)
	}
	return nil
}

type NullApplyStatus struct {
	ApplyStatus ApplyStatus `json:"apply_status"`
	Valid       bool        `json:"valid"` // Valid is true if ApplyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApplyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ApplyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ApplyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApplyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ApplyStatus), nil
}

type BackupKind string

const (
	BackupKindManual    BackupKind = "manual"
	BackupKindScheduled BackupKind = "scheduled"
)

func (e *BackupKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BackupKind(s)
	case string:
		*e = BackupKind(s)
	default:
		return fmt.Errorf("unsupported scan type for BackupKind: %T", src)
	}
	return nil
}

type NullBackupKind struct {
	BackupKind BackupKind `json:"backup_kind"`
	Valid      bool       `json:"valid"` // Valid is true if BackupKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBackupKind) Scan(value interface{}) error {
	if value == nil {
		ns.BackupKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BackupKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBackupKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BackupKind), nil
}

type KeyStatus string

const (
	KeyStatusPending KeyStatus = "pending"
	KeyStatusActive  KeyStatus = "active"
	KeyStatusRevoked KeyStatus = "revoked"
)

func (e *KeyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KeyStatus(s)
	case string:
		*e = KeyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for KeyStatus: %T", src)
	}
	return nil
}

type NullKeyStatus struct {
	KeyStatus KeyStatus `json:"key_status"`
	Valid     bool      `json:"valid"` // Valid is true if KeyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKeyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.KeyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KeyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKeyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KeyStatus), nil
}

type KeyType string

const (
	KeyTypeSHARED   KeyType = "SHARED"
	KeyTypePERSONAL KeyType = "PERSONAL"
)

func (e *KeyType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = KeyType(s)
	case string:
		*e = KeyType(s)
	default:
		return fmt.Errorf("unsupported scan type for KeyType: %T", src)
	}
	return nil
}

type NullKeyType struct {
	KeyType KeyType `json:"key_type"`
	Valid   bool    `json:"valid"` // Valid is true if KeyType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullKeyType) Scan(value interface{}) error {
	if value == nil {
		ns.KeyType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.KeyType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullKeyType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.KeyType), nil
}

type NodeEngine string

const (
	NodeEngineTproxy NodeEngine = "tproxy"
	NodeEngineTelemt NodeEngine = "telemt"
)

func (e *NodeEngine) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NodeEngine(s)
	case string:
		*e = NodeEngine(s)
	default:
		return fmt.Errorf("unsupported scan type for NodeEngine: %T", src)
	}
	return nil
}

type NullNodeEngine struct {
	NodeEngine NodeEngine `json:"node_engine"`
	Valid      bool       `json:"valid"` // Valid is true if NodeEngine is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNodeEngine) Scan(value interface{}) error {
	if value == nil {
		ns.NodeEngine, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NodeEngine.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNodeEngine) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NodeEngine), nil
}

type NodeStatus string

const (
	NodeStatusPending  NodeStatus = "pending"
	NodeStatusOnline   NodeStatus = "online"
	NodeStatusOffline  NodeStatus = "offline"
	NodeStatusDegraded NodeStatus = "degraded"
)

func (e *NodeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NodeStatus(s)
	case string:
		*e = NodeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NodeStatus: %T", src)
	}
	return nil
}

type NullNodeStatus struct {
	NodeStatus NodeStatus `json:"node_status"`
	Valid      bool       `json:"valid"` // Valid is true if NodeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNodeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NodeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NodeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNodeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NodeStatus), nil
}

type SyncState string

const (
	SyncStatePending SyncState = "pending"
	SyncStateSynced  SyncState = "synced"
	SyncStateFailed  SyncState = "failed"
)

func (e *SyncState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SyncState(s)
	case string:
		*e = SyncState(s)
	default:
		return fmt.Errorf("unsupported scan type for SyncState: %T", src)
	}
	return nil
}

type NullSyncState struct {
	SyncState SyncState `json:"sync_state"`
	Valid     bool      `json:"valid"` // Valid is true if SyncState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSyncState) Scan(value interface{}) error {
	if value == nil {
		ns.SyncState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SyncState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSyncState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SyncState), nil
}

type AccessKey struct {
	ID           uuid.UUID     `json:"id"`
	Label        string        `json:"label"`
	Type         KeyType       `json:"type"`
	OwnerLabel   string        `json:"owner_label"`
	SecretEnc    []byte        `json:"secret_enc"`
	Status       KeyStatus     `json:"status"`
	CarrierMode  string        `json:"carrier_mode"`
	Limits       []byte        `json:"limits"`
	ExpiresAt    *time.Time    `json:"expires_at"`
	RevokedAt    *time.Time    `json:"revoked_at"`
	Note         string        `json:"note"`
	CreatedBy    uuid.NullUUID `json:"created_by"`
	CreatedAt    time.Time     `json:"created_at"`
	TelemtLimits []byte        `json:"telemt_limits"`
}

type AdminUser struct {
	ID             uuid.UUID  `json:"id"`
	Username       string     `json:"username"`
	PasswordHash   string     `json:"password_hash"`
	Role           AdminRole  `json:"role"`
	TotpSecretEnc  []byte     `json:"totp_secret_enc"`
	TotpEnabled    bool       `json:"totp_enabled"`
	FailedLogins   int32      `json:"failed_logins"`
	LockedUntil    *time.Time `json:"locked_until"`
	CreatedAt      time.Time  `json:"created_at"`
	TotpPendingEnc []byte     `json:"totp_pending_enc"`
}

type Alert struct {
	ID         int64         `json:"id"`
	NodeID     uuid.NullUUID `json:"node_id"`
	Kind       string        `json:"kind"`
	Message    string        `json:"message"`
	CreatedAt  time.Time     `json:"created_at"`
	ResolvedAt *time.Time    `json:"resolved_at"`
}

type ApplyJob struct {
	ID         uuid.UUID   `json:"id"`
	NodeID     uuid.UUID   `json:"node_id"`
	Status     ApplyStatus `json:"status"`
	Kind       ApplyKind   `json:"kind"`
	StartedAt  *time.Time  `json:"started_at"`
	FinishedAt *time.Time  `json:"finished_at"`
	Error      string      `json:"error"`
	Log        string      `json:"log"`
	CreatedAt  time.Time   `json:"created_at"`
}

type AuditLog struct {
	ID          int64         `json:"id"`
	AdminUserID uuid.NullUUID `json:"admin_user_id"`
	Action      string        `json:"action"`
	TargetType  string        `json:"target_type"`
	TargetID    string        `json:"target_id"`
	Meta        []byte        `json:"meta"`
	Ip          string        `json:"ip"`
	CreatedAt   time.Time     `json:"created_at"`
}

type Backup struct {
	ID        uuid.UUID  `json:"id"`
	Path      string     `json:"path"`
	Size      int64      `json:"size"`
	Kind      BackupKind `json:"kind"`
	CreatedAt time.Time  `json:"created_at"`
}

type BrandingProfile struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	IsActive     bool      `json:"is_active"`
	PanelName    string    `json:"panel_name"`
	LogoPath     string    `json:"logo_path"`
	FaviconPath  string    `json:"favicon_path"`
	PrimaryColor string    `json:"primary_color"`
	AccentColor  string    `json:"accent_color"`
	ThemeDefault string    `json:"theme_default"`
	LoginBgPath  string    `json:"login_bg_path"`
	LoginText    string    `json:"login_text"`
	SupportLink  string    `json:"support_link"`
	FooterText   string    `json:"footer_text"`
	CustomCss    string    `json:"custom_css"`
	UpdatedAt    time.Time `json:"updated_at"`
	LogoDarkPath string    `json:"logo_dark_path"`
}

type KeyBinding struct {
	AccessKeyID uuid.UUID `json:"access_key_id"`
	NodeID      uuid.UUID `json:"node_id"`
	ProfileID   uuid.UUID `json:"profile_id"`
}

type KeyStatsSnapshot struct {
	ID             uuid.UUID `json:"id"`
	AccessKeyID    uuid.UUID `json:"access_key_id"`
	NodeID         uuid.UUID `json:"node_id"`
	TakenAt        time.Time `json:"taken_at"`
	Connections    int32     `json:"connections"`
	TotalOctets    int64     `json:"total_octets"`
	QuotaUsedBytes int64     `json:"quota_used_bytes"`
	ActiveIps      int32     `json:"active_ips"`
}

type Node struct {
	ID                  uuid.UUID  `json:"id"`
	Name                string     `json:"name"`
	Hostname            string     `json:"hostname"`
	PublicIp            string     `json:"public_ip"`
	AcmeEmail           string     `json:"acme_email"`
	Status              NodeStatus `json:"status"`
	AgentTokenHash      *string    `json:"agent_token_hash"`
	InstallTokenHash    *string    `json:"install_token_hash"`
	InstallTokenExpires *time.Time `json:"install_token_expires"`
	TproxyVersion       string     `json:"tproxy_version"`
	AgentVersion        string     `json:"agent_version"`
	MaxProfiles         int32      `json:"max_profiles"`
	Dirty               bool       `json:"dirty"`
	LastSeenAt          *time.Time `json:"last_seen_at"`
	LastApplyAt         *time.Time `json:"last_apply_at"`
	LastHealth          []byte     `json:"last_health"`
	CreatedAt           time.Time  `json:"created_at"`
	DirtySeq            int64      `json:"dirty_seq"`
	LastCheck           []byte     `json:"last_check"`
	Engine              NodeEngine `json:"engine"`
	TlsDomain           string     `json:"tls_domain"`
	ClassicPort         int32      `json:"classic_port"`
	TelemtVersion       string     `json:"telemt_version"`
}

type NodeSite struct {
	NodeID       uuid.UUID     `json:"node_id"`
	TemplateID   uuid.NullUUID `json:"template_id"`
	Bundle       []byte        `json:"bundle"`
	BundleHash   string        `json:"bundle_hash"`
	DeployedHash *string       `json:"deployed_hash"`
	UpdatedAt    time.Time     `json:"updated_at"`
}

type NodeStatsSnapshot struct {
	ID              int64     `json:"id"`
	NodeID          uuid.UUID `json:"node_id"`
	TakenAt         time.Time `json:"taken_at"`
	SessionsLive    int32     `json:"sessions_live"`
	StreamsLive     int32     `json:"streams_live"`
	BytesUp         int64     `json:"bytes_up"`
	BytesDown       int64     `json:"bytes_down"`
	SessionsCreated int64     `json:"sessions_created"`
	LimitHits       int64     `json:"limit_hits"`
	MtproxyRaw      []byte    `json:"mtproxy_raw"`
	RelayRaw        string    `json:"relay_raw"`
	CpuPercent      float32   `json:"cpu_percent"`
	MemUsedPercent  float32   `json:"mem_used_percent"`
	DiskUsedPercent float32   `json:"disk_used_percent"`
	DcLatency       []byte    `json:"dc_latency"`
}

type Profile struct {
	ID          uuid.UUID     `json:"id"`
	NodeID      uuid.UUID     `json:"node_id"`
	AccessKeyID uuid.NullUUID `json:"access_key_id"`
	Name        string        `json:"name"`
	SecretEnc   []byte        `json:"secret_enc"`
	Backend     string        `json:"backend"`
	CarrierMode string        `json:"carrier_mode"`
	Limits      []byte        `json:"limits"`
	SyncState   SyncState     `json:"sync_state"`
	CreatedAt   time.Time     `json:"created_at"`
}

type RecoveryCode struct {
	ID          uuid.UUID  `json:"id"`
	AdminUserID uuid.UUID  `json:"admin_user_id"`
	CodeHash    string     `json:"code_hash"`
	UsedAt      *time.Time `json:"used_at"`
}

type Session struct {
	ID          string    `json:"id"`
	AdminUserID uuid.UUID `json:"admin_user_id"`
	CreatedAt   time.Time `json:"created_at"`
	ExpiresAt   time.Time `json:"expires_at"`
	Ip          string    `json:"ip"`
	UserAgent   string    `json:"user_agent"`
}

type Setting struct {
	Key   string `json:"key"`
	Value []byte `json:"value"`
}

type SiteTemplate struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Html      string    `json:"html"`
	Assets    []byte    `json:"assets"`
	IsPreset  bool      `json:"is_preset"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type SubscriptionToken struct {
	TokenHash   string     `json:"token_hash"`
	AccessKeyID uuid.UUID  `json:"access_key_id"`
	CreatedAt   time.Time  `json:"created_at"`
	RevokedAt   *time.Time `json:"revoked_at"`
}
