// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countNodesByStatus = `-- name: CountNodesByStatus :many
SELECT status, count(*) AS n FROM nodes GROUP BY status
`

type CountNodesByStatusRow struct {
	Status NodeStatus `json:"status"`
	N      int64      `json:"n"`
}

func (q *Queries) CountNodesByStatus(ctx context.Context) ([]CountNodesByStatusRow, error) {
	rows, err := q.db.Query(ctx, countNodesByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountNodesByStatusRow{}
	for rows.Next() {
		var i CountNodesByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (name, hostname, public_ip, acme_email, install_token_hash, install_token_expires, engine, tls_domain, classic_port)
VALUES ($1, $2, $3, $4, $5, $6,
  COALESCE($7::node_engine, 'telemt'),
  COALESCE($8::text, ''),
  COALESCE($9::int, 8443))
RETURNING id, name, hostname, public_ip, acme_email, status, agent_token_hash, install_token_hash, install_token_expires, tproxy_version, agent_version, max_profiles, dirty, last_seen_at, last_apply_at, last_health, created_at, dirty_seq, last_check, engine, tls_domain, classic_port, telemt_version, ad_tag
`

type CreateNodeParams struct {
	Name                string         `json:"name"`
	Hostname            string         `json:"hostname"`
	PublicIp            string         `json:"public_ip"`
	AcmeEmail           string         `json:"acme_email"`
	InstallTokenHash    *string        `json:"install_token_hash"`
	InstallTokenExpires *time.Time     `json:"install_token_expires"`
	Engine              NullNodeEngine `json:"engine"`
	TlsDomain           *string        `json:"tls_domain"`
	ClassicPort         pgtype.Int4    `json:"classic_port"`
}

// CreateNode takes the engine and its Fake-TLS settings as nullable arguments so
// that a caller which does not care about them (tests, fixtures) still gets the
// column defaults rather than an invalid enum value or a zero port.
func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.Name,
		arg.Hostname,
		arg.PublicIp,
		arg.AcmeEmail,
		arg.InstallTokenHash,
		arg.InstallTokenExpires,
		arg.Engine,
		arg.TlsDomain,
		arg.ClassicPort,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.PublicIp,
		&i.AcmeEmail,
		&i.Status,
		&i.AgentTokenHash,
		&i.InstallTokenHash,
		&i.InstallTokenExpires,
		&i.TproxyVersion,
		&i.AgentVersion,
		&i.MaxProfiles,
		&i.Dirty,
		&i.LastSeenAt,
		&i.LastApplyAt,
		&i.LastHealth,
		&i.CreatedAt,
		&i.DirtySeq,
		&i.LastCheck,
		&i.Engine,
		&i.TlsDomain,
		&i.ClassicPort,
		&i.TelemtVersion,
		&i.AdTag,
	)
	return i, err
}

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = $1
`

func (q *Queries) DeleteNode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNode, id)
	return err
}

const getNode = `-- name: GetNode :one
SELECT id, name, hostname, public_ip, acme_email, status, agent_token_hash, install_token_hash, install_token_expires, tproxy_version, agent_version, max_profiles, dirty, last_seen_at, last_apply_at, last_health, created_at, dirty_seq, last_check, engine, tls_domain, classic_port, telemt_version, ad_tag FROM nodes WHERE id = $1
`

func (q *Queries) GetNode(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNode, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.PublicIp,
		&i.AcmeEmail,
		&i.Status,
		&i.AgentTokenHash,
		&i.InstallTokenHash,
		&i.InstallTokenExpires,
		&i.TproxyVersion,
		&i.AgentVersion,
		&i.MaxProfiles,
		&i.Dirty,
		&i.LastSeenAt,
		&i.LastApplyAt,
		&i.LastHealth,
		&i.CreatedAt,
		&i.DirtySeq,
		&i.LastCheck,
		&i.Engine,
		&i.TlsDomain,
		&i.ClassicPort,
		&i.TelemtVersion,
		&i.AdTag,
	)
	return i, err
}

const getNodeByAgentToken = `-- name: GetNodeByAgentToken :one
SELECT id, name, hostname, public_ip, acme_email, status, agent_token_hash, install_token_hash, install_token_expires, tproxy_version, agent_version, max_profiles, dirty, last_seen_at, last_apply_at, last_health, created_at, dirty_seq, last_check, engine, tls_domain, classic_port, telemt_version, ad_tag FROM nodes WHERE agent_token_hash = $1
`

func (q *Queries) GetNodeByAgentToken(ctx context.Context, agentTokenHash *string) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByAgentToken, agentTokenHash)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.PublicIp,
		&i.AcmeEmail,
		&i.Status,
		&i.AgentTokenHash,
		&i.InstallTokenHash,
		&i.InstallTokenExpires,
		&i.TproxyVersion,
		&i.AgentVersion,
		&i.MaxProfiles,
		&i.Dirty,
		&i.LastSeenAt,
		&i.LastApplyAt,
		&i.LastHealth,
		&i.CreatedAt,
		&i.DirtySeq,
		&i.LastCheck,
		&i.Engine,
		&i.TlsDomain,
		&i.ClassicPort,
		&i.TelemtVersion,
		&i.AdTag,
	)
	return i, err
}

const getNodeByHostname = `-- name: GetNodeByHostname :one
SELECT id, name, hostname, public_ip, acme_email, status, agent_token_hash, install_token_hash, install_token_expires, tproxy_version, agent_version, max_profiles, dirty, last_seen_at, last_apply_at, last_health, created_at, dirty_seq, last_check, engine, tls_domain, classic_port, telemt_version, ad_tag FROM nodes WHERE hostname = $1
`

func (q *Queries) GetNodeByHostname(ctx context.Context, hostname string) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByHostname, hostname)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.PublicIp,
		&i.AcmeEmail,
		&i.Status,
		&i.AgentTokenHash,
		&i.InstallTokenHash,
		&i.InstallTokenExpires,
		&i.TproxyVersion,
		&i.AgentVersion,
		&i.MaxProfiles,
		&i.Dirty,
		&i.LastSeenAt,
		&i.LastApplyAt,
		&i.LastHealth,
		&i.CreatedAt,
		&i.DirtySeq,
		&i.LastCheck,
		&i.Engine,
		&i.TlsDomain,
		&i.ClassicPort,
		&i.TelemtVersion,
		&i.AdTag,
	)
	return i, err
}

const getNodeByInstallToken = `-- name: GetNodeByInstallToken :one
SELECT id, name, hostname, public_ip, acme_email, status, agent_token_hash, install_token_hash, install_token_expires, tproxy_version, agent_version, max_profiles, dirty, last_seen_at, last_apply_at, last_health, created_at, dirty_seq, last_check, engine, tls_domain, classic_port, telemt_version, ad_tag FROM nodes WHERE install_token_hash = $1 AND install_token_expires > now()
`

func (q *Queries) GetNodeByInstallToken(ctx context.Context, installTokenHash *string) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByInstallToken, installTokenHash)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.PublicIp,
		&i.AcmeEmail,
		&i.Status,
		&i.AgentTokenHash,
		&i.InstallTokenHash,
		&i.InstallTokenExpires,
		&i.TproxyVersion,
		&i.AgentVersion,
		&i.MaxProfiles,
		&i.Dirty,
		&i.LastSeenAt,
		&i.LastApplyAt,
		&i.LastHealth,
		&i.CreatedAt,
		&i.DirtySeq,
		&i.LastCheck,
		&i.Engine,
		&i.TlsDomain,
		&i.ClassicPort,
		&i.TelemtVersion,
		&i.AdTag,
	)
	return i, err
}

const listDirtyNodesAny = `-- name: ListDirtyNodesAny :many
SELECT id, name, hostname, public_ip, acme_email, status, agent_token_hash, install_token_hash, install_token_expires, tproxy_version, agent_version, max_profiles, dirty, last_seen_at, last_apply_at, last_health, created_at, dirty_seq, last_check, engine, tls_domain, classic_port, telemt_version, ad_tag FROM nodes WHERE dirty = true
`

// ListDirtyNodesAny returns every dirty node regardless of status: the apply
// sweep decides reachability from the live driver, so a node marked offline by a
// stale heartbeat while its gRPC stream is up is still picked up.
func (q *Queries) ListDirtyNodesAny(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listDirtyNodesAny)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.PublicIp,
			&i.AcmeEmail,
			&i.Status,
			&i.AgentTokenHash,
			&i.InstallTokenHash,
			&i.InstallTokenExpires,
			&i.TproxyVersion,
			&i.AgentVersion,
			&i.MaxProfiles,
			&i.Dirty,
			&i.LastSeenAt,
			&i.LastApplyAt,
			&i.LastHealth,
			&i.CreatedAt,
			&i.DirtySeq,
			&i.LastCheck,
			&i.Engine,
			&i.TlsDomain,
			&i.ClassicPort,
			&i.TelemtVersion,
			&i.AdTag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodes = `-- name: ListNodes :many
SELECT id, name, hostname, public_ip, acme_email, status, agent_token_hash, install_token_hash, install_token_expires, tproxy_version, agent_version, max_profiles, dirty, last_seen_at, last_apply_at, last_health, created_at, dirty_seq, last_check, engine, tls_domain, classic_port, telemt_version, ad_tag FROM nodes ORDER BY created_at
`

func (q *Queries) ListNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.Query(ctx, listNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Node{}
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Hostname,
			&i.PublicIp,
			&i.AcmeEmail,
			&i.Status,
			&i.AgentTokenHash,
			&i.InstallTokenHash,
			&i.InstallTokenExpires,
			&i.TproxyVersion,
			&i.AgentVersion,
			&i.MaxProfiles,
			&i.Dirty,
			&i.LastSeenAt,
			&i.LastApplyAt,
			&i.LastHealth,
			&i.CreatedAt,
			&i.DirtySeq,
			&i.LastCheck,
			&i.Engine,
			&i.TlsDomain,
			&i.ClassicPort,
			&i.TelemtVersion,
			&i.AdTag,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesWithCounts = `-- name: ListNodesWithCounts :many
SELECT n.id, n.name, n.hostname, n.public_ip, n.acme_email, n.status, n.agent_token_hash, n.install_token_hash, n.install_token_expires, n.tproxy_version, n.agent_version, n.max_profiles, n.dirty, n.last_seen_at, n.last_apply_at, n.last_health, n.created_at, n.dirty_seq, n.last_check, n.engine, n.tls_domain, n.classic_port, n.telemt_version, n.ad_tag, (SELECT count(*) FROM profiles p WHERE p.node_id = n.id) AS profile_count
FROM nodes n ORDER BY n.created_at
`

type ListNodesWithCountsRow struct {
	Node         Node  `json:"node"`
	ProfileCount int64 `json:"profile_count"`
}

// ListNodesWithCounts is ListNodes plus each node's profile count, so the list
// endpoint no longer issues one CountNodeProfiles round trip per node.
func (q *Queries) ListNodesWithCounts(ctx context.Context) ([]ListNodesWithCountsRow, error) {
	rows, err := q.db.Query(ctx, listNodesWithCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodesWithCountsRow{}
	for rows.Next() {
		var i ListNodesWithCountsRow
		if err := rows.Scan(
			&i.Node.ID,
			&i.Node.Name,
			&i.Node.Hostname,
			&i.Node.PublicIp,
			&i.Node.AcmeEmail,
			&i.Node.Status,
			&i.Node.AgentTokenHash,
			&i.Node.InstallTokenHash,
			&i.Node.InstallTokenExpires,
			&i.Node.TproxyVersion,
			&i.Node.AgentVersion,
			&i.Node.MaxProfiles,
			&i.Node.Dirty,
			&i.Node.LastSeenAt,
			&i.Node.LastApplyAt,
			&i.Node.LastHealth,
			&i.Node.CreatedAt,
			&i.Node.DirtySeq,
			&i.Node.LastCheck,
			&i.Node.Engine,
			&i.Node.TlsDomain,
			&i.Node.ClassicPort,
			&i.Node.TelemtVersion,
			&i.Node.AdTag,
			&i.ProfileCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleNodesOffline = `-- name: MarkStaleNodesOffline :many
UPDATE nodes SET status = 'offline' WHERE status IN ('online','degraded') AND last_seen_at < $1 RETURNING id
`

func (q *Queries) MarkStaleNodesOffline(ctx context.Context, lastSeenAt *time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, markStaleNodesOffline, lastSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerNode = `-- name: RegisterNode :exec
UPDATE nodes SET agent_token_hash = $2, install_token_hash = NULL, install_token_expires = NULL,
  tproxy_version = $3, agent_version = $4, status = 'offline' WHERE id = $1
`

type RegisterNodeParams struct {
	ID             uuid.UUID `json:"id"`
	AgentTokenHash *string   `json:"agent_token_hash"`
	TproxyVersion  string    `json:"tproxy_version"`
	AgentVersion   string    `json:"agent_version"`
}

func (q *Queries) RegisterNode(ctx context.Context, arg RegisterNodeParams) error {
	_, err := q.db.Exec(ctx, registerNode,
		arg.ID,
		arg.AgentTokenHash,
		arg.TproxyVersion,
		arg.AgentVersion,
	)
	return err
}

const setNodeApplied = `-- name: SetNodeApplied :exec
UPDATE nodes SET dirty = false, last_apply_at = now()
WHERE id = $1 AND dirty_seq = $2
`

type SetNodeAppliedParams struct {
	ID       uuid.UUID `json:"id"`
	DirtySeq int64     `json:"dirty_seq"`
}

func (q *Queries) SetNodeApplied(ctx context.Context, arg SetNodeAppliedParams) error {
	_, err := q.db.Exec(ctx, setNodeApplied, arg.ID, arg.DirtySeq)
	return err
}

const setNodeDirty = `-- name: SetNodeDirty :exec
UPDATE nodes SET dirty = $1,
  dirty_seq = CASE WHEN $1::boolean THEN dirty_seq + 1 ELSE dirty_seq END
WHERE id = $2
`

type SetNodeDirtyParams struct {
	Dirty bool      `json:"dirty"`
	ID    uuid.UUID `json:"id"`
}

// SetNodeDirty bumps dirty_seq whenever it marks a node dirty. An in-flight apply carries
// the dirty_seq it snapshotted, so any mutation that lands while it runs makes the apply's
// SetNodeApplied a no-op and the node stays dirty for the next sweep.
func (q *Queries) SetNodeDirty(ctx context.Context, arg SetNodeDirtyParams) error {
	_, err := q.db.Exec(ctx, setNodeDirty, arg.Dirty, arg.ID)
	return err
}

const setNodeHeartbeat = `-- name: SetNodeHeartbeat :exec
UPDATE nodes SET status = $2, last_seen_at = now(), last_health = $3,
  tproxy_version = COALESCE(NULLIF($4::text, ''), tproxy_version),
  telemt_version = CASE WHEN engine = 'telemt'
    THEN COALESCE(NULLIF($5::text, ''), telemt_version)
    ELSE telemt_version END
WHERE id = $1
`

type SetNodeHeartbeatParams struct {
	ID            uuid.UUID  `json:"id"`
	Status        NodeStatus `json:"status"`
	LastHealth    []byte     `json:"last_health"`
	TproxyVersion string     `json:"tproxy_version"`
	TelemtVersion string     `json:"telemt_version"`
}

// SetNodeHeartbeat carries the versions too: a telemt node whose control API was down at
// hello time reports its version on the first heartbeat that reaches it, and there is no
// other moment at which the panel would learn it.
func (q *Queries) SetNodeHeartbeat(ctx context.Context, arg SetNodeHeartbeatParams) error {
	_, err := q.db.Exec(ctx, setNodeHeartbeat,
		arg.ID,
		arg.Status,
		arg.LastHealth,
		arg.TproxyVersion,
		arg.TelemtVersion,
	)
	return err
}

const setNodeInstallToken = `-- name: SetNodeInstallToken :exec
UPDATE nodes SET install_token_hash = $2, install_token_expires = $3 WHERE id = $1
`

type SetNodeInstallTokenParams struct {
	ID                  uuid.UUID  `json:"id"`
	InstallTokenHash    *string    `json:"install_token_hash"`
	InstallTokenExpires *time.Time `json:"install_token_expires"`
}

func (q *Queries) SetNodeInstallToken(ctx context.Context, arg SetNodeInstallTokenParams) error {
	_, err := q.db.Exec(ctx, setNodeInstallToken, arg.ID, arg.InstallTokenHash, arg.InstallTokenExpires)
	return err
}

const setNodeLastCheck = `-- name: SetNodeLastCheck :exec
UPDATE nodes SET last_check = $2 WHERE id = $1
`

type SetNodeLastCheckParams struct {
	ID        uuid.UUID `json:"id"`
	LastCheck []byte    `json:"last_check"`
}

func (q *Queries) SetNodeLastCheck(ctx context.Context, arg SetNodeLastCheckParams) error {
	_, err := q.db.Exec(ctx, setNodeLastCheck, arg.ID, arg.LastCheck)
	return err
}

const setNodeOnline = `-- name: SetNodeOnline :exec
UPDATE nodes SET status = 'online', last_seen_at = now(),
  tproxy_version = COALESCE(NULLIF($2::text, ''), tproxy_version),
  agent_version = COALESCE(NULLIF($3::text, ''), agent_version),
  telemt_version = CASE WHEN engine = 'telemt'
    THEN COALESCE(NULLIF($4::text, ''), telemt_version)
    ELSE telemt_version END
WHERE id = $1
`

type SetNodeOnlineParams struct {
	ID            uuid.UUID `json:"id"`
	TproxyVersion string    `json:"tproxy_version"`
	AgentVersion  string    `json:"agent_version"`
	TelemtVersion string    `json:"telemt_version"`
}

// SetNodeOnline records the versions the agent reported. An empty string means "the agent
// could not read it" (telemt's version comes from its control API, which may be briefly
// unreachable) and must never overwrite a known version with a blank. telemt_version is only
// written for telemt nodes, so a tproxy node cannot end up labelled with one.
func (q *Queries) SetNodeOnline(ctx context.Context, arg SetNodeOnlineParams) error {
	_, err := q.db.Exec(ctx, setNodeOnline,
		arg.ID,
		arg.TproxyVersion,
		arg.AgentVersion,
		arg.TelemtVersion,
	)
	return err
}

const setNodePublicIP = `-- name: SetNodePublicIP :exec
UPDATE nodes SET public_ip = $2 WHERE id = $1
`

type SetNodePublicIPParams struct {
	ID       uuid.UUID `json:"id"`
	PublicIp string    `json:"public_ip"`
}

// SetNodePublicIP fills in the address the node reported at registration. telemt
// needs it for web.vhosts.public_addr, and the install script is the only place
// that reliably knows it.
func (q *Queries) SetNodePublicIP(ctx context.Context, arg SetNodePublicIPParams) error {
	_, err := q.db.Exec(ctx, setNodePublicIP, arg.ID, arg.PublicIp)
	return err
}

const setNodeStatus = `-- name: SetNodeStatus :exec
UPDATE nodes SET status = $2 WHERE id = $1
`

type SetNodeStatusParams struct {
	ID     uuid.UUID  `json:"id"`
	Status NodeStatus `json:"status"`
}

func (q *Queries) SetNodeStatus(ctx context.Context, arg SetNodeStatusParams) error {
	_, err := q.db.Exec(ctx, setNodeStatus, arg.ID, arg.Status)
	return err
}

const setNodeTelemtVersion = `-- name: SetNodeTelemtVersion :exec
UPDATE nodes SET telemt_version = $2 WHERE id = $1
`

type SetNodeTelemtVersionParams struct {
	ID            uuid.UUID `json:"id"`
	TelemtVersion string    `json:"telemt_version"`
}

func (q *Queries) SetNodeTelemtVersion(ctx context.Context, arg SetNodeTelemtVersionParams) error {
	_, err := q.db.Exec(ctx, setNodeTelemtVersion, arg.ID, arg.TelemtVersion)
	return err
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes SET name = $2, public_ip = $3, max_profiles = $4, acme_email = $5,
  tls_domain = COALESCE($6::text, tls_domain),
  classic_port = COALESCE($7::int, classic_port),
  ad_tag = COALESCE($8::text, ad_tag)
WHERE id = $1 RETURNING id, name, hostname, public_ip, acme_email, status, agent_token_hash, install_token_hash, install_token_expires, tproxy_version, agent_version, max_profiles, dirty, last_seen_at, last_apply_at, last_health, created_at, dirty_seq, last_check, engine, tls_domain, classic_port, telemt_version, ad_tag
`

type UpdateNodeParams struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	PublicIp    string      `json:"public_ip"`
	MaxProfiles int32       `json:"max_profiles"`
	AcmeEmail   string      `json:"acme_email"`
	TlsDomain   *string     `json:"tls_domain"`
	ClassicPort pgtype.Int4 `json:"classic_port"`
	AdTag       *string     `json:"ad_tag"`
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, updateNode,
		arg.ID,
		arg.Name,
		arg.PublicIp,
		arg.MaxProfiles,
		arg.AcmeEmail,
		arg.TlsDomain,
		arg.ClassicPort,
		arg.AdTag,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Hostname,
		&i.PublicIp,
		&i.AcmeEmail,
		&i.Status,
		&i.AgentTokenHash,
		&i.InstallTokenHash,
		&i.InstallTokenExpires,
		&i.TproxyVersion,
		&i.AgentVersion,
		&i.MaxProfiles,
		&i.Dirty,
		&i.LastSeenAt,
		&i.LastApplyAt,
		&i.LastHealth,
		&i.CreatedAt,
		&i.DirtySeq,
		&i.LastCheck,
		&i.Engine,
		&i.TlsDomain,
		&i.ClassicPort,
		&i.TelemtVersion,
		&i.AdTag,
	)
	return i, err
}
