// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countNodeProfiles = `-- name: CountNodeProfiles :one
SELECT count(*) FROM profiles WHERE node_id = $1
`

func (q *Queries) CountNodeProfiles(ctx context.Context, nodeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNodeProfiles, nodeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profiles (node_id, access_key_id, name, secret_enc, backend, carrier_mode, limits)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, node_id, access_key_id, name, secret_enc, backend, carrier_mode, limits, sync_state, created_at
`

type CreateProfileParams struct {
	NodeID      uuid.UUID     `json:"node_id"`
	AccessKeyID uuid.NullUUID `json:"access_key_id"`
	Name        string        `json:"name"`
	SecretEnc   []byte        `json:"secret_enc"`
	Backend     string        `json:"backend"`
	CarrierMode string        `json:"carrier_mode"`
	Limits      []byte        `json:"limits"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.NodeID,
		arg.AccessKeyID,
		arg.Name,
		arg.SecretEnc,
		arg.Backend,
		arg.CarrierMode,
		arg.Limits,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.AccessKeyID,
		&i.Name,
		&i.SecretEnc,
		&i.Backend,
		&i.CarrierMode,
		&i.Limits,
		&i.SyncState,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProfile = `-- name: DeleteProfile :exec
DELETE FROM profiles WHERE id = $1
`

func (q *Queries) DeleteProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProfile, id)
	return err
}

const deleteProfilesByKey = `-- name: DeleteProfilesByKey :exec
DELETE FROM profiles WHERE access_key_id = $1
`

func (q *Queries) DeleteProfilesByKey(ctx context.Context, accessKeyID uuid.NullUUID) error {
	_, err := q.db.Exec(ctx, deleteProfilesByKey, accessKeyID)
	return err
}

const listNodeProfiles = `-- name: ListNodeProfiles :many
SELECT id, node_id, access_key_id, name, secret_enc, backend, carrier_mode, limits, sync_state, created_at FROM profiles WHERE node_id = $1 ORDER BY created_at
`

func (q *Queries) ListNodeProfiles(ctx context.Context, nodeID uuid.UUID) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listNodeProfiles, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.AccessKeyID,
			&i.Name,
			&i.SecretEnc,
			&i.Backend,
			&i.CarrierMode,
			&i.Limits,
			&i.SyncState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeProfilesWithKey = `-- name: ListNodeProfilesWithKey :many
SELECT p.id, p.node_id, p.access_key_id, p.name, p.secret_enc, p.backend, p.carrier_mode, p.limits, p.sync_state, p.created_at, k.telemt_limits AS key_telemt_limits, k.expires_at AS key_expires_at,
       k.status AS key_status, k.label AS key_label
FROM profiles p LEFT JOIN access_keys k ON k.id = p.access_key_id
WHERE p.node_id = $1 ORDER BY p.created_at
`

type ListNodeProfilesWithKeyRow struct {
	ID              uuid.UUID     `json:"id"`
	NodeID          uuid.UUID     `json:"node_id"`
	AccessKeyID     uuid.NullUUID `json:"access_key_id"`
	Name            string        `json:"name"`
	SecretEnc       []byte        `json:"secret_enc"`
	Backend         string        `json:"backend"`
	CarrierMode     string        `json:"carrier_mode"`
	Limits          []byte        `json:"limits"`
	SyncState       SyncState     `json:"sync_state"`
	CreatedAt       time.Time     `json:"created_at"`
	KeyTelemtLimits []byte        `json:"key_telemt_limits"`
	KeyExpiresAt    *time.Time    `json:"key_expires_at"`
	KeyStatus       NullKeyStatus `json:"key_status"`
	KeyLabel        *string       `json:"key_label"`
}

// ListNodeProfilesWithKey is ListNodeProfiles plus the columns of the bound access key that
// the telemt engine has to push to the node - the per-user limits, the expiry, and the status
// (a revoked key must be served as a disabled user even in the window before its profile row
// is deleted) - and the key's label, which the node's Profiles tab prints so a row can be
// read as a person rather than as a uuid. The default profile has no key, so the joined
// columns are NULL there and the caller reads them as "no limits, never expires, enabled".
func (q *Queries) ListNodeProfilesWithKey(ctx context.Context, nodeID uuid.UUID) ([]ListNodeProfilesWithKeyRow, error) {
	rows, err := q.db.Query(ctx, listNodeProfilesWithKey, nodeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNodeProfilesWithKeyRow{}
	for rows.Next() {
		var i ListNodeProfilesWithKeyRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.AccessKeyID,
			&i.Name,
			&i.SecretEnc,
			&i.Backend,
			&i.CarrierMode,
			&i.Limits,
			&i.SyncState,
			&i.CreatedAt,
			&i.KeyTelemtLimits,
			&i.KeyExpiresAt,
			&i.KeyStatus,
			&i.KeyLabel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfilesByKey = `-- name: ListProfilesByKey :many
SELECT id, node_id, access_key_id, name, secret_enc, backend, carrier_mode, limits, sync_state, created_at FROM profiles WHERE access_key_id = $1
`

func (q *Queries) ListProfilesByKey(ctx context.Context, accessKeyID uuid.NullUUID) ([]Profile, error) {
	rows, err := q.db.Query(ctx, listProfilesByKey, accessKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Profile{}
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.AccessKeyID,
			&i.Name,
			&i.SecretEnc,
			&i.Backend,
			&i.CarrierMode,
			&i.Limits,
			&i.SyncState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNodeProfilesSync = `-- name: SetNodeProfilesSync :exec
UPDATE profiles SET sync_state = $2 WHERE node_id = $1
`

type SetNodeProfilesSyncParams struct {
	NodeID    uuid.UUID `json:"node_id"`
	SyncState SyncState `json:"sync_state"`
}

func (q *Queries) SetNodeProfilesSync(ctx context.Context, arg SetNodeProfilesSyncParams) error {
	_, err := q.db.Exec(ctx, setNodeProfilesSync, arg.NodeID, arg.SyncState)
	return err
}

const setProfilesSyncByIDs = `-- name: SetProfilesSyncByIDs :exec
UPDATE profiles SET sync_state = $1
WHERE id = ANY($2::uuid[])
`

type SetProfilesSyncByIDsParams struct {
	SyncState SyncState   `json:"sync_state"`
	Ids       []uuid.UUID `json:"ids"`
}

// SetProfilesSyncByIDs marks only the profiles an apply actually pushed. Profiles created
// after the apply's snapshot keep sync_state = 'pending' so ActivatePendingKeysForNode
// correctly leaves their keys pending.
func (q *Queries) SetProfilesSyncByIDs(ctx context.Context, arg SetProfilesSyncByIDsParams) error {
	_, err := q.db.Exec(ctx, setProfilesSyncByIDs, arg.SyncState, arg.Ids)
	return err
}

const updateProfileSecret = `-- name: UpdateProfileSecret :exec
UPDATE profiles SET secret_enc = $2, sync_state = 'pending' WHERE id = $1
`

type UpdateProfileSecretParams struct {
	ID        uuid.UUID `json:"id"`
	SecretEnc []byte    `json:"secret_enc"`
}

func (q *Queries) UpdateProfileSecret(ctx context.Context, arg UpdateProfileSecretParams) error {
	_, err := q.db.Exec(ctx, updateProfileSecret, arg.ID, arg.SecretEnc)
	return err
}

const updateProfileSettings = `-- name: UpdateProfileSettings :exec
UPDATE profiles SET carrier_mode = $2, limits = $3, sync_state = 'pending' WHERE id = $1
`

type UpdateProfileSettingsParams struct {
	ID          uuid.UUID `json:"id"`
	CarrierMode string    `json:"carrier_mode"`
	Limits      []byte    `json:"limits"`
}

func (q *Queries) UpdateProfileSettings(ctx context.Context, arg UpdateProfileSettingsParams) error {
	_, err := q.db.Exec(ctx, updateProfileSettings, arg.ID, arg.CarrierMode, arg.Limits)
	return err
}
