// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, admin_user_id, expires_at, ip, user_agent) VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	ID          string    `json:"id"`
	AdminUserID uuid.UUID `json:"admin_user_id"`
	ExpiresAt   time.Time `json:"expires_at"`
	Ip          string    `json:"ip"`
	UserAgent   string    `json:"user_agent"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.AdminUserID,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE admin_user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, adminUserID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, adminUserID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT s.id, s.admin_user_id, s.created_at, s.expires_at, s.ip, s.user_agent, u.username, u.role FROM sessions s JOIN admin_users u ON u.id = s.admin_user_id
WHERE s.id = $1 AND s.expires_at > now()
`

type GetSessionRow struct {
	ID          string    `json:"id"`
	AdminUserID uuid.UUID `json:"admin_user_id"`
	CreatedAt   time.Time `json:"created_at"`
	ExpiresAt   time.Time `json:"expires_at"`
	Ip          string    `json:"ip"`
	UserAgent   string    `json:"user_agent"`
	Username    string    `json:"username"`
	Role        AdminRole `json:"role"`
}

func (q *Queries) GetSession(ctx context.Context, id string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Ip,
		&i.UserAgent,
		&i.Username,
		&i.Role,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET expires_at = $2 WHERE id = $1
`

type TouchSessionParams struct {
	ID        string    `json:"id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.ExpiresAt)
	return err
}
