// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sites.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSiteTemplate = `-- name: CreateSiteTemplate :one
INSERT INTO site_templates (name, html, assets, is_preset) VALUES ($1, $2, $3, $4) RETURNING id, name, html, assets, is_preset, created_at, updated_at
`

type CreateSiteTemplateParams struct {
	Name     string `json:"name"`
	Html     string `json:"html"`
	Assets   []byte `json:"assets"`
	IsPreset bool   `json:"is_preset"`
}

func (q *Queries) CreateSiteTemplate(ctx context.Context, arg CreateSiteTemplateParams) (SiteTemplate, error) {
	row := q.db.QueryRow(ctx, createSiteTemplate,
		arg.Name,
		arg.Html,
		arg.Assets,
		arg.IsPreset,
	)
	var i SiteTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Html,
		&i.Assets,
		&i.IsPreset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRetiredPresets = `-- name: DeleteRetiredPresets :execrows
DELETE FROM site_templates WHERE is_preset = true AND name <> ALL($1::text[])
`

// DeleteRetiredPresets removes built-in templates the panel no longer ships. A node that had
// one keeps its deployed bundle: node_sites.template_id is ON DELETE SET NULL and the bundle
// is the node's own copy. Custom templates are never touched.
func (q *Queries) DeleteRetiredPresets(ctx context.Context, dollar_1 []string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRetiredPresets, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSiteTemplate = `-- name: DeleteSiteTemplate :exec
DELETE FROM site_templates WHERE id = $1 AND is_preset = false
`

func (q *Queries) DeleteSiteTemplate(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSiteTemplate, id)
	return err
}

const getPresetByName = `-- name: GetPresetByName :one
SELECT id, name, html, assets, is_preset, created_at, updated_at FROM site_templates WHERE is_preset = true AND name = $1
`

func (q *Queries) GetPresetByName(ctx context.Context, name string) (SiteTemplate, error) {
	row := q.db.QueryRow(ctx, getPresetByName, name)
	var i SiteTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Html,
		&i.Assets,
		&i.IsPreset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSiteTemplate = `-- name: GetSiteTemplate :one
SELECT id, name, html, assets, is_preset, created_at, updated_at FROM site_templates WHERE id = $1
`

func (q *Queries) GetSiteTemplate(ctx context.Context, id uuid.UUID) (SiteTemplate, error) {
	row := q.db.QueryRow(ctx, getSiteTemplate, id)
	var i SiteTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Html,
		&i.Assets,
		&i.IsPreset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSiteTemplates = `-- name: ListSiteTemplates :many
SELECT t.id, t.name, t.is_preset, t.created_at, t.updated_at,
 (SELECT count(*) FROM node_sites n WHERE n.template_id = t.id) AS used_by
FROM site_templates t ORDER BY t.is_preset DESC, t.name
`

type ListSiteTemplatesRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	IsPreset  bool      `json:"is_preset"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	UsedBy    int64     `json:"used_by"`
}

func (q *Queries) ListSiteTemplates(ctx context.Context) ([]ListSiteTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listSiteTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSiteTemplatesRow{}
	for rows.Next() {
		var i ListSiteTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPreset,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UsedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSiteTemplate = `-- name: UpdateSiteTemplate :one
UPDATE site_templates SET name = $2, html = $3, assets = $4, updated_at = now() WHERE id = $1 RETURNING id, name, html, assets, is_preset, created_at, updated_at
`

type UpdateSiteTemplateParams struct {
	ID     uuid.UUID `json:"id"`
	Name   string    `json:"name"`
	Html   string    `json:"html"`
	Assets []byte    `json:"assets"`
}

func (q *Queries) UpdateSiteTemplate(ctx context.Context, arg UpdateSiteTemplateParams) (SiteTemplate, error) {
	row := q.db.QueryRow(ctx, updateSiteTemplate,
		arg.ID,
		arg.Name,
		arg.Html,
		arg.Assets,
	)
	var i SiteTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Html,
		&i.Assets,
		&i.IsPreset,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertNodeSite = `-- name: UpsertNodeSite :exec
INSERT INTO node_sites (node_id, template_id, bundle, bundle_hash) VALUES ($1, $2, $3, $4)
ON CONFLICT (node_id) DO UPDATE SET template_id = EXCLUDED.template_id, bundle = EXCLUDED.bundle, bundle_hash = EXCLUDED.bundle_hash, updated_at = now()
`

type UpsertNodeSiteParams struct {
	NodeID     uuid.UUID     `json:"node_id"`
	TemplateID uuid.NullUUID `json:"template_id"`
	Bundle     []byte        `json:"bundle"`
	BundleHash string        `json:"bundle_hash"`
}

func (q *Queries) UpsertNodeSite(ctx context.Context, arg UpsertNodeSiteParams) error {
	_, err := q.db.Exec(ctx, upsertNodeSite,
		arg.NodeID,
		arg.TemplateID,
		arg.Bundle,
		arg.BundleHash,
	)
	return err
}
