// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stats.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteOldKeyStatsSnapshots = `-- name: DeleteOldKeyStatsSnapshots :execrows
DELETE FROM key_stats_snapshots s
WHERE s.id IN (
  SELECT b.id FROM key_stats_snapshots b
  WHERE b.taken_at < $1 ORDER BY b.taken_at LIMIT $2
)
`

type DeleteOldKeyStatsSnapshotsParams struct {
	Before time.Time `json:"before"`
	Batch  int32     `json:"batch"`
}

// DeleteOldKeyStatsSnapshots removes one bounded batch of expired rows and reports how many it
// deleted, so the caller can loop until the sweep is done. An unbounded DELETE over the largest
// table in the database takes a single long-running statement whose locks and WAL burst are
// felt by every other query; a batch keeps each statement short. key_stats_taken_at_idx
// (migration 00006) is what makes the inner SELECT an index scan rather than a seq scan.
func (q *Queries) DeleteOldKeyStatsSnapshots(ctx context.Context, arg DeleteOldKeyStatsSnapshotsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldKeyStatsSnapshots, arg.Before, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldSnapshots = `-- name: DeleteOldSnapshots :exec
DELETE FROM node_stats_snapshots WHERE taken_at < $1
`

func (q *Queries) DeleteOldSnapshots(ctx context.Context, takenAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldSnapshots, takenAt)
	return err
}

const insertAlert = `-- name: InsertAlert :one
INSERT INTO alerts (node_id, kind, message) VALUES ($1, $2, $3) RETURNING id, node_id, kind, message, created_at, resolved_at
`

type InsertAlertParams struct {
	NodeID  uuid.NullUUID `json:"node_id"`
	Kind    string        `json:"kind"`
	Message string        `json:"message"`
}

func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, insertAlert, arg.NodeID, arg.Kind, arg.Message)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Kind,
		&i.Message,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const insertKeyStatsSnapshot = `-- name: InsertKeyStatsSnapshot :exec
INSERT INTO key_stats_snapshots (access_key_id, node_id, connections, total_octets, quota_used_bytes, active_ips)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertKeyStatsSnapshotParams struct {
	AccessKeyID    uuid.UUID `json:"access_key_id"`
	NodeID         uuid.UUID `json:"node_id"`
	Connections    int32     `json:"connections"`
	TotalOctets    int64     `json:"total_octets"`
	QuotaUsedBytes int64     `json:"quota_used_bytes"`
	ActiveIps      int32     `json:"active_ips"`
}

// key_stats_snapshots hold per-key traffic/connection counters read from telemt
// nodes. They are written by the stats worker and read by the key drawer.
func (q *Queries) InsertKeyStatsSnapshot(ctx context.Context, arg InsertKeyStatsSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertKeyStatsSnapshot,
		arg.AccessKeyID,
		arg.NodeID,
		arg.Connections,
		arg.TotalOctets,
		arg.QuotaUsedBytes,
		arg.ActiveIps,
	)
	return err
}

const insertSnapshot = `-- name: InsertSnapshot :exec
INSERT INTO node_stats_snapshots (node_id, sessions_live, streams_live, bytes_up, bytes_down, sessions_created, limit_hits, mtproxy_raw, relay_raw,
  cpu_percent, mem_used_percent, disk_used_percent, dc_latency)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, coalesce($13::jsonb, '{}'::jsonb))
`

type InsertSnapshotParams struct {
	NodeID          uuid.UUID `json:"node_id"`
	SessionsLive    int32     `json:"sessions_live"`
	StreamsLive     int32     `json:"streams_live"`
	BytesUp         int64     `json:"bytes_up"`
	BytesDown       int64     `json:"bytes_down"`
	SessionsCreated int64     `json:"sessions_created"`
	LimitHits       int64     `json:"limit_hits"`
	MtproxyRaw      []byte    `json:"mtproxy_raw"`
	RelayRaw        string    `json:"relay_raw"`
	CpuPercent      float32   `json:"cpu_percent"`
	MemUsedPercent  float32   `json:"mem_used_percent"`
	DiskUsedPercent float32   `json:"disk_used_percent"`
	DcLatency       []byte    `json:"dc_latency"`
}

// InsertSnapshot's dc_latency is coalesced so a caller with no DC data (a tproxy node, or a
// Go nil) lands the column's '{}' rather than a NULL the NOT NULL constraint would reject.
func (q *Queries) InsertSnapshot(ctx context.Context, arg InsertSnapshotParams) error {
	_, err := q.db.Exec(ctx, insertSnapshot,
		arg.NodeID,
		arg.SessionsLive,
		arg.StreamsLive,
		arg.BytesUp,
		arg.BytesDown,
		arg.SessionsCreated,
		arg.LimitHits,
		arg.MtproxyRaw,
		arg.RelayRaw,
		arg.CpuPercent,
		arg.MemUsedPercent,
		arg.DiskUsedPercent,
		arg.DcLatency,
	)
	return err
}

const keyTrafficLast30d = `-- name: KeyTrafficLast30d :many
WITH deltas AS (
  SELECT access_key_id,
         GREATEST(total_octets - lag(total_octets) OVER (
           PARTITION BY access_key_id, node_id ORDER BY taken_at), 0) AS octets
  FROM key_stats_snapshots
  WHERE access_key_id = ANY($1::uuid[]) AND taken_at >= $2
)
SELECT access_key_id, coalesce(sum(octets), 0)::bigint AS traffic FROM deltas GROUP BY access_key_id
`

type KeyTrafficLast30dParams struct {
	KeyIds []uuid.UUID `json:"key_ids"`
	Since  time.Time   `json:"since"`
}

type KeyTrafficLast30dRow struct {
	AccessKeyID uuid.UUID `json:"access_key_id"`
	Traffic     int64     `json:"traffic"`
}

// KeyTrafficLast30d reports, per key, how many octets the key moved inside the window: the sum
// of the positive step-to-step deltas of total_octets on each node, summed over the nodes.
//
// total_octets is a *process-scoped* cumulative counter, so it restarts at zero whenever telemt
// does. Taking the endpoints (last - first) therefore reads a restarted node as negative and
// clamps the whole window to zero, discarding the traffic before the restart as well as after
// it. Summing consecutive deltas and clamping each one instead keeps every complete interval
// and loses only the single step that spans the restart. lag() over (key, node) ordered by time
// gives the previous reading; the first row of each run has no predecessor and GREATEST ignores
// the resulting NULL, so it contributes nothing.
// The whole page of keys is answered by one query - the keys list must not fan out per row.
func (q *Queries) KeyTrafficLast30d(ctx context.Context, arg KeyTrafficLast30dParams) ([]KeyTrafficLast30dRow, error) {
	rows, err := q.db.Query(ctx, keyTrafficLast30d, arg.KeyIds, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeyTrafficLast30dRow{}
	for rows.Next() {
		var i KeyTrafficLast30dRow
		if err := rows.Scan(&i.AccessKeyID, &i.Traffic); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestKeyStatsSnapshots = `-- name: LatestKeyStatsSnapshots :many
SELECT DISTINCT ON (node_id) id, access_key_id, node_id, taken_at, connections, total_octets, quota_used_bytes, active_ips FROM key_stats_snapshots WHERE access_key_id = $1 ORDER BY node_id, taken_at DESC
`

func (q *Queries) LatestKeyStatsSnapshots(ctx context.Context, accessKeyID uuid.UUID) ([]KeyStatsSnapshot, error) {
	rows, err := q.db.Query(ctx, latestKeyStatsSnapshots, accessKeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []KeyStatsSnapshot{}
	for rows.Next() {
		var i KeyStatsSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.AccessKeyID,
			&i.NodeID,
			&i.TakenAt,
			&i.Connections,
			&i.TotalOctets,
			&i.QuotaUsedBytes,
			&i.ActiveIps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestSnapshots = `-- name: LatestSnapshots :many
SELECT DISTINCT ON (node_id) id, node_id, taken_at, sessions_live, streams_live, bytes_up, bytes_down, sessions_created, limit_hits, mtproxy_raw, relay_raw, cpu_percent, mem_used_percent, disk_used_percent, dc_latency FROM node_stats_snapshots ORDER BY node_id, taken_at DESC
`

func (q *Queries) LatestSnapshots(ctx context.Context) ([]NodeStatsSnapshot, error) {
	rows, err := q.db.Query(ctx, latestSnapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeStatsSnapshot{}
	for rows.Next() {
		var i NodeStatsSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.TakenAt,
			&i.SessionsLive,
			&i.StreamsLive,
			&i.BytesUp,
			&i.BytesDown,
			&i.SessionsCreated,
			&i.LimitHits,
			&i.MtproxyRaw,
			&i.RelayRaw,
			&i.CpuPercent,
			&i.MemUsedPercent,
			&i.DiskUsedPercent,
			&i.DcLatency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeyStatsSnapshots = `-- name: ListKeyStatsSnapshots :many
SELECT s.id, s.access_key_id, s.node_id, s.taken_at, s.connections, s.total_octets, s.quota_used_bytes, s.active_ips, n.name AS node_name FROM key_stats_snapshots s JOIN nodes n ON n.id = s.node_id
WHERE s.access_key_id = $1 AND s.taken_at >= $2 AND s.taken_at <= $3
ORDER BY s.node_id, s.taken_at
`

type ListKeyStatsSnapshotsParams struct {
	AccessKeyID uuid.UUID `json:"access_key_id"`
	TakenAt     time.Time `json:"taken_at"`
	TakenAt_2   time.Time `json:"taken_at_2"`
}

type ListKeyStatsSnapshotsRow struct {
	ID             uuid.UUID `json:"id"`
	AccessKeyID    uuid.UUID `json:"access_key_id"`
	NodeID         uuid.UUID `json:"node_id"`
	TakenAt        time.Time `json:"taken_at"`
	Connections    int32     `json:"connections"`
	TotalOctets    int64     `json:"total_octets"`
	QuotaUsedBytes int64     `json:"quota_used_bytes"`
	ActiveIps      int32     `json:"active_ips"`
	NodeName       string    `json:"node_name"`
}

func (q *Queries) ListKeyStatsSnapshots(ctx context.Context, arg ListKeyStatsSnapshotsParams) ([]ListKeyStatsSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listKeyStatsSnapshots, arg.AccessKeyID, arg.TakenAt, arg.TakenAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKeyStatsSnapshotsRow{}
	for rows.Next() {
		var i ListKeyStatsSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccessKeyID,
			&i.NodeID,
			&i.TakenAt,
			&i.Connections,
			&i.TotalOctets,
			&i.QuotaUsedBytes,
			&i.ActiveIps,
			&i.NodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKeyStatsSnapshotsBucketed = `-- name: ListKeyStatsSnapshotsBucketed :many
SELECT s.node_id,
       n.name AS node_name,
       max(s.taken_at)::timestamptz AS taken_at,
       round(avg(s.connections))::int AS connections,
       max(s.total_octets)::bigint AS total_octets
FROM key_stats_snapshots s JOIN nodes n ON n.id = s.node_id
WHERE s.access_key_id = $1
  AND s.taken_at >= $2 AND s.taken_at <= $3
GROUP BY s.node_id, n.name, floor(extract(epoch FROM s.taken_at) / $4::bigint)
ORDER BY s.node_id, 3
`

type ListKeyStatsSnapshotsBucketedParams struct {
	AccessKeyID uuid.UUID `json:"access_key_id"`
	FromAt      time.Time `json:"from_at"`
	ToAt        time.Time `json:"to_at"`
	Step        int64     `json:"step"`
}

type ListKeyStatsSnapshotsBucketedRow struct {
	NodeID      uuid.UUID `json:"node_id"`
	NodeName    string    `json:"node_name"`
	TakenAt     time.Time `json:"taken_at"`
	Connections int32     `json:"connections"`
	TotalOctets int64     `json:"total_octets"`
}

// ListKeyStatsSnapshotsBucketed is ListKeyStatsSnapshots with the thinning done in the
// database, mirroring ListSnapshotsAllNodesBucketed. The unbucketed query returns one row per
// key per node per minute, so a 31-day window is ~45k rows per node that Go loads in full only
// to throw all but 1000 of them away. Bucketing first makes the result O(range/step) per node.
//
// connections is a gauge, so the bucket's average is the honest summary; total_octets is a
// monotonic counter, so the bucket's max is its closing value and consecutive maxima give the
// correct traffic between two buckets. The point's timestamp is max(taken_at), not the bucket
// boundary, so a partial trailing bucket is placed where its data actually ends.
func (q *Queries) ListKeyStatsSnapshotsBucketed(ctx context.Context, arg ListKeyStatsSnapshotsBucketedParams) ([]ListKeyStatsSnapshotsBucketedRow, error) {
	rows, err := q.db.Query(ctx, listKeyStatsSnapshotsBucketed,
		arg.AccessKeyID,
		arg.FromAt,
		arg.ToAt,
		arg.Step,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListKeyStatsSnapshotsBucketedRow{}
	for rows.Next() {
		var i ListKeyStatsSnapshotsBucketedRow
		if err := rows.Scan(
			&i.NodeID,
			&i.NodeName,
			&i.TakenAt,
			&i.Connections,
			&i.TotalOctets,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenAlerts = `-- name: ListOpenAlerts :many
SELECT a.id, a.node_id, a.kind, a.message, a.created_at, a.resolved_at, n.name AS node_name FROM alerts a LEFT JOIN nodes n ON n.id = a.node_id WHERE a.resolved_at IS NULL ORDER BY a.created_at DESC
`

type ListOpenAlertsRow struct {
	ID         int64         `json:"id"`
	NodeID     uuid.NullUUID `json:"node_id"`
	Kind       string        `json:"kind"`
	Message    string        `json:"message"`
	CreatedAt  time.Time     `json:"created_at"`
	ResolvedAt *time.Time    `json:"resolved_at"`
	NodeName   *string       `json:"node_name"`
}

func (q *Queries) ListOpenAlerts(ctx context.Context) ([]ListOpenAlertsRow, error) {
	rows, err := q.db.Query(ctx, listOpenAlerts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenAlertsRow{}
	for rows.Next() {
		var i ListOpenAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Kind,
			&i.Message,
			&i.CreatedAt,
			&i.ResolvedAt,
			&i.NodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshots = `-- name: ListSnapshots :many
SELECT id, node_id, taken_at, sessions_live, streams_live, bytes_up, bytes_down, sessions_created, limit_hits, mtproxy_raw, relay_raw, cpu_percent, mem_used_percent, disk_used_percent, dc_latency FROM node_stats_snapshots WHERE node_id = $1 AND taken_at >= $2 AND taken_at <= $3 ORDER BY taken_at
`

type ListSnapshotsParams struct {
	NodeID    uuid.UUID `json:"node_id"`
	TakenAt   time.Time `json:"taken_at"`
	TakenAt_2 time.Time `json:"taken_at_2"`
}

func (q *Queries) ListSnapshots(ctx context.Context, arg ListSnapshotsParams) ([]NodeStatsSnapshot, error) {
	rows, err := q.db.Query(ctx, listSnapshots, arg.NodeID, arg.TakenAt, arg.TakenAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeStatsSnapshot{}
	for rows.Next() {
		var i NodeStatsSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.TakenAt,
			&i.SessionsLive,
			&i.StreamsLive,
			&i.BytesUp,
			&i.BytesDown,
			&i.SessionsCreated,
			&i.LimitHits,
			&i.MtproxyRaw,
			&i.RelayRaw,
			&i.CpuPercent,
			&i.MemUsedPercent,
			&i.DiskUsedPercent,
			&i.DcLatency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsAllNodes = `-- name: ListSnapshotsAllNodes :many
SELECT node_id, taken_at, sessions_live, streams_live, bytes_up, bytes_down, cpu_percent, mem_used_percent, disk_used_percent, dc_latency
FROM node_stats_snapshots WHERE taken_at >= $1 AND taken_at <= $2 ORDER BY node_id, taken_at
`

type ListSnapshotsAllNodesParams struct {
	TakenAt   time.Time `json:"taken_at"`
	TakenAt_2 time.Time `json:"taken_at_2"`
}

type ListSnapshotsAllNodesRow struct {
	NodeID          uuid.UUID `json:"node_id"`
	TakenAt         time.Time `json:"taken_at"`
	SessionsLive    int32     `json:"sessions_live"`
	StreamsLive     int32     `json:"streams_live"`
	BytesUp         int64     `json:"bytes_up"`
	BytesDown       int64     `json:"bytes_down"`
	CpuPercent      float32   `json:"cpu_percent"`
	MemUsedPercent  float32   `json:"mem_used_percent"`
	DiskUsedPercent float32   `json:"disk_used_percent"`
	DcLatency       []byte    `json:"dc_latency"`
}

func (q *Queries) ListSnapshotsAllNodes(ctx context.Context, arg ListSnapshotsAllNodesParams) ([]ListSnapshotsAllNodesRow, error) {
	rows, err := q.db.Query(ctx, listSnapshotsAllNodes, arg.TakenAt, arg.TakenAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSnapshotsAllNodesRow{}
	for rows.Next() {
		var i ListSnapshotsAllNodesRow
		if err := rows.Scan(
			&i.NodeID,
			&i.TakenAt,
			&i.SessionsLive,
			&i.StreamsLive,
			&i.BytesUp,
			&i.BytesDown,
			&i.CpuPercent,
			&i.MemUsedPercent,
			&i.DiskUsedPercent,
			&i.DcLatency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSnapshotsAllNodesBucketed = `-- name: ListSnapshotsAllNodesBucketed :many
WITH scalars AS (
  SELECT r.node_id,
         floor(extract(epoch FROM r.taken_at) / $1::bigint) AS bucket,
         max(r.taken_at)::timestamptz AS taken_at,
         round(avg(r.sessions_live))::int AS sessions_live,
         round(avg(r.streams_live))::int AS streams_live,
         max(r.bytes_up)::bigint AS bytes_up,
         max(r.bytes_down)::bigint AS bytes_down,
         avg(r.cpu_percent)::real AS cpu_percent,
         avg(r.mem_used_percent)::real AS mem_used_percent,
         avg(r.disk_used_percent)::real AS disk_used_percent
  FROM node_stats_snapshots r
  WHERE r.taken_at >= $2 AND r.taken_at <= $3
  GROUP BY r.node_id, 2
), per_dc AS (
  SELECT s.node_id,
         floor(extract(epoch FROM s.taken_at) / $1::bigint) AS bucket,
         d.key AS dc,
         avg((d.value #>> '{}')::float8) AS latency_ms
  FROM node_stats_snapshots s, jsonb_each(s.dc_latency) AS d(key, value)
  WHERE s.taken_at >= $2 AND s.taken_at <= $3
  GROUP BY s.node_id, 2, d.key
), dc AS (
  SELECT node_id, bucket, jsonb_object_agg(dc, latency_ms) AS dc_latency
  FROM per_dc GROUP BY node_id, bucket
)
SELECT scalars.node_id,
       scalars.taken_at,
       scalars.sessions_live,
       scalars.streams_live,
       scalars.bytes_up,
       scalars.bytes_down,
       scalars.cpu_percent,
       scalars.mem_used_percent,
       scalars.disk_used_percent,
       coalesce(dc.dc_latency, '{}'::jsonb)::jsonb AS dc_latency
FROM scalars
LEFT JOIN dc ON dc.node_id = scalars.node_id AND dc.bucket = scalars.bucket
ORDER BY scalars.node_id, scalars.taken_at
`

type ListSnapshotsAllNodesBucketedParams struct {
	Step   int64     `json:"step"`
	FromAt time.Time `json:"from_at"`
	ToAt   time.Time `json:"to_at"`
}

type ListSnapshotsAllNodesBucketedRow struct {
	NodeID          uuid.UUID `json:"node_id"`
	TakenAt         time.Time `json:"taken_at"`
	SessionsLive    int32     `json:"sessions_live"`
	StreamsLive     int32     `json:"streams_live"`
	BytesUp         int64     `json:"bytes_up"`
	BytesDown       int64     `json:"bytes_down"`
	CpuPercent      float32   `json:"cpu_percent"`
	MemUsedPercent  float32   `json:"mem_used_percent"`
	DiskUsedPercent float32   `json:"disk_used_percent"`
	DcLatency       []byte    `json:"dc_latency"`
}

// ListSnapshotsAllNodesBucketed collapses snapshots into fixed-width time buckets in the
// database. The unbucketed query returns one row per node per minute, so a wide range is
// bounded only by retention (30 days x 1440/day x N nodes) and the whole set has to be
// materialised in Go before it can be thinned. Bucketing first makes the result size
// O(range/step) per node instead.
//
// sessions_live/streams_live are gauges, so the bucket's average is the honest summary;
// bytes_up/bytes_down are monotonic counters, so the bucket's max is its closing value and
// consecutive maxima give the correct average rate over the interval between the buckets'
// closing timestamps. The point's own timestamp is max(taken_at) rather than the bucket
// boundary for exactly that reason: a partial trailing bucket would otherwise be divided by
// the full step width and under-report the current rate. The load percentages are gauges
// like the session counts and get the same average. node_stats_node_time_idx
// (node_id, taken_at DESC) covers the scan.
//
// dc_latency is a {"<dc>": <ms>} object per row, averaged per DC over the rows of the bucket
// that carry that DC (a row without the key is "unknown", not 0, so it must not drag the
// mean down). That is a second pass over the same rows: the keys are unnested with
// jsonb_each, averaged per (node, bucket, dc) and folded back into one object per bucket,
// then joined onto the scalar aggregates by bucket. A bucket none of whose rows measured any
// DC gets '{}'.
func (q *Queries) ListSnapshotsAllNodesBucketed(ctx context.Context, arg ListSnapshotsAllNodesBucketedParams) ([]ListSnapshotsAllNodesBucketedRow, error) {
	rows, err := q.db.Query(ctx, listSnapshotsAllNodesBucketed, arg.Step, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSnapshotsAllNodesBucketedRow{}
	for rows.Next() {
		var i ListSnapshotsAllNodesBucketedRow
		if err := rows.Scan(
			&i.NodeID,
			&i.TakenAt,
			&i.SessionsLive,
			&i.StreamsLive,
			&i.BytesUp,
			&i.BytesDown,
			&i.CpuPercent,
			&i.MemUsedPercent,
			&i.DiskUsedPercent,
			&i.DcLatency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAlert = `-- name: ResolveAlert :exec
UPDATE alerts SET resolved_at = now() WHERE id = $1
`

func (q *Queries) ResolveAlert(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, resolveAlert, id)
	return err
}

const resolveNodeAlerts = `-- name: ResolveNodeAlerts :execrows
UPDATE alerts SET resolved_at = now() WHERE node_id = $1 AND kind = $2 AND resolved_at IS NULL
`

type ResolveNodeAlertsParams struct {
	NodeID uuid.NullUUID `json:"node_id"`
	Kind   string        `json:"kind"`
}

// ResolveNodeAlerts reports the number of rows it actually closed (:execrows)
// so callers can tell "an alert was open and just got resolved" from "there was
// nothing to resolve" without a separate SELECT.
func (q *Queries) ResolveNodeAlerts(ctx context.Context, arg ResolveNodeAlertsParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveNodeAlerts, arg.NodeID, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
