// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telemtupdate.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTelemtUpdateJob = `-- name: CreateTelemtUpdateJob :one
INSERT INTO telemt_update_jobs (node_id, from_version, to_version)
VALUES ($1, $2, $3) RETURNING id, node_id, status, outcome, from_version, to_version, error, steps, verification, started_at, finished_at
`

type CreateTelemtUpdateJobParams struct {
	NodeID      uuid.UUID `json:"node_id"`
	FromVersion string    `json:"from_version"`
	ToVersion   string    `json:"to_version"`
}

func (q *Queries) CreateTelemtUpdateJob(ctx context.Context, arg CreateTelemtUpdateJobParams) (TelemtUpdateJob, error) {
	row := q.db.QueryRow(ctx, createTelemtUpdateJob, arg.NodeID, arg.FromVersion, arg.ToVersion)
	var i TelemtUpdateJob
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Status,
		&i.Outcome,
		&i.FromVersion,
		&i.ToVersion,
		&i.Error,
		&i.Steps,
		&i.Verification,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishTelemtUpdateJob = `-- name: FinishTelemtUpdateJob :one
UPDATE telemt_update_jobs SET status = $2, outcome = $3, error = $4, steps = $5,
  from_version = COALESCE(NULLIF($6::text, ''), from_version),
  finished_at = now()
WHERE id = $1 RETURNING id, node_id, status, outcome, from_version, to_version, error, steps, verification, started_at, finished_at
`

type FinishTelemtUpdateJobParams struct {
	ID          uuid.UUID `json:"id"`
	Status      string    `json:"status"`
	Outcome     string    `json:"outcome"`
	Error       string    `json:"error"`
	Steps       []byte    `json:"steps"`
	FromVersion string    `json:"from_version"`
}

func (q *Queries) FinishTelemtUpdateJob(ctx context.Context, arg FinishTelemtUpdateJobParams) (TelemtUpdateJob, error) {
	row := q.db.QueryRow(ctx, finishTelemtUpdateJob,
		arg.ID,
		arg.Status,
		arg.Outcome,
		arg.Error,
		arg.Steps,
		arg.FromVersion,
	)
	var i TelemtUpdateJob
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Status,
		&i.Outcome,
		&i.FromVersion,
		&i.ToVersion,
		&i.Error,
		&i.Steps,
		&i.Verification,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRunningTelemtUpdateJob = `-- name: GetRunningTelemtUpdateJob :one
SELECT id, node_id, status, outcome, from_version, to_version, error, steps, verification, started_at, finished_at FROM telemt_update_jobs WHERE node_id = $1 AND finished_at IS NULL
ORDER BY started_at DESC LIMIT 1
`

// GetRunningTelemtUpdateJob is what refuses a second update while one is in flight.
func (q *Queries) GetRunningTelemtUpdateJob(ctx context.Context, nodeID uuid.UUID) (TelemtUpdateJob, error) {
	row := q.db.QueryRow(ctx, getRunningTelemtUpdateJob, nodeID)
	var i TelemtUpdateJob
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Status,
		&i.Outcome,
		&i.FromVersion,
		&i.ToVersion,
		&i.Error,
		&i.Steps,
		&i.Verification,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getTelemtUpdateJob = `-- name: GetTelemtUpdateJob :one
SELECT id, node_id, status, outcome, from_version, to_version, error, steps, verification, started_at, finished_at FROM telemt_update_jobs WHERE id = $1
`

func (q *Queries) GetTelemtUpdateJob(ctx context.Context, id uuid.UUID) (TelemtUpdateJob, error) {
	row := q.db.QueryRow(ctx, getTelemtUpdateJob, id)
	var i TelemtUpdateJob
	err := row.Scan(
		&i.ID,
		&i.NodeID,
		&i.Status,
		&i.Outcome,
		&i.FromVersion,
		&i.ToVersion,
		&i.Error,
		&i.Steps,
		&i.Verification,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listNodeTelemtUpdateJobs = `-- name: ListNodeTelemtUpdateJobs :many
SELECT id, node_id, status, outcome, from_version, to_version, error, steps, verification, started_at, finished_at FROM telemt_update_jobs WHERE node_id = $1 ORDER BY started_at DESC LIMIT $2
`

type ListNodeTelemtUpdateJobsParams struct {
	NodeID uuid.UUID `json:"node_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) ListNodeTelemtUpdateJobs(ctx context.Context, arg ListNodeTelemtUpdateJobsParams) ([]TelemtUpdateJob, error) {
	rows, err := q.db.Query(ctx, listNodeTelemtUpdateJobs, arg.NodeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TelemtUpdateJob{}
	for rows.Next() {
		var i TelemtUpdateJob
		if err := rows.Scan(
			&i.ID,
			&i.NodeID,
			&i.Status,
			&i.Outcome,
			&i.FromVersion,
			&i.ToVersion,
			&i.Error,
			&i.Steps,
			&i.Verification,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNodeTelemtUpdateAvailable = `-- name: SetNodeTelemtUpdateAvailable :exec
UPDATE nodes SET telemt_update_available = $2 WHERE id = $1
`

type SetNodeTelemtUpdateAvailableParams struct {
	ID                    uuid.UUID `json:"id"`
	TelemtUpdateAvailable string    `json:"telemt_update_available"`
}

func (q *Queries) SetNodeTelemtUpdateAvailable(ctx context.Context, arg SetNodeTelemtUpdateAvailableParams) error {
	_, err := q.db.Exec(ctx, setNodeTelemtUpdateAvailable, arg.ID, arg.TelemtUpdateAvailable)
	return err
}

const setTelemtUpdateJobSteps = `-- name: SetTelemtUpdateJobSteps :exec
UPDATE telemt_update_jobs SET steps = $2 WHERE id = $1
`

type SetTelemtUpdateJobStepsParams struct {
	ID    uuid.UUID `json:"id"`
	Steps []byte    `json:"steps"`
}

func (q *Queries) SetTelemtUpdateJobSteps(ctx context.Context, arg SetTelemtUpdateJobStepsParams) error {
	_, err := q.db.Exec(ctx, setTelemtUpdateJobSteps, arg.ID, arg.Steps)
	return err
}

const setTelemtUpdateJobVerification = `-- name: SetTelemtUpdateJobVerification :exec
UPDATE telemt_update_jobs SET verification = $2 WHERE id = $1
`

type SetTelemtUpdateJobVerificationParams struct {
	ID           uuid.UUID `json:"id"`
	Verification []byte    `json:"verification"`
}

func (q *Queries) SetTelemtUpdateJobVerification(ctx context.Context, arg SetTelemtUpdateJobVerificationParams) error {
	_, err := q.db.Exec(ctx, setTelemtUpdateJobVerification, arg.ID, arg.Verification)
	return err
}
